const token=localStorage.getItem('sovan-auth-token'),$=s=>document.querySelector(s);
const fmtBytes=n=>{n=Number(n||0);if(n<1e6)return `${(n/1e3).toFixed(n<1e5?1:0)} KB`;if(n<1e9)return `${(n/1e6).toFixed(n<1e8?1:0)} MB`;return `${(n/1e9).toFixed(1)} GB`};
async function request(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
async function init(){if(!token){location.href='dashboard.html';return}try{const [me,usage]=await Promise.all([request('/api/auth/me'),request('/api/account/usage')]);if(!me.user)throw Error('Sign in required');$('#accountEmail').textContent=me.user.email;$('#accountRole').textContent=me.user.role||'customer';$('#accountPlan').textContent=(usage.plan||me.user.plan||'free').replace(/^./,c=>c.toUpperCase());const verified=Boolean(me.user.emailVerified??me.user.email_verified);$('#emailVerificationStatus').textContent=verified?'Verified':'Not verified';$('#requestVerification').hidden=verified;const u=usage.usage||{},l=usage.limits||{};$('#usageInvitations').textContent=`${u.invitations||0} / ${l.invitations??'—'}`;$('#usageTemplates').textContent=`${u.templates||0} / ${l.templates??'—'}`;$('#usageStorage').textContent=`${fmtBytes(u.storageBytes)} / ${fmtBytes(l.storageBytes)}`;$('#usageNote').textContent=usage.enforced?'Your plan limits are currently enforced.':'Usage limits are informational in this development build; an administrator can assign plans manually.'}catch{location.href='dashboard.html'}}
$('#passwordForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),status=$('#passwordStatus');if(data.newPassword!==data.confirmPassword){status.textContent='The new passwords do not match.';return}status.textContent='Changing password…';try{await request('/api/auth/password',{method:'PUT',body:JSON.stringify({currentPassword:data.currentPassword,newPassword:data.newPassword})});e.target.reset();status.textContent='Password changed. Other signed-in sessions were ended.'}catch(err){status.textContent=err.message}}
$('#exportAccount').onclick=async()=>{const status=$('#exportStatus');status.textContent='Preparing export…';try{const data=await request('/api/account/export'),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`e-invitation-website-account-export-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent='Export downloaded.'}catch(err){status.textContent=err.message}}
init();

$('#requestVerification').onclick=async()=>{const status=$('#verificationMessage');status.textContent='Sending verification email…';try{const result=await request('/api/auth/verification/request',{method:'POST',body:'{}'});status.innerHTML=result.verified?'Your email is already verified.':result.sent?'Verification email sent.':'Verification token created, but SMTP delivery is not configured.';if(result.devToken)status.innerHTML+=` <a href="verify.html?token=${encodeURIComponent(result.devToken)}">Development verification link</a>`}catch(error){status.textContent=error.message}};
