const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const activeInviteId=localStorage.getItem('sovan-active-invite')||'demo-wedding';
const draftKey=`sovan-invite-draft-v3:${activeInviteId}`,publishKey=`sovan-invite-published-v3:${activeInviteId}`,historyKey=`sovan-invite-history-v3:${activeInviteId}`,rsvpKey=`sovan-invite-rsvps-v3:${activeInviteId}`;
let selected=null,saveTimer,serverInvite=inviteStore.read(`sovan-server-invite:${activeInviteId}`);
async function api(path,options={}){let token=localStorage.getItem('sovan-auth-token'),r=await fetch(path,{headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})},...options});if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||'Server request failed');return r.json()}
async function connectServer(){try{await api('/api/health');if(!serverInvite){let names=state?.fields?.names||'our invitation';serverInvite=await api('/api/invitations',{method:'POST',body:JSON.stringify({slug:names.replace(/&/g,' and '),document:state})});inviteStore.write(`sovan-server-invite:${activeInviteId}`,serverInvite)}$('#serverState').textContent='Server connected'}catch{$('#serverState').textContent='Local mode'}}
async function saveServerDraft(){if(!serverInvite)return;try{await api('/api/invitations/'+serverInvite.id,{method:'PUT',body:JSON.stringify({document:capture()})})}catch{$('#serverState').textContent='Offline — saved locally'}}
const initial={fields:{names:'Sophea & Dara',date:'2026-12-27',venue:'The Riverside Ballroom, Phnom Penh',message:'Together with our families, we warmly invite you to celebrate our wedding.'},accent:'#9d4555',objects:{}};
let state=inviteStore.read(draftKey,inviteStore.read('sovan-invite-draft-v3',initial));
function capture(){state.fields={names:$('#names').value,date:$('#date').value,venue:$('#venue').value,message:$('#message').value};state.accent=$('#accent').value;$$('.object').forEach(o=>state.objects[o.dataset.id]={left:o.style.left,top:o.style.top,width:o.style.width,height:o.style.height,font:o.dataset.font||'',color:o.dataset.color||'',animation:o.dataset.animation||'fade-up',duration:o.dataset.duration||'900',html:o.querySelector('.content')?.innerHTML,src:o.querySelector('img')?.src,type:o.classList.contains('image-object')?'image':'text'});return state}
function save(){capture();$('#saveState').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{inviteStore.write(draftKey,state);$('#saveState').textContent='Saved';saveServerDraft()},350)}
function apply(){Object.entries(state.fields||{}).forEach(([k,v])=>{if($('#'+k))$('#'+k).value=v});document.documentElement.style.setProperty('--accent',state.accent||'#9d4555');$('#accent').value=state.accent||'#9d4555';Object.entries(state.objects||{}).forEach(([id,d])=>{let o=$(`[data-id="${id}"]`);if(!o){o=createObject(id,d.type);$('#stage').append(o)};['left','top','width','height'].forEach(k=>o.style[k]=d[k]);o.dataset.font=d.font||'';o.dataset.color=d.color||'';o.dataset.animation=d.animation||'fade-up';o.dataset.duration=d.duration||'900';if(o.querySelector('.content')){o.querySelector('.content').innerHTML=d.html||'';o.querySelector('.content').style.fontFamily=d.font;o.querySelector('.content').style.color=d.color}if(o.querySelector('img')&&d.src)o.querySelector('img').src=d.src});syncFields();refreshPublish()}
function createObject(id,type){let o=document.createElement('div');o.className=`object ${type}-object`;o.dataset.id=id;o.style.cssText='left:20%;top:40%;width:60%;height:100px';o.innerHTML=type==='image'?'<img alt="Uploaded"><i></i>':'<div class="content">New text</div><i></i>';wireObject(o);return o}
function syncFields(){$('[data-id="title"] .content').textContent=$('#names').value;$('[data-id="subtitle"] .content').textContent=$('#message').value;let dt=new Date($('#date').value+'T00:00:00');let label=isNaN(dt)?$('#date').value:dt.toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'});$('[data-id="details"] .content').innerHTML=`${label}<br>${$('#venue').value}`;save()}
['names','date','venue','message'].forEach(id=>$('#'+id).addEventListener('input',syncFields));$('#accent').addEventListener('input',e=>{document.documentElement.style.setProperty('--accent',e.target.value);save()});
function wireObject(o){o.addEventListener('pointerdown',e=>{select(o);let resize=e.target.tagName==='I',sx=e.clientX,sy=e.clientY,r=o.getBoundingClientRect(),p=$('#stage').getBoundingClientRect();o.setPointerCapture(e.pointerId);const move=x=>{if(resize){o.style.width=Math.max(50,r.width+x.clientX-sx)+'px';o.style.height=Math.max(40,r.height+x.clientY-sy)+'px'}else{o.style.left=((r.left-p.left+x.clientX-sx)/p.width*100)+'%';o.style.top=((r.top-p.top+x.clientY-sy)/p.height*100)+'%'}};o.onpointermove=move;o.onpointerup=()=>{o.onpointermove=null;save()};e.preventDefault()})}
function select(o){$$('.object').forEach(x=>x.classList.remove('selected'));selected=o;o.classList.add('selected');$('#noSelection').hidden=true;$('#properties').hidden=false;$('#font').value=o.dataset.font||'Georgia,serif';$('#color').value=o.dataset.color||'#47252d';$('#animation').value=o.dataset.animation||'fade-up';$('#duration').value=o.dataset.duration||'900'}
$$('.object').forEach(wireObject);$('#font').onchange=e=>{if(selected){selected.dataset.font=e.target.value;let c=selected.querySelector('.content');if(c)c.style.fontFamily=e.target.value;save()}};$('#color').oninput=e=>{if(selected){selected.dataset.color=e.target.value;let c=selected.querySelector('.content');if(c)c.style.color=e.target.value;save()}};$('#animation').onchange=e=>{if(selected){selected.dataset.animation=e.target.value;save()}};$('#duration').oninput=e=>{if(selected){selected.dataset.duration=e.target.value;save()}};
$('#deleteBtn').onclick=()=>{if(selected&&!['title','subtitle','details','hero'].includes(selected.dataset.id)){selected.remove();selected=null;$('#properties').hidden=true;save()}};$('#duplicate').onclick=()=>{if(!selected)return;let data=capture().objects[selected.dataset.id],id='obj-'+Date.now(),o=createObject(id,data.type);$('#stage').append(o);Object.assign(o.style,{left:(parseFloat(selected.style.left)+4)+'%',top:(parseFloat(selected.style.top)+3)+'%',width:selected.style.width,height:selected.style.height});if(data.type==='image')o.querySelector('img').src=data.src;else o.querySelector('.content').innerHTML=data.html;save()};$('#addText').onclick=()=>{let o=createObject('text-'+Date.now(),'text');$('#stage').append(o);select(o);save()};
$$('[data-device]').forEach(b=>b.onclick=()=>$('#stage').style.width=Math.min(+b.dataset.device,$('.stage-wrap').clientWidth-36)+'px');
$('#photoUpload').onchange=async e=>{let file=e.target.files[0];if(!file)return;if(file.size>15e6)return alert('Please choose an image under 15 MB.');try{await assetStore.put({id:Date.now(),name:file.name,type:file.type,size:file.size,blob:file,createdAt:new Date().toISOString()});await renderAssets()}catch{alert('The material could not be stored in this browser.')}};
async function renderAssets(){let assets=await assetStore.list();$('#assets').innerHTML='';assets.forEach(a=>{let img=new Image,src=URL.createObjectURL(a.blob);img.src=src;img.title=`${a.name} — click to add`;img.onclick=()=>{let o=createObject('img-'+Date.now(),'image');let reader=new FileReader();reader.onload=()=>{o.querySelector('img').src=reader.result;$('#stage').append(o);select(o);save()};reader.readAsDataURL(a.blob)};img.oncontextmenu=async e=>{e.preventDefault();if(confirm(`Remove ${a.name} from materials?`)){URL.revokeObjectURL(src);await assetStore.delete(a.id);renderAssets()}};$('#assets').append(img)})}renderAssets();
function snapshot(){return {id:crypto.randomUUID?.()||Date.now()+'',version:Date.now(),publishedAt:new Date().toISOString(),document:structuredClone(capture())}}
$('#publishBtn').onclick=async()=>{let snap=snapshot();inviteStore.write(publishKey,snap);inviteStore.append(historyKey,snap);let message='Published locally. Guest preview now uses an immutable snapshot.';if(serverInvite){try{let result=await api('/api/invitations/'+serverInvite.id+'/publish',{method:'POST',body:JSON.stringify({document:snap.document})});message=`Published! Public URL: ${location.origin+result.url}`;$('#publishInfo').dataset.publicUrl=result.url}catch{message+=' Server publishing is temporarily unavailable.'}}refreshPublish();alert(message)};
function refreshPublish(){let p=inviteStore.read(publishKey);$('#publishInfo').innerHTML=p?`<strong>Published</strong><br>${new Date(p.publishedAt).toLocaleString()}<br>Snapshot ${String(p.version).slice(-6)}`:'No snapshot published yet.'}
function guestHTML(snap){let d=snap.document,f=d.fields,objs=Object.values(d.objects),hero=objs.find(x=>x.type==='image')?.src||'';let anim=objs[0]?.animation||'fade-up';let key={"fade-up":'fadeUp',"soft-zoom":'softZoom',"slide-left":'slideLeft',float:'float',none:''}[anim];return `<div class="guest"><p>YOU ARE INVITED</p><h1 class="reveal" style="animation-name:${key}">${f.names}</h1>${hero?`<img class="reveal" style="animation-delay:.2s;animation-name:${key}" src="${hero}">`:''}<h2>${new Date(f.date+'T00:00:00').toLocaleDateString(undefined,{dateStyle:'long'})}</h2><p>${f.message}</p><p><strong>${f.venue}</strong></p><form id="guestRsvp"><h2>RSVP</h2><label>Your name<input name="name" required></label><label>Will you attend?<select name="status"><option>Yes, joyfully</option><option>Unable to attend</option><option>Maybe</option></select></label><label>Number of guests<input name="count" type="number" min="1" max="10" value="1"></label><label>Message<textarea name="note"></textarea></label><button class="primary">Send RSVP</button></form></div>`}
function openGuest(){let p=inviteStore.read(publishKey)||snapshot();$('#modalBody').innerHTML=guestHTML(p);$('#modal').showModal();$('#guestRsvp').onsubmit=e=>{e.preventDefault();let rec=Object.fromEntries(new FormData(e.target));rec.id=crypto.randomUUID?.()||Date.now()+'';rec.createdAt=new Date().toISOString();rec.publishVersion=p.version;inviteStore.append(rsvpKey,rec);e.target.innerHTML='<h2>Thank you!</h2><p>Your response has been saved.</p>'}}
$('#previewBtn').onclick=openGuest;$('#rsvpBtn').onclick=()=>{let rs=inviteStore.read(rsvpKey,[]);$('#modalBody').innerHTML=`<div class="responses"><h1>RSVP responses (${rs.length})</h1>${rs.length?rs.map(r=>`<div class="response"><strong>${r.name}</strong> · ${r.status} · ${r.count} guest(s)<br><small>${r.note||''}</small></div>`).join(''):'<p>No responses yet. Submit one through Guest preview.</p>'}</div>`;$('#modal').showModal()};
$('#historyBtn').onclick=()=>{let items=inviteStore.read(historyKey,[]).slice().reverse();$('#modalBody').innerHTML=`<div class="responses"><h1>Published versions</h1>${items.length?items.map((p,i)=>`<div class="response"><strong>Version ${String(p.version).slice(-6)}</strong><br>${new Date(p.publishedAt).toLocaleString()} <button data-restore-version="${p.version}">Restore as draft</button></div>`).join(''):'<p>No versions published yet.</p>'}</div>`;$('#modal').showModal();$$('[data-restore-version]').forEach(b=>b.onclick=()=>{let p=items.find(x=>String(x.version)===b.dataset.restoreVersion);state=structuredClone(p.document);inviteStore.write(draftKey,state);location.reload()})};
$('#backupBtn').onclick=()=>{let payload={format:'sovan-invite-backup',version:1,exportedAt:new Date().toISOString(),draft:capture(),published:inviteStore.read(publishKey),history:inviteStore.read(historyKey,[]),rsvps:inviteStore.read(rsvpKey,[])};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`invitation-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#restoreBtn').onclick=()=>$('#restoreFile').click();$('#restoreFile').onchange=async e=>{try{let data=JSON.parse(await e.target.files[0].text());if(data.format!=='sovan-invite-backup'||!data.draft)throw Error();inviteStore.write(draftKey,data.draft);if(data.published)inviteStore.write(publishKey,data.published);inviteStore.write(historyKey,data.history||[]);inviteStore.write(rsvpKey,data.rsvps||[]);location.reload()}catch{alert('This is not a valid Sovan Invite backup.')}};
$('.close').onclick=()=>$('#modal').close();apply();connectServer();
