const $=s=>document.querySelector(s),token=localStorage.getItem('sovan-auth-token');
const plans={free:{name:'Free',invitations:3,templates:5,storageBytes:250_000_000,features:['Create and publish invitations','Basic templates and editor','RSVP and guest tools','250 MB material storage']},creator:{name:'Creator',invitations:50,templates:100,storageBytes:5_000_000_000,features:['Higher invitation capacity','Large reusable template library','5 GB material storage','Designed for frequent creators']},studio:{name:'Studio',invitations:500,templates:1000,storageBytes:50_000_000_000,features:['High-volume invitation production','Designer and studio workflows','50 GB material storage','Best fit for professional teams']}};
const fmtBytes=n=>{n=Number(n||0);if(n<1e6)return `${(n/1e3).toFixed(n<1e5?1:0)} KB`;if(n<1e9)return `${(n/1e6).toFixed(n<1e8?1:0)} MB`;return `${(n/1e9).toFixed(1)} GB`};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
function meter(value,limit){const percent=limit?Math.min(100,Math.round(value/limit*100)):0;return `<div class="meter"><i style="width:${percent}%"></i></div><small>${percent}% used</small>`}
async function init(){if(!token){location.href='dashboard.html';return}try{const [me,usage]=await Promise.all([api('/api/auth/me'),api('/api/account/usage')]);if(!me.user)throw Error('Sign in required');const plan=usage.plan||me.user.plan||'free';$('#currentPlan').textContent=plans[plan]?.name||plan;$('#planRole').textContent=`${me.user.role||'customer'} account`;
 const u=usage.usage,l=usage.limits;$('#usageGrid').innerHTML=`<article class="usage-card"><small>Invitations</small><strong>${u.invitations} / ${l.invitations}</strong>${meter(u.invitations,l.invitations)}</article><article class="usage-card"><small>Reusable templates</small><strong>${u.templates} / ${l.templates}</strong>${meter(u.templates,l.templates)}</article><article class="usage-card"><small>Material storage</small><strong>${fmtBytes(u.storageBytes)} / ${fmtBytes(l.storageBytes)}</strong>${meter(u.storageBytes,l.storageBytes)}</article>`;
 $('#planCards').innerHTML=Object.entries(plans).map(([key,p])=>`<article class="plan ${key===plan?'current':''}"><span class="badge">${key===plan?'Current plan':'Available tier'}</span><h2>${p.name}</h2><p>${p.invitations} active invitations · ${p.templates} templates · ${fmtBytes(p.storageBytes)} storage</p><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul>${key===plan?'<button disabled>Current plan</button>':'<button type="button" data-plan-interest="'+key+'">Contact administrator</button>'}</article>`).join('');document.querySelectorAll('[data-plan-interest]').forEach(b=>b.onclick=async()=>{b.disabled=true;const old=b.textContent;b.textContent='Preparing checkout…';try{const result=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({plan:b.dataset.planInterest})});location.href=result.url}catch(error){uiAlert(error.message,{title:'Checkout unavailable'})}finally{b.disabled=false;b.textContent=old}});
 if(!usage.enforced)$('#billingNotice').textContent='Usage limits are currently informational and not automatically enforced. No payment gateway is connected; administrators can manually assign Free, Creator, or Studio plans.';
 }catch(e){document.querySelector('.billing-page').innerHTML=`<h1>Plans unavailable</h1><p>${String(e.message)}</p><a href="dashboard.html"><button>Back to dashboard</button></a>`}}
init();
