(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s); if(!$('#stage'))return;
const token=()=>localStorage.getItem('sovan-auth-token');
const inviteId=()=>window.serverInvite?.id||localStorage.getItem('sovan-active-invite');
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
const sharePane=document.querySelector('[data-inspector-pane="publish"]')||document.querySelector('.right');if(!sharePane)return;
const section=document.createElement('section');section.className='ei-collab-card';section.innerHTML=`<div><small>Collaboration</small><h2>Invite collaborators</h2><p class="hint">Share editing access with another registered account. Owners and managers can manage collaborators.</p></div><div class="ei-collab-form"><input id="eiCollabEmail" type="email" placeholder="name@example.com"><select id="eiCollabRole"><option value="viewer">Can view</option><option value="content">Edit content</option><option value="designer">Edit design</option><option value="manager">Manage project</option></select><button id="eiCollabAdd" type="button">Invite</button></div><div id="eiCollabState" class="hint"></div><div id="eiCollabList" class="ei-collab-list"></div>`;sharePane.append(section);
async function load(){const id=inviteId();if(!id||!token()){section.hidden=true;return}section.hidden=false;const state=$('#eiCollabState');try{const rows=await api(`/api/invitations/${id}/collaborators`);state.textContent=rows.length?`${rows.length} collaborator${rows.length===1?'':'s'}`:'No collaborators yet.';const list=$('#eiCollabList');list.innerHTML='';rows.forEach(row=>{const el=document.createElement('div');el.className='ei-collab-row';el.innerHTML=`<div><strong></strong><small></small></div><span></span><button type="button" class="danger">Remove</button>`;el.querySelector('strong').textContent=row.email;el.querySelector('small').textContent='Registered collaborator';el.querySelector('span').textContent=row.role;el.querySelector('button').onclick=async()=>{if(!(await uiConfirm(`Remove ${row.email} from this invitation?`,{title:'Remove collaborator',danger:true,confirmText:'Remove'})))return;try{await api(`/api/invitations/${id}/collaborators/${row.userId}`,{method:'DELETE'});uiToast('Collaborator removed','✓');load()}catch(e){uiAlert(e.message)}};list.append(el)})}catch(e){state.textContent=e.message;$('#eiCollabList').innerHTML=''}}
$('#eiCollabAdd').onclick=async()=>{const email=$('#eiCollabEmail').value.trim(),role=$('#eiCollabRole').value;if(!email)return;try{await api(`/api/invitations/${inviteId()}/collaborators`,{method:'POST',body:JSON.stringify({email,role})});$('#eiCollabEmail').value='';uiToast('Collaborator added','✓');load()}catch(e){uiAlert(e.message)}};
setTimeout(load,900);document.addEventListener('einvite:server-connected',load);
})();
