(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s);if(!$('#stage'))return;const pane=document.querySelector('[data-studio-pane="elements"]');if(!pane)return;
const packs=[
 {name:'Khmer Ceremony',desc:'Gold ceremonial title, dividers and lotus marks.',preview:'✾  ◇  ✾',items:[['text','សិរីមង្គលអាពាហ៍ពិពាហ៍',{font:"'Khmer OS Muol Light','Noto Serif Khmer',serif",fontSize:34,color:'#a87616',top:12,left:10,width:80}],['decoration','✾',{fontSize:58,color:'#a87616',top:35,left:15,width:18}],['decoration','◇',{fontSize:52,color:'#a87616',top:36,left:41,width:18}],['decoration','✾',{fontSize:58,color:'#a87616',top:35,left:67,width:18}]]},
 {name:'Botanical Header',desc:'Soft leaf ornaments with an editorial heading.',preview:'❧  A  ❧',items:[['decoration','❧',{fontSize:62,color:'#477a64',top:14,left:8,width:18,rotation:-16}],['text','OUR CELEBRATION',{font:'Georgia,serif',fontSize:32,color:'#335a4a',top:18,left:24,width:52,letterSpacing:3}],['decoration','❧',{fontSize:62,color:'#477a64',top:14,left:74,width:18,rotation:16}]]},
 {name:'Luxury Divider',desc:'Gold divider for elegant wedding and gala pages.',preview:'— ✦ —',items:[['shape','line',{fillColor:'#c6a35b',top:48,left:16,width:25,height:1}],['decoration','✦',{fontSize:38,color:'#c6a35b',top:44,left:44,width:12}],['shape','line',{fillColor:'#c6a35b',top:48,left:59,width:25,height:1}]]},
 {name:'Photo Caption',desc:'Framed photo placeholder with a refined caption.',preview:'▣  Aa',items:[['shape','rectangle',{fillColor:'#f3eee7',top:18,left:10,width:80,height:55,borderRadius:20}],['text','A MOMENT TO REMEMBER',{font:'Georgia,serif',fontSize:24,color:'#563b42',top:77,left:15,width:70,letterSpacing:2}]]},
 {name:'Birthday Spark',desc:'Colorful title and celebratory sparkle cluster.',preview:'✦ 🎉 ✦',items:[['decoration','✦',{fontSize:48,color:'#ff5e91',top:14,left:15,width:15}],['text','LET’S CELEBRATE',{font:'Arial,sans-serif',fontSize:38,color:'#6842b8',top:18,left:22,width:60,fontWeight:'700'}],['decoration','✦',{fontSize:48,color:'#33c7d8',top:14,left:72,width:15}]]},
 {name:'Executive Label',desc:'Modern business event heading with accent rule.',preview:'▌ EVENT',items:[['shape','rectangle',{fillColor:'#1d4f6e',top:20,left:10,width:2,height:15}],['text','EVENT HIGHLIGHT',{font:'Arial,sans-serif',fontSize:28,color:'#1d3446',top:20,left:16,width:68,fontWeight:'700',letterSpacing:1.5}]]}
];
const section=document.createElement('section');section.className='ei-pack-panel';section.innerHTML='<div class="final-panel-title"><div><small>Ready-made compositions</small><h2>Invitation packs</h2></div></div><div class="ei-pack-grid"></div>';pane.append(section);const grid=$('.ei-pack-grid',section);
function make(kind,content,opt,index){const id=`pack-${Date.now()}-${index}-${Math.random().toString(36).slice(2,5)}`;let type=kind;if(kind==='shape')type='shape';if(typeof createObject!=='function')return null;const obj=createObject(id,type);if(type==='text'||type==='decoration'){obj.querySelector('.content').textContent=content;obj.dataset.font=opt.font||'Georgia,serif';obj.dataset.fontSize=String(opt.fontSize||32);obj.dataset.color=opt.color||'#7b4555';obj.dataset.fontWeight=opt.fontWeight||'400';obj.dataset.letterSpacing=String(opt.letterSpacing||0)}else{obj.dataset.shapeKind=content;obj.dataset.fillColor=opt.fillColor||'#d9a6ad';obj.dataset.borderRadius=String(opt.borderRadius||0)}obj.style.left=`${opt.left||10}%`;obj.style.top=`${opt.top||10}%`;obj.style.width=`${opt.width||50}%`;obj.style.height=type==='shape'?`${opt.height||12}%`:`${opt.height||12}%`;obj.dataset.rotation=String(opt.rotation||0);obj.style.zIndex=String((typeof nextZIndex==='function'?nextZIndex():10)+index);applyObjectVisualStyle(obj);return obj}
packs.forEach(pack=>{const b=document.createElement('button');b.type='button';b.className='ei-pack-card';b.innerHTML=`<div class="preview">${pack.preview}</div><strong>${pack.name}</strong><small>${pack.desc}</small>`;b.onclick=()=>{try{capture()}catch{}const created=pack.items.map((it,i)=>make(it[0],it[1],it[2],i)).filter(Boolean);created.forEach(x=>$('#stage').append(x));try{clearSelection();setSelection(created);save()}catch{}window.uiToast?.(`${pack.name} added`,'✦')};grid.append(b)});
})();
