const $=s=>document.querySelector(s),accountKey='sovan-account-v1',invitesKey='sovan-multi-invites-v1',tokenKey='sovan-auth-token';
const seed=[{id:'demo-wedding',title:'Sophea & Dara',type:'Wedding',status:'Published',views:128,rsvps:34,updatedAt:new Date().toISOString()}];
let account=JSON.parse(localStorage.getItem(accountKey)||'null'),invites=JSON.parse(localStorage.getItem(invitesKey)||'null')||seed,server=false;
async function request(path,options={}){let token=localStorage.getItem(tokenKey),r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});let data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
async function detect(){try{await request('/api/health');server=true;let me=await request('/api/auth/me');account=me.user;if(account)await loadServerInvites()}catch{server=false}show()}
async function loadServerInvites(){invites=(await request('/api/invitations')).map(i=>({...i,type:'Wedding',views:0}))}
function show(){let signed=!!account;$('#loginView').hidden=signed;$('#dashboardView').hidden=!signed;$('#logoutBtn').hidden=!signed;$('#accountName').textContent=signed?`${account.email}${server?' · Server':' · Local demo'}`:'';if(signed)render()}
function render(){$('#inviteGrid').innerHTML=invites.map(i=>`<article class="invite-card"><div class="invite-cover">${escapeHtml(i.type||'Invitation')}</div><div class="invite-body"><h2>${escapeHtml(i.title)}</h2><span>${escapeHtml(i.status)}</span><div class="stats"><span>${i.views||0} views</span><span>${i.rsvps||0} RSVPs</span></div><div class="actions"><button data-edit="${i.id}" class="primary">Edit</button><button data-copy="${i.id}">Duplicate</button></div></div></article>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>duplicate(b.dataset.copy))}
function openEditor(id){localStorage.setItem('sovan-active-invite',id);location.href='index.html'}
function localSave(){localStorage.setItem(invitesKey,JSON.stringify(invites));render()}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#loginBtn').onclick=async()=>{let email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<8)return alert('Enter a valid email and a password of at least 8 characters.');if(server){try{let result;try{result=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})})}catch(e){if(!confirm(`${e.message}. Create this account instead?`))return;result=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email,password})})}localStorage.setItem(tokenKey,result.token);account=result.user;await loadServerInvites()}catch(e){return alert(e.message)}}else{account={id:crypto.randomUUID(),email};localStorage.setItem(accountKey,JSON.stringify(account))}show()};
$('#logoutBtn').onclick=async()=>{if(server)try{await request('/api/auth/logout',{method:'POST'})}catch{}localStorage.removeItem(tokenKey);localStorage.removeItem(accountKey);account=null;show()};
$('#newBtn').onclick=async()=>{let title=prompt('Invitation name','New Wedding Invitation');if(!title)return;if(server){try{let document={fields:{names:title,date:'2026-12-27',venue:'Your venue',message:'We warmly invite you to celebrate with us.'},accent:'#9d4555',objects:{}};let item=await request('/api/invitations',{method:'POST',body:JSON.stringify({slug:title,document})});await loadServerInvites();openEditor(item.id)}catch(e){alert(e.message)}}else{let item={id:crypto.randomUUID(),title,type:'Wedding',status:'Draft',views:0,rsvps:0,updatedAt:new Date().toISOString()};invites.push(item);localSave();openEditor(item.id)}};
async function duplicate(id){let src=invites.find(i=>i.id===id);if(server){let item=await request('/api/invitations',{method:'POST',body:JSON.stringify({slug:src.title+' copy',document:{fields:{names:src.title+' Copy',date:'2026-12-27',venue:'Your venue',message:'We warmly invite you.'},accent:'#9d4555',objects:{}}})});await loadServerInvites();render();return item}invites.push({...src,id:crypto.randomUUID(),title:src.title+' Copy',status:'Draft',views:0,rsvps:0});localSave()}
detect();
