const $=s=>document.querySelector(s),accountKey='sovan-account-v1',invitesKey='sovan-multi-invites-v1',tokenKey='sovan-auth-token';
const seed=[{id:'demo-wedding',title:'Sophea & Dara',type:'Wedding',status:'Published',views:128,rsvps:34,updatedAt:new Date().toISOString()}];
let account=JSON.parse(localStorage.getItem(accountKey)||'null'),invites=JSON.parse(localStorage.getItem(invitesKey)||'null')||seed,server=false;
async function request(path,options={}){let token=localStorage.getItem(tokenKey),r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});let data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
async function detect(){try{await request('/api/health');server=true;try{let me=await request('/api/auth/me');account=me.user;if(account)await loadServerInvites()}catch{account=null}}catch{server=false}show()}
async function loadServerInvites(){invites=(await request('/api/invitations')).map(i=>({...i,type:i.type||'Invitation'}))}
function show(){let signed=!!account;$('#loginView').hidden=signed;$('#dashboardView').hidden=!signed;$('#logoutBtn').hidden=!signed;$('#accountName').textContent=signed?`${account.email}${server?' · Server':' · Local demo'}`:'';if(signed)render()}
function render(){$('#inviteGrid').innerHTML=invites.map(i=>`<article class="invite-card" style="opacity:${i.archived?.72:1}"><div class="invite-cover">${escapeHtml(i.type||'Invitation')}</div><div class="invite-body"><h2>${escapeHtml(i.title)}</h2><span>${escapeHtml(i.status)}</span><div class="stats"><span>${i.views||0} views</span><span>${i.rsvps||0} RSVPs</span></div><div class="actions"><button data-edit="${i.id}" class="primary" ${i.archived?'disabled':''}>Edit</button><button data-guests="${i.id}">Guests</button><button data-copy="${i.id}">Duplicate</button><button data-archive="${i.id}">${i.archived?'Restore':'Archive'}</button><button data-delete="${i.id}" class="danger">Delete</button></div></div></article>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));document.querySelectorAll('[data-guests]').forEach(b=>b.onclick=()=>{localStorage.setItem('sovan-active-invite',b.dataset.guests);location.href='guests.html'});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>duplicate(b.dataset.copy));document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archiveInvite(b.dataset.archive));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteInvite(b.dataset.delete))}
function openEditor(id){localStorage.setItem('sovan-active-invite',id);location.href='index.html'}
function localSave(){localStorage.setItem(invitesKey,JSON.stringify(invites));render()}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#loginBtn').onclick=async()=>{let email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<8)return alert('Enter a valid email and a password of at least 8 characters.');if(server){try{let result;try{result=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})})}catch(e){if(!confirm(`${e.message}. Create this account instead?`))return;result=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email,password})})}localStorage.setItem(tokenKey,result.token);account=result.user;await loadServerInvites()}catch(e){return alert(e.message)}}else{account={id:crypto.randomUUID(),email};localStorage.setItem(accountKey,JSON.stringify(account))}show()};
$('#logoutBtn').onclick=async()=>{if(server)try{await request('/api/auth/logout',{method:'POST'})}catch{}localStorage.removeItem(tokenKey);localStorage.removeItem(accountKey);account=null;show()};
function starterDocument(title,type){let presets={Wedding:{message:'Together with our families, we warmly invite you to celebrate our wedding.',venue:'Your wedding venue',theme:'rose',accent:'#9d4555',schedule:[{time:'4:00 PM',title:'Guest arrival'},{time:'5:00 PM',title:'Wedding ceremony'},{time:'6:30 PM',title:'Dinner reception'}]},Birthday:{message:'Join us for a joyful birthday celebration!',venue:'Party venue',theme:'gold',accent:'#a87616',schedule:[{time:'4:00 PM',title:'Guest arrival'},{time:'5:00 PM',title:'Cake and celebration'}]},Business:{message:'You are warmly invited to join us for this special business event.',venue:'Event venue',theme:'midnight',accent:'#8065c7',schedule:[{time:'8:30 AM',title:'Registration'},{time:'9:00 AM',title:'Opening program'},{time:'12:00 PM',title:'Networking lunch'}]}},p=presets[type]||presets.Wedding;return{eventType:type,fields:{names:title,date:'2026-12-27',time:'16:00',venue:p.venue,message:p.message},settings:{rsvpEnabled:true,scheduleEnabled:true,venueEnabled:true,galleryEnabled:true,countdownEnabled:true,musicEnabled:false,openingEnabled:true},dateFormat:'both',khmerDate:'',countdownTitle:'Counting down to our celebration',theme:p.theme,openingStyle:'soft',sectionOrder:['gallery','countdown','schedule','venue','rsvp'],schedule:p.schedule,venues:[],music:null,mapUrl:'',accent:p.accent,objects:{}}}
$('#newBtn').onclick=()=>{$('#newTitle').value='';$('#newType').value='Wedding';$('#createDialog').showModal();$('#newTitle').focus()};$('#cancelCreate').onclick=()=>$('#createDialog').close();$('#createForm').onsubmit=async e=>{e.preventDefault();let title=$('#newTitle').value.trim(),type=$('#newType').value;if(!title)return;let document=starterDocument(title,type),button=$('#confirmCreate');button.disabled=true;button.textContent='Creating…';try{if(server){let item=await request('/api/invitations',{method:'POST',body:JSON.stringify({slug:title,document})});await loadServerInvites();openEditor(item.id)}else{let item={id:crypto.randomUUID(),title,type,status:'Draft',views:0,rsvps:0,updatedAt:new Date().toISOString()};invites.push(item);localStorage.setItem(`sovan-invite-draft-v3:${item.id}`,JSON.stringify(document));localSave();openEditor(item.id)}}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent='Create and edit'}};
function copyDocument(document,title){let copy=structuredClone(document||{});copy.fields={...(copy.fields||{}),names:title};delete copy.id;delete copy.version;delete copy.publishedAt;return copy}
async function duplicate(id){let src=invites.find(i=>i.id===id);if(!src)return;let title=src.title+' Copy';if(server){try{let source=await request('/api/invitations/'+encodeURIComponent(id)),document=copyDocument(source.document,title),item=await request('/api/invitations',{method:'POST',body:JSON.stringify({slug:title,document})});await loadServerInvites();render();return item}catch(error){return alert(`The invitation could not be duplicated: ${error.message}`)}}let sourceKey=`sovan-invite-draft-v3:${id}`,sourceDocument=JSON.parse(localStorage.getItem(sourceKey)||'null')||starterDocument(src.title,src.type||'Wedding'),item={...src,id:crypto.randomUUID(),title,status:'Draft',views:0,rsvps:0,archived:false,updatedAt:new Date().toISOString()};localStorage.setItem(`sovan-invite-draft-v3:${item.id}`,JSON.stringify(copyDocument(sourceDocument,title)));invites.push(item);localSave()}
async function archiveInvite(id){let item=invites.find(i=>i.id===id),archived=!item.archived;if(server){await request(`/api/invitations/${id}/archive`,{method:'PUT',body:JSON.stringify({archived})});await loadServerInvites();render()}else{Object.assign(item,{archived,status:archived?'Archived':'Draft'});localSave()}}
async function deleteInvite(id){let item=invites.find(i=>i.id===id);if(!confirm(`Permanently delete “${item.title}”? This cannot be undone.`))return;if(server){await request(`/api/invitations/${id}`,{method:'DELETE'});await loadServerInvites();render()}else{invites=invites.filter(i=>i.id!==id);localSave()}}
detect();
