(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const stage=$('#stage'),viewport=$('#canvasViewport'),toolbar=$('.toolbar');if(!stage||!viewport||!toolbar)return;
const selected=()=>$$('.object.selected,.object.multi-selected').filter(x=>x.isConnected);
const primary=()=>selected()[0]||null;
const applyInput=(id,value,event='input')=>{const el=$('#'+id);if(!el)return;if(value!==undefined)el.value=value;el.dispatchEvent(new Event(event,{bubbles:true}))};
const click=id=>$('#'+id)?.click();
const saveNow=()=>{try{typeof save==='function'&&save()}catch{}};
const choose=(items)=>{try{typeof clearSelection==='function'&&clearSelection();typeof setSelection==='function'&&setSelection(items)}catch{}};
const makeId=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const currentZoom=()=>Number($('#zoomLevel')?.value||1);

// ------------------------------------------------------------------
// Persistent tool modes
// ------------------------------------------------------------------
const toolDefs=[['select','V','↖','Select / Move'],['text','T','T','Text'],['frame','F','▣','Photo frame'],['rect','R','□','Rectangle'],['ellipse','O','○','Ellipse'],['line','L','╱','Line'],['hand','H','✋','Hand / Pan'],['zoom','Z','⌕','Zoom']];
const rail=document.createElement('nav');rail.className='ei-tool-rail';rail.setAttribute('aria-label','Design tools');
toolDefs.forEach(([id,key,icon,label],i)=>{if(i===6){const sep=document.createElement('div');sep.className='sep';rail.append(sep)}const b=document.createElement('button');b.type='button';b.dataset.tool=id;b.title=`${label} (${key})`;b.setAttribute('aria-label',label);b.innerHTML=`${icon}<span>${key}</span>`;rail.append(b)});viewport.prepend(rail);
let activeTool=localStorage.getItem('einvite-active-tool')||'select';
function setTool(tool,{announce=true}={}){if(!toolDefs.some(x=>x[0]===tool))tool='select';activeTool=tool;localStorage.setItem('einvite-active-tool',tool);document.body.dataset.activeTool=tool;$$('[data-tool]',rail).forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));viewport.classList.toggle('ei-tool-crosshair',['text','frame','rect','ellipse','line'].includes(tool));viewport.classList.toggle('ei-tool-zoom',tool==='zoom');viewport.classList.toggle('ei-tool-hand',tool==='hand');if(tool==='hand'&&$('#panToggle')?.getAttribute('aria-pressed')!=='true')$('#panToggle')?.click();if(tool!=='hand'&&$('#panToggle')?.getAttribute('aria-pressed')==='true')$('#panToggle')?.click();if(announce&&window.uiToast)uiToast(`${toolDefs.find(x=>x[0]===tool)?.[3]||tool} tool`,'⌘')}
rail.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)setTool(b.dataset.tool)});setTool(activeTool,{announce:false});
function canvasPoint(e){const r=stage.getBoundingClientRect();return{x:Math.max(0,Math.min(98,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(98,(e.clientY-r.top)/r.height*100))}}
function createTextAt(point){if(typeof createObject!=='function')return;const o=createObject(makeId('text'),'text');o.style.left=`${Math.min(72,point.x)}%`;o.style.top=`${Math.min(90,point.y)}%`;o.style.width='40%';o.style.height='90px';o.dataset.fontSize='32';o.dataset.layerName='Text';o.querySelector('.content').textContent='Type your text';stage.append(o);choose([o]);saveNow();setTimeout(()=>{const c=o.querySelector('.content');c.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));},50)}
function createShapeAt(kind,point){if(typeof createObject!=='function')return;const o=createObject(makeId(kind), 'shape');o.dataset.shapeKind=kind==='ellipse'?'circle':kind;o.dataset.layerName=kind==='ellipse'?'Ellipse':kind[0].toUpperCase()+kind.slice(1);o.dataset.fillColor=$('#accent')?.value||'#9d4555';if(kind==='line'){o.style.width='34%';o.style.height='8px'}else{o.style.width='28%';o.style.height=kind==='ellipse'?'150px':'130px'}o.style.left=`${Math.min(80,point.x)}%`;o.style.top=`${Math.min(90,point.y)}%`;if(kind==='ellipse')o.dataset.borderRadius='120';stage.append(o);try{applyObjectVisualStyle(o)}catch{}choose([o]);saveNow()}
const frameSvg=`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#eceef5"/><stop offset="1" stop-color="#d7dae5"/></linearGradient></defs><rect width="800" height="600" rx="30" fill="url(#g)"/><path d="M210 390l120-125 90 92 70-67 110 100" fill="none" stroke="#9499a9" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/><circle cx="560" cy="180" r="55" fill="#b9bdca"/></svg>`)}`;
function createFrameAt(point){if(typeof createObject!=='function')return;const o=createObject(makeId('frame'),'image');o.style.left=`${Math.min(70,point.x)}%`;o.style.top=`${Math.min(82,point.y)}%`;o.style.width='42%';o.style.height='260px';o.dataset.layerName='Photo frame';o.dataset.showInGallery='false';o.dataset.originalSrc='';o.dataset.framePlaceholder='true';o.classList.add('ei-frame-placeholder');const img=o.querySelector('img');img.src=frameSvg;img.alt='Empty photo frame';stage.append(o);choose([o]);saveNow()}
stage.addEventListener('pointerdown',e=>{if(activeTool==='select'||activeTool==='hand')return;if(e.target.closest('.object,.selection-bounds,.safe-margin-overlay'))return;if(e.button!==0)return;if(activeTool==='zoom'){e.preventDefault();const zoom=currentZoom();applyInput('zoomLevel',Math.min(2,zoom+.25),'change');return}const point=canvasPoint(e);e.preventDefault();e.stopImmediatePropagation();if(activeTool==='text')createTextAt(point);else if(activeTool==='frame')createFrameAt(point);else if(activeTool==='rect')createShapeAt('rectangle',point);else if(activeTool==='ellipse')createShapeAt('ellipse',point);else if(activeTool==='line')createShapeAt('line',point)},true);
stage.addEventListener('dblclick',e=>{const frame=e.target.closest('.ei-frame-placeholder');if(!frame)return;if(typeof openMaterialPicker!=='function')return;openMaterialPicker('Choose photo for frame',(url,asset)=>{frame.classList.remove('ei-frame-placeholder');frame.dataset.framePlaceholder='false';frame.dataset.originalSrc=frame.querySelector('img')?.src||'';frame.dataset.src=url;const img=frame.querySelector('img');if(img){img.src=url;img.alt=asset?.name||'Invitation photo'}saveNow()})},true);
// Capture shortcuts before legacy listeners so they behave as persistent tools instead of immediate insert actions.
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable;if(typing||e.ctrlKey||e.metaKey||e.altKey)return;const map={v:'select',t:'text',f:'frame',r:'rect',o:'ellipse',l:'line',h:'hand',z:'zoom'};const tool=map[e.key.toLowerCase()];if(tool){e.preventDefault();e.stopImmediatePropagation();setTool(tool)}},true);

// ------------------------------------------------------------------
// Contextual top toolbar
// ------------------------------------------------------------------
const context=document.createElement('div');context.className='ei-context-toolbar';toolbar.insertBefore(context,$('#activeCanvasLabel'));
const divider=()=>'<span class="divider"></span>';
function valueOf(id,fallback=''){return $('#'+id)?.value??fallback}
function selectOptions(id){return $('#'+id)?.innerHTML||''}
function renderContext(){const items=selected(),o=items[0];context.innerHTML='';if(!items.length){context.classList.add('visible');context.innerHTML=`<span class="ei-context-name">No selection</span>${divider()}<button type="button" data-action="design">Design</button><button type="button" data-action="page-motion">Animate page</button><button type="button" data-action="check">Design check</button>`;wireContext();return}context.classList.add('visible');const type=o.dataset.objectType||'text',name=o.dataset.layerName||o.querySelector('.content')?.textContent?.trim()?.slice(0,30)||type;let html=`<span class="ei-context-name" title="${name.replace(/"/g,'&quot;')}">${items.length>1?`${items.length} selected`:name}</span>${divider()}`;
 if(items.length>1){html+=`<div class="group"><button data-action="group">Group</button><button data-action="ungroup">Ungroup</button><button data-action="align">Align</button><button data-action="tidy">Tidy</button></div>`}
 else if(type==='text'||type==='decoration'){html+=`<div class="group"><select data-ctx="font" title="Font">${selectOptions('font')}</select><input data-ctx="fontSize" type="number" min="8" max="200" value="${o.dataset.fontSize||32}" title="Font size"><input data-ctx="color" type="color" value="${o.dataset.color||'#342c26'}" title="Text color"><button class="icon-button ${o.dataset.fontWeight==='700'?'active':''}" data-action="bold"><b>B</b></button><button class="icon-button ${o.dataset.fontStyle==='italic'?'active':''}" data-action="italic"><i>I</i></button><button class="icon-button" data-action="alignText" title="Text alignment">≡</button></div>${divider()}<div class="group"><button data-action="editText">Edit text</button><button data-action="effects">Effects</button><button data-action="animate">Animate</button></div>`}
 else if(type==='image'){html+=`<div class="group"><button data-action="replace">Replace</button><button data-action="removeBg">Remove BG</button><button data-action="crop">Crop</button><button class="icon-button" data-action="flipX">↔</button><button class="icon-button" data-action="flipY">↕</button></div>${divider()}<div class="group"><button data-action="position">Position</button><button data-action="animate">Animate</button></div>`}
 else if(type==='shape'){html+=`<div class="group"><input data-ctx="fill" type="color" value="${o.dataset.fillColor||'#9d4555'}" title="Fill"><input data-ctx="border" type="color" value="${o.dataset.borderColor||'#ffffff'}" title="Border"><button data-action="position">Position</button><button data-action="animate">Animate</button></div>`}
 context.innerHTML=html;const font=context.querySelector('[data-ctx=font]');if(font)font.value=o.dataset.font||valueOf('font');wireContext()}
function openInspector(target){document.querySelector('[data-inspector-tab="object"]')?.click();setTimeout(()=>$(target)?.scrollIntoView({behavior:'smooth',block:'nearest'}),60)}
function wireContext(){context.querySelector('[data-ctx=font]')?.addEventListener('change',e=>applyInput('font',e.target.value,'change'));context.querySelector('[data-ctx=fontSize]')?.addEventListener('change',e=>applyInput('fontSize',e.target.value));context.querySelector('[data-ctx=color]')?.addEventListener('input',e=>applyInput('color',e.target.value));context.querySelector('[data-ctx=fill]')?.addEventListener('input',e=>applyInput('fillColor',e.target.value));context.querySelector('[data-ctx=border]')?.addEventListener('input',e=>applyInput('borderColor',e.target.value));context.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action,o=primary();if(a==='bold')click('fontBold');if(a==='italic')click('fontItalic');if(a==='alignText'){const modes=['left','center','right'],next=modes[(modes.indexOf(o?.dataset.textAlign||'center')+1)%modes.length];applyInput('textAlign',next,'change')}if(a==='editText')o?.querySelector('.content')?.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));if(a==='effects')openInspector('#finalTextTransform');if(a==='animate')openInspector('#animation');if(a==='crop')openInspector('#cropPreview');if(a==='replace')click('aiReplaceImage');if(a==='removeBg')click('aiBgCut');if(a==='flipX')click('aiFlipX');if(a==='flipY')click('aiFlipY');if(a==='position')openInspector('#canvasPlusTransform');if(a==='group')click('groupObjects');if(a==='ungroup')click('ungroupObjects');if(a==='tidy')click('studioTidy');if(a==='align')openInspector('.alignment-grid');if(a==='design')document.querySelector('[data-inspector-tab="design"]')?.click();if(a==='page-motion')openInspector('#sectionAnimationsManager');if(a==='check')click('studioDesignCheck')})}
const selectionObserver=new MutationObserver(()=>renderContext());selectionObserver.observe(stage,{subtree:true,attributes:true,attributeFilter:['class','data-font-size','data-color','data-fill-color','data-font-weight','data-font-style']});document.addEventListener('pointerup',()=>setTimeout(renderContext,0),true);renderContext();

// ------------------------------------------------------------------
// Inline rich-text mini toolbar
// ------------------------------------------------------------------
const rich=document.createElement('div');rich.className='ei-rich-toolbar';rich.innerHTML=`<button type="button" data-cmd="bold"><b>B</b></button><button type="button" data-cmd="italic"><i>I</i></button><button type="button" data-cmd="underline"><u>U</u></button><span class="sep"></span><button type="button" data-cmd="insertUnorderedList">• List</button><button type="button" data-cmd="insertOrderedList">1.</button><span class="sep"></span><button type="button" data-cmd="justifyLeft">⇤</button><button type="button" data-cmd="justifyCenter">↔</button><button type="button" data-cmd="justifyRight">⇥</button>`;document.body.append(rich);
let editing=null;
function positionRich(){if(!editing||!editing.isConnected){rich.classList.remove('visible');return}const r=editing.closest('.object').getBoundingClientRect(),w=rich.offsetWidth||280;rich.style.left=`${Math.max(10,Math.min(innerWidth-w-10,r.left+r.width/2-w/2))}px`;rich.style.top=`${Math.max(70,r.top-48)}px`;rich.classList.add('visible')}
stage.addEventListener('dblclick',e=>{const c=e.target.closest('.text-object .content,.decoration-object .content');if(!c)return;editing=c;setTimeout(positionRich,20)},true);rich.addEventListener('mousedown',e=>e.preventDefault());rich.addEventListener('click',e=>{const b=e.target.closest('[data-cmd]');if(!b||!editing)return;editing.focus();document.execCommand(b.dataset.cmd,false,null);saveNow();positionRich()});document.addEventListener('focusout',e=>{if(editing&&e.target===editing)setTimeout(()=>{if(!rich.matches(':hover')){editing=null;rich.classList.remove('visible')}},120)},true);addEventListener('resize',positionRich);addEventListener('scroll',positionRich,true);
})();
