(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];if(!$('#font')||!$('#stage'))return;
const fonts=[
 ['Inter','Inter,ui-sans-serif,system-ui,sans-serif','Modern','Clean modern interface and body text'],['Segoe UI','"Segoe UI",Arial,sans-serif','Modern','Balanced modern sans'],['Arial','Arial,sans-serif','Modern','Universal sans serif'],['Helvetica','Helvetica,Arial,sans-serif','Modern','Classic Swiss sans'],['Trebuchet','"Trebuchet MS",sans-serif','Modern','Friendly humanist sans'],['Verdana','Verdana,sans-serif','Modern','Highly readable sans'],['Tahoma','Tahoma,sans-serif','Modern','Compact interface sans'],['Gill Sans','"Gill Sans",Calibri,sans-serif','Modern','Elegant humanist sans'],
 ['Georgia','Georgia,serif','Serif','Warm editorial serif'],['Times New Roman','"Times New Roman",serif','Serif','Traditional formal serif'],['Baskerville','Baskerville,Georgia,serif','Serif','Refined classical serif'],['Garamond','Garamond,"Times New Roman",serif','Serif','Old-style romantic serif'],['Palatino','Palatino,"Palatino Linotype",serif','Serif','Elegant book serif'],['Didot','Didot,"Bodoni 72",serif','Display','High-fashion editorial'],['Bodoni','"Bodoni 72","Bodoni MT",Didot,serif','Display','Luxury contrast serif'],['Copperplate','Copperplate,"Copperplate Gothic Light",serif','Display','Formal engraved style'],['Optima','Optima,Candara,sans-serif','Display','Elegant flared sans'],
 ['Khmer Sans','"Noto Sans Khmer","Khmer OS Battambang",sans-serif','Khmer','Clean Khmer body text'],['Khmer Serif','"Noto Serif Khmer","Khmer OS Battambang",serif','Khmer','Formal Khmer serif'],['Khmer Ceremonial','"Khmer OS Muol Light","Noto Serif Khmer",serif','Khmer','Ceremonial Khmer titles'],['Khmer Muol','"Khmer OS Muol","Khmer OS Muol Light",serif','Khmer','Traditional Khmer display'],['Khmer Battambang','"Khmer OS Battambang","Noto Sans Khmer",sans-serif','Khmer','Readable Khmer text'],['Khmer Siemreap','"Khmer OS Siemreap","Noto Sans Khmer",sans-serif','Khmer','Soft Khmer sans'],['Khmer Bokor','"Khmer OS Bokor","Noto Serif Khmer",serif','Khmer','Decorative Khmer style'],['Khmer Freehand','"Khmer OS Freehand","Noto Sans Khmer",sans-serif','Khmer','Handwritten Khmer feel'],
 ['Brush Script','"Brush Script MT",cursive','Script','Classic flowing script'],['Segoe Script','"Segoe Script",cursive','Script','Modern handwriting'],['Snell Roundhand','"Snell Roundhand",cursive','Script','Elegant wedding script'],['Apple Chancery','"Apple Chancery",cursive','Script','Formal calligraphic script'],['Comic Sans','"Comic Sans MS",cursive','Playful','Casual playful lettering'],['Impact','Impact,sans-serif','Display','Bold condensed display'],['Rockwell','Rockwell,"Roboto Slab",serif','Display','Strong slab serif']
 ].map(([name,stack,category,description])=>({name,stack,category,description}));
const select=$('#font');fonts.forEach(font=>{if(![...select.options].some(o=>o.value===font.stack)){const option=document.createElement('option');option.value=font.stack;option.textContent=font.name;select.append(option)}});
const label=select.closest('label');const launch=document.createElement('button');launch.type='button';launch.className='ei-font-launch';launch.innerHTML='<span>Browse fonts</span><small>Search · favorites · Khmer</small>';label?.append(launch);
const dialog=document.createElement('dialog');dialog.className='ei-font-dialog';dialog.innerHTML=`<div class="ei-font-shell"><div class="ei-font-head"><h2>Font browser</h2><button type="button" data-close>×</button></div><div class="ei-font-search"><input type="search" placeholder="Search fonts…"><div class="ei-font-tabs"></div></div><div class="ei-font-grid"></div></div>`;document.body.append(dialog);
let category='All',query='',favorites=new Set(JSON.parse(localStorage.getItem('einvite-font-favorites-v1')||'[]')),recent=JSON.parse(localStorage.getItem('einvite-font-recent-v1')||'[]');const cats=['All','Favorites','Recent','Khmer','Serif','Modern','Display','Script','Playful'];
function render(){const tabs=$('.ei-font-tabs',dialog);tabs.innerHTML=cats.map(c=>`<button type="button" data-cat="${c}" class="${c===category?'active':''}">${c}</button>`).join('');$$('[data-cat]',tabs).forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()});const grid=$('.ei-font-grid',dialog);grid.innerHTML='';let list=fonts.filter(f=>{if(category==='Favorites'&&!favorites.has(f.stack))return false;if(category==='Recent'&&!recent.includes(f.stack))return false;if(!['All','Favorites','Recent'].includes(category)&&f.category!==category)return false;return!query||`${f.name} ${f.category} ${f.description}`.toLowerCase().includes(query)});if(category==='Recent')list.sort((a,b)=>recent.indexOf(a.stack)-recent.indexOf(b.stack));if(!list.length){grid.innerHTML='<div class="ei-font-empty">No fonts match this view.</div>';return}list.forEach(f=>{const card=document.createElement('article');card.className=`ei-font-card${select.value===f.stack?' active':''}`;card.innerHTML=`<button type="button" class="ei-font-fav ${favorites.has(f.stack)?'active':''}">★</button><div class="preview"></div><strong></strong><small></small>`;$('.preview',card).textContent=f.category==='Khmer'?'សិរីមង្គលអាពាហ៍ពិពាហ៍':'Beautiful moments';$('.preview',card).style.fontFamily=f.stack;$('strong',card).textContent=f.name;$('small',card).textContent=`${f.category} · ${f.description}`;card.onclick=e=>{if(e.target.closest('.ei-font-fav'))return;select.value=f.stack;select.dispatchEvent(new Event('change',{bubbles:true}));recent=[f.stack,...recent.filter(x=>x!==f.stack)].slice(0,12);localStorage.setItem('einvite-font-recent-v1',JSON.stringify(recent));dialog.close()};$('.ei-font-fav',card).onclick=e=>{e.stopPropagation();favorites.has(f.stack)?favorites.delete(f.stack):favorites.add(f.stack);localStorage.setItem('einvite-font-favorites-v1',JSON.stringify([...favorites]));render()};grid.append(card)})}
launch.onclick=()=>{render();dialog.showModal();setTimeout(()=>$('.ei-font-search input',dialog)?.focus(),0)};dialog.querySelector('[data-close]').onclick=()=>dialog.close();$('.ei-font-search input',dialog).oninput=e=>{query=e.target.value.trim().toLowerCase();render()};
})();
