(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
if(!$('#font')||!$('#stage')||!window.EInviteTypography)return;
const select=$('#font'),bridge=()=>window.EInviteEditorBridge,custom=()=>window.EInviteCustomFonts;
const storageGet=(key,fallback='')=>{try{return localStorage.getItem(key)??fallback}catch{return fallback}},storageSet=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};
const label=select.closest('label');let launch=$('.ei-font-launch[data-font-loader]',label)||$('.ei-font-launch',label);if(!launch){launch=document.createElement('button');launch.type='button';launch.className='ei-font-launch';launch.innerHTML='<span>Browse fonts</span><small>Bundled + uploaded TTF/OTF</small>';label?.append(launch)}launch.removeAttribute('data-font-loading');launch.disabled=false;
const dialog=document.createElement('dialog');dialog.className='ei-font-dialog';dialog.innerHTML='<div class="ei-font-shell"><div class="ei-font-head"><h2>Font browser</h2><label class="ei-font-upload"><span>Upload font</span><input type="file" accept=".ttf,.tff,.otf,.woff2,font/ttf,font/otf,font/woff2"></label><button type="button" data-close aria-label="Close font browser">×</button></div><div class="ei-font-search"><input type="search" placeholder="Search fonts…"><div class="ei-font-tabs"></div><label class="ei-font-license"><input type="checkbox"><span>I confirm that I have permission to use and publish the uploaded font.</span></label></div><p class="ei-font-upload-status" role="status" aria-live="polite"></p><div class="ei-font-grid"></div></div>';document.body.append(dialog);
let category='All',query='',favorites=new Set(JSON.parse(storageGet('einvite-font-favorites-v3','[]'))),recent=JSON.parse(storageGet('einvite-font-recent-v3','[]'));
const fileInput=$('.ei-font-upload input',dialog),license=$('.ei-font-license input',dialog),status=$('.ei-font-upload-status',dialog);
function documentFonts(){const doc=bridge()?.getState?.()||{};return new Set(Object.keys(doc.customFonts||{}))}
function quality(font){if(!font.custom)return{label:'',tone:'',description:font.bundled?'Bundled for offline invitations':'Trusted system choice with bundled fallback'};if(font.khmerReady)return{label:'Khmer ready',tone:'ready',description:`Khmer shaping verified${Number(font.khmerCoreCoveragePercent)>0?` · ${Math.round(font.khmerCoreCoveragePercent)}% core coverage`:''}`};if((font.scripts||[]).includes('Khmer'))return{label:'Khmer partial',tone:'warning',description:'Incomplete Khmer coverage; trusted Noto Khmer fallback will be used'};return{label:'Latin only',tone:'neutral',description:'Optimized custom font with trusted Khmer fallback'}}
function fontList(){
 const registry=window.EInviteFontRegistry?.data?.fonts||{},allowedCustom=documentFonts();return Object.entries(registry).filter(([id,f])=>!f.custom||allowedCustom.has(id)).map(([id,f])=>{const q=quality(f);return{id,name:f.label,stack:f.stack,category:f.custom?'Custom':/khmer/i.test(id)||f.scripts?.includes('Khmer')&&!f.scripts?.includes('Latin')?'Khmer':f.category==='serif'?'Serif':'Modern',description:q.description,qualityLabel:q.label,qualityTone:q.tone,custom:!!f.custom,scripts:f.scripts||[],khmerReady:f.khmerReady===true,khmerCoreCoveragePercent:Number(f.khmerCoreCoveragePercent)||0,recommendedLineHeight:Number(f.recommendedLineHeight)||0}})
}
function syncSelect(){const current=select.value,fonts=fontList();select.replaceChildren(...fonts.map(f=>{const option=document.createElement('option');option.value=f.id;option.textContent=f.name;return option}));select.value=fonts.some(f=>f.id===current)?current:(fonts[0]?.id||'noto-serif')}
function announce(message,tone=''){status.textContent=message;status.dataset.tone=tone}
function catsFor(fonts){const base=['All','Favorites','Recent','Custom','Khmer','Serif','Modern'];return base.filter(c=>!['Custom','Khmer'].includes(c)||fonts.some(f=>f.category===c))}
function replaceRemovedFont(doc,id){const pairing=`custom-pair-${id}`,fallback='serif-formal';for(const style of Object.values(doc.typography?.styles||{}))if(style?.fontPairing===pairing)style.fontPairing=fallback;const visit=map=>Object.values(map||{}).forEach(o=>{if(!o||typeof o!=='object')return;if(o.font===id)o.font='noto-serif';if(o.fontPairing===pairing)o.fontPairing=fallback;if(o.typographyOverrides?.fontPairing===pairing)o.typographyOverrides.fontPairing=fallback});visit(doc.objects);for(const page of doc.designPages||[])visit(page.objects)}
async function removeCustomFont(font){if(!font.custom)return;const ok=await(window.uiConfirm?.(`Remove “${font.name}” from this invitation? Text using it will return to the Formal Serif pairing.`,{title:'Remove custom font',danger:true,confirmText:'Remove'})??Promise.resolve(confirm(`Remove ${font.name}?`)));if(!ok)return;bridge()?.transact?.('Remove custom font',doc=>{replaceRemovedFont(doc,font.id);custom()?.removeFromDocument(doc,font.id)});favorites.delete(font.id);recent=recent.filter(id=>id!==font.id);storageSet('einvite-font-favorites-v3',JSON.stringify([...favorites]));storageSet('einvite-font-recent-v3',JSON.stringify(recent));syncSelect();render();announce('Custom font removed from this invitation.','success')}
function render(){
 const fonts=fontList(),cats=catsFor(fonts);if(!cats.includes(category))category='All';const tabs=$('.ei-font-tabs',dialog);tabs.replaceChildren(...cats.map(c=>{const b=document.createElement('button');b.type='button';b.dataset.cat=c;b.classList.toggle('active',c===category);b.textContent=c;b.onclick=()=>{category=c;render()};return b}));const grid=$('.ei-font-grid',dialog);grid.replaceChildren();let list=fonts.filter(f=>{if(category==='Favorites'&&!favorites.has(f.id))return false;if(category==='Recent'&&!recent.includes(f.id))return false;if(!['All','Favorites','Recent'].includes(category)&&f.category!==category)return false;return!query||`${f.name} ${f.category} ${f.description} ${f.scripts.join(' ')}`.toLowerCase().includes(query)});if(category==='Recent')list.sort((a,b)=>recent.indexOf(a.id)-recent.indexOf(b.id));if(!list.length){const empty=document.createElement('div');empty.className='ei-font-empty';empty.textContent='No fonts match this view.';grid.append(empty);return}
 list.forEach(f=>{const card=document.createElement('article');card.className=`ei-font-card${select.value===f.id?' active':''}`;card.dataset.custom=String(f.custom);card.dataset.khmerReady=String(f.khmerReady);card.innerHTML='<button type="button" class="ei-font-fav" aria-label="Favorite font">★</button><div class="preview"></div><strong></strong><small></small>';if(f.custom){const remove=document.createElement('button');remove.type='button';remove.className='ei-font-remove';remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${f.name}`);remove.onclick=e=>{e.stopPropagation();removeCustomFont(f)};card.append(remove);const badge=document.createElement('span');badge.className='ei-font-badge';badge.dataset.tone=f.qualityTone||'neutral';badge.textContent=f.qualityLabel||'Uploaded';card.append(badge)}const fav=$('.ei-font-fav',card);fav.classList.toggle('active',favorites.has(f.id));const preview=$('.preview',card);preview.lang=f.scripts.includes('Khmer')?'km':'en';preview.textContent=f.scripts.includes('Khmer')?'សិរីមង្គលអាពាហ៍ពិពាហ៍ · កម្ពុជា ២០២៦':'Beautiful moments · សិរីមង្គល';preview.style.fontFamily=f.stack;if(f.recommendedLineHeight)preview.style.lineHeight=String(Math.max(1.2,f.recommendedLineHeight));$('strong',card).textContent=f.name;$('small',card).textContent=`${f.category} · ${f.description}`;card.onclick=e=>{if(e.target.closest('button'))return;select.value=f.id;select.dispatchEvent(new Event('change',{bubbles:true}));recent=[f.id,...recent.filter(x=>x!==f.id)].slice(0,12);storageSet('einvite-font-recent-v3',JSON.stringify(recent));dialog.close()};fav.onclick=e=>{e.stopPropagation();favorites.has(f.id)?favorites.delete(f.id):favorites.add(f.id);storageSet('einvite-font-favorites-v3',JSON.stringify([...favorites]));render()};grid.append(card)})
}
async function uploadFont(file){if(!file)return;if(!custom())return announce('Custom font runtime is unavailable.','error');fileInput.disabled=true;announce('Validating and optimizing font…');try{const invitationId=window.EInviteContext?.getInvitationId?.()||'';const entry=await custom().upload(file,{invitationId,licenseAcknowledged:license.checked,onProgress:info=>announce(info.phase==='processing'?'Optimizing font…':`Uploading font… ${info.percent||0}%`)});bridge()?.transact?.('Upload custom font',doc=>custom().addToDocument(doc,entry));await custom().loadEntry(entry);syncSelect();select.value=entry.id;window.EInviteEditorState?.applyTextProperty?.('font',entry.id);category='Custom';render();const khmer=entry.khmerReady?` Khmer shaping ready${entry.khmerCoreCoveragePercent?` (${Math.round(entry.khmerCoreCoveragePercent)}% core coverage)`:''}.`:entry.scripts?.includes('Khmer')?' Khmer support is incomplete, so Noto Khmer fallback remains active.':' Trusted Noto Khmer fallback remains active.';announce(entry.sourceType==='local'?`${entry.label} stored locally.${khmer} Connect the backend before publishing from another device.`:`${entry.label} uploaded as WOFF2${entry.savingsPercent?` · ${entry.savingsPercent}% smaller`:''}.${khmer}`,'success');license.checked=false}catch(error){announce(error.message||'The font could not be uploaded.','error')}finally{fileInput.value='';fileInput.disabled=false}}
fileInput.addEventListener('change',()=>uploadFont(fileInput.files?.[0]));launch.onclick=()=>{custom()?.installDocumentFonts(bridge()?.getState?.()||{});syncSelect();render();dialog.showModal();setTimeout(()=>$('.ei-font-search input',dialog)?.focus(),0)};dialog.querySelector('[data-close]').onclick=()=>dialog.close();$('.ei-font-search input',dialog).oninput=e=>{query=e.target.value.trim().toLowerCase();render()};document.addEventListener('einvite:custom-font-ready',()=>{syncSelect();render()});syncSelect();document.dispatchEvent(new CustomEvent('einvite:font-browser-ready',{detail:{launch}}));
})();
