#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
DATA=json.loads((ROOT/'typography-contract.json').read_text(encoding='utf-8'))
fonts=DATA['fonts']; default=DATA['defaultFontId']
js=f"""(()=>{{'use strict';
const DATA={json.dumps(DATA,ensure_ascii=False,separators=(',',':'))};
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const ids=Object.freeze(Object.keys(DATA.fonts)),pairingIds=Object.freeze(Object.keys(DATA.pairings)),MAX_TEXT_STYLES=DATA.maxTextStyles||64;
function finiteNumber(value,fallback,min,max){{if(typeof value==='boolean'||value===null||value===''||Array.isArray(value)||(typeof value==='object'&&value!==null))return fallback;const number=typeof value==='number'?value:Number(value);return Number.isFinite(number)?Math.max(min,Math.min(max,number)):fallback}}
function fontId(value,{{fallback=DATA.defaultFontId,strict=false}}={{}}){{const raw=typeof value==='string'?value.trim():'';if(own(DATA.fonts,raw))return raw;if(own(DATA.legacy,raw))return DATA.legacy[raw];if(strict)throw new TypeError('Unknown font ID');return fallback}}
function pairingId(value,{{fallback=DATA.defaultPairingId,strict=false}}={{}}){{const raw=typeof value==='string'?value.trim():'';if(own(DATA.pairings,raw))return raw;if(strict)throw new TypeError('Unknown font pairing ID');return fallback}}
function stack(value){{return DATA.fonts[fontId(value)].stack}}
function pairing(value){{const id=pairingId(value);return Object.freeze({{id,...DATA.pairings[id]}})}}
function pairedFont(value,locale='en'){{const p=pairing(value);return fontId(String(locale).toLowerCase().startsWith('km')?p.km:p.en)}}
function pairedStack(value,locale='en'){{return stack(pairedFont(value,locale))}}
function metadata(value){{const id=fontId(value);return Object.freeze({{id,...DATA.fonts[id]}})}}
function normalizeTypography(source={{}}){{const o={{...source}},fontSize=finiteNumber(o.fontSize,32,8,200),max=finiteNumber(o.textAutoFitMax,fontSize,8,200),min=Math.min(finiteNumber(o.textMinFontSize,10,8,72),max);o.font=fontId(o.font);o.fontPairing=pairingId(o.fontPairing||o.fontPairId);o.fontSize=fontSize;o.textAutoFit=o.textAutoFit==='fit'?'fit':'none';o.textAutoFitMax=max;o.textMinFontSize=min;o.textWrap=['normal','balance','pretty'].includes(o.textWrap)?o.textWrap:'normal';o.textColumns=Math.round(finiteNumber(o.textColumns,1,1,3));o.textColumnGap=finiteNumber(o.textColumnGap,24,0,64);o.textAlign=['left','center','right','justify'].includes(o.textAlign)?o.textAlign:'center';return o}}
function fitLargest({{min=8,max=200,fits,steps=16}}={{}}){{min=finiteNumber(min,8,8,200);max=finiteNumber(max,200,min,200);if(typeof fits!=='function')return min;let low=min,high=max,best=min;for(let i=0;i<steps;i++){{const candidate=(low+high)/2;if(fits(candidate)){{best=candidate;low=candidate}}else high=candidate}}return Math.max(min,Math.floor((best+1e-7)*10)/10)}}
async function ensureReady(idsToLoad=ids){{if(!document.fonts)return;const requests=[];for(const raw of idsToLoad){{const meta=DATA.fonts[fontId(raw)];if(!meta.bundled)continue;for(const weight of meta.weights||[400])requests.push(document.fonts.load(`${{weight}} 16px "${{meta.family}}"`))}}await Promise.allSettled(requests)}}
const registry=Object.freeze({{version:DATA.version,data:DATA,MAX_TEXT_STYLES,fontIds:ids,pairingIds,fontId,pairingId,stack,pairing,pairedFont,pairedStack,metadata,ensureReady}});
window.EInviteFontRegistry=registry;
window.EInviteTypography=Object.freeze({{version:DATA.version,data:DATA,MAX_TEXT_STYLES,fontIds:ids,pairingIds,finiteNumber,fontId,pairingId,stack,pairing,pairedFont,pairedStack,metadata,normalizeTypography,fitLargest,ensureReady}});
}})();
"""
(ROOT/'typography-contract.js').write_text(js,encoding='utf-8')
py=f'''# Generated by generate_typography_contract.py. Do not edit.\nfrom __future__ import annotations\nimport math\nDATA={repr(DATA)}\nFONT_REGISTRY=DATA["fonts"]\nFONT_PAIRINGS=DATA["pairings"]\nFONT_LEGACY=DATA["legacy"]\nDEFAULT_FONT_ID={default!r}\nDEFAULT_PAIRING_ID={DATA['defaultPairingId']!r}\nFONT_IDS=frozenset(FONT_REGISTRY)\nPAIRING_IDS=frozenset(FONT_PAIRINGS)\nCOLOR_TOKENS=frozenset(DATA["colorTokens"])
MAX_TEXT_STYLES=int(DATA.get("maxTextStyles",64))\ndef normalize_font_id(value, *, strict=True):\n    if not isinstance(value,str):\n        if strict: raise ValueError("Invalid font ID")\n        return DEFAULT_FONT_ID\n    raw=value.strip()\n    if raw in FONT_REGISTRY:return raw\n    if raw in FONT_LEGACY:return FONT_LEGACY[raw]\n    if strict:raise ValueError("Unknown font ID")\n    return DEFAULT_FONT_ID\ndef normalize_pairing_id(value, *, strict=True):\n    if not isinstance(value,str):\n        if strict:raise ValueError("Invalid font pairing ID")\n        return DEFAULT_PAIRING_ID\n    raw=value.strip()\n    if raw in FONT_PAIRINGS:return raw\n    if strict:raise ValueError("Unknown font pairing ID")\n    return DEFAULT_PAIRING_ID\ndef font_stack(value):return FONT_REGISTRY[normalize_font_id(value)]["stack"]\ndef paired_font(value, locale="en"):\n    item=FONT_PAIRINGS[normalize_pairing_id(value)]\n    return item["km" if str(locale).lower().startswith("km") else "en"]\ndef finite_number(value, fallback, minimum, maximum, *, integer=False, strict=False):\n    if isinstance(value,bool) or value is None or value=="" or isinstance(value,(list,dict,tuple,set)) or (strict and not isinstance(value,(int,float))):\n        if strict:raise ValueError("Invalid finite number")\n        return fallback\n    try:number=float(value)\n    except (TypeError,ValueError):\n        if strict:raise ValueError("Invalid finite number")\n        return fallback\n    if not math.isfinite(number):\n        if strict:raise ValueError("Invalid finite number")\n        return fallback\n    if strict and not minimum <= number <= maximum:raise ValueError("Finite number outside allowed range")\n    number=max(minimum,min(maximum,number))\n    return int(round(number)) if integer else number\n'''
(ROOT/'typography_contract.py').write_text(py,encoding='utf-8')
faces=[]
for font_id,meta in fonts.items():
    if not meta.get('bundled'):continue
    for weight,path in meta.get('assets',{}).items():
        
        unicode = 'unicode-range:U+1780-17FF,U+19E0-19FF;' if 'Khmer' in (meta.get('scripts') or []) else 'unicode-range:U+0000-024F,U+1E00-1EFF,U+2000-206F;'
        faces.append(f"@font-face{{font-family:'{meta['family']}';src:url('{path}') format('woff2');font-style:normal;font-weight:{weight};font-display:swap;{unicode}}}")
css="/* Generated trusted typography font faces. Bundled Noto assets use SIL OFL 1.1. */\n"+'\n'.join(faces)+'\n'
(ROOT/'typography-fonts.css').write_text(css,encoding='utf-8')
print('TYPOGRAPHY_CONTRACT_GENERATED')
