const $=s=>document.querySelector(s),inviteId=localStorage.getItem('sovan-active-invite')||'demo-wedding',token=localStorage.getItem('sovan-auth-token'),localKey=`sovan-guests:${inviteId}`;let guests=[],server=false,slug='invitation';
async function request(path,options={}){let r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
async function load(){try{await request('/api/health');server=true;let invitations=await request('/api/invitations'),invite=invitations.find(i=>i.id===inviteId);slug=invite?.slug||slug;guests=await request(`/api/invitations/${inviteId}/guests`)}catch{server=false;guests=JSON.parse(localStorage.getItem(localKey)||'[]')}render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function guestUrl(g){return server?`${location.origin}/i/${slug}?g=${g.token}`:`${location.origin}${location.pathname.replace('guests.html','public.html')}?g=${g.token}`}
function filtered(){let q=$('#search').value.trim().toLowerCase(),filter=$('#statusFilter').value;return guests.filter(g=>{let text=`${g.name} ${g.phone||''}`.toLowerCase(),status=g.rsvp_status||'';return text.includes(q)&&(filter==='all'||filter==='yes'&&status.startsWith('Yes')||filter==='no'&&status.startsWith('Unable')||filter==='pending'&&!status||filter==='checked'&&g.checked_in)})}
function render(){let yes=guests.filter(g=>g.rsvp_status?.startsWith('Yes')).length,no=guests.filter(g=>g.rsvp_status?.startsWith('Unable')).length,pending=guests.length-yes-no,checked=guests.filter(g=>g.checked_in).length;$('#summary').innerHTML=`<div class="metric"><strong>${guests.length}</strong>Invited</div><div class="metric"><strong>${yes}</strong>Attending</div><div class="metric"><strong>${no}</strong>Declined</div><div class="metric"><strong>${pending}</strong>Pending</div><div class="metric"><strong>${checked}</strong>Checked in</div>`;$('#guestList').innerHTML=filtered().map(g=>`<div class="guest-row ${g.checked_in?'checked':''}"><div><strong>${esc(g.name)}</strong><br><small>${esc(g.phone)}</small></div><span>${esc(g.rsvp_status||'Awaiting reply')}</span><button data-qr="${g.id}">QR</button><button data-check="${g.id}">${g.checked_in?'Undo check-in':'Check in'}</button><button class="danger" data-delete="${g.id}">Remove</button></div>`).join('')||'<p class="empty">No guests match this filter.</p>';document.querySelectorAll('[data-qr]').forEach(b=>b.onclick=()=>showQr(b.dataset.qr));document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>checkIn(b.dataset.check));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeGuest(b.dataset.delete))}
$('#search').oninput=render;$('#statusFilter').onchange=render;
$('#addForm').onsubmit=async e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));await addGuest(data);e.target.reset();render()};
async function addGuest(data){if(server){await request(`/api/invitations/${inviteId}/guests`,{method:'POST',body:JSON.stringify(data)});guests=await request(`/api/invitations/${inviteId}/guests`)}else{guests.unshift({id:crypto.randomUUID(),name:data.name,phone:data.phone,token:crypto.randomUUID().slice(0,12),rsvp_status:null,checked_in:false});localStorage.setItem(localKey,JSON.stringify(guests))}}
async function checkIn(id){let g=guests.find(x=>x.id===id),checkedIn=!g.checked_in;if(server){await request(`/api/invitations/${inviteId}/guests/${id}/check-in`,{method:'PUT',body:JSON.stringify({checkedIn})});guests=await request(`/api/invitations/${inviteId}/guests`)}else{g.checked_in=checkedIn;g.checked_in_at=checkedIn?Date.now():null;localStorage.setItem(localKey,JSON.stringify(guests))}render()}
async function removeGuest(id){if(!confirm('Remove this guest?'))return;if(server){await request(`/api/invitations/${inviteId}/guests/${id}`,{method:'DELETE'});guests=await request(`/api/invitations/${inviteId}/guests`)}else{guests=guests.filter(g=>g.id!==id);localStorage.setItem(localKey,JSON.stringify(guests))}render()}
function showQr(id){let g=guests.find(x=>x.id===id),url=guestUrl(g),qr=`https://quickchart.io/qr?size=420&text=${encodeURIComponent(url)}`;$('#qrBody').innerHTML=`<h2>${esc(g.name)}</h2><img src="${qr}" alt="QR code for ${esc(g.name)}"><p><button id="copyLink">Copy invitation link</button> <a href="${qr}" download="${esc(g.name)}-qr.png"><button>Download QR</button></a></p>`;$('#qrModal').showModal();$('#copyLink').onclick=async()=>{await navigator.clipboard.writeText(url);$('#copyLink').textContent='Copied!'}}
$('.close').onclick=()=>$('#qrModal').close();
function parseCsv(text){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
$('#importFile').onchange=async e=>{let rows=parseCsv(await e.target.files[0].text()),start=/name/i.test(rows[0]?.[0]||'')?1:0,added=0;for(let i=start;i<rows.length;i++){if(!rows[i][0])continue;await addGuest({name:rows[i][0],phone:rows[i][1]||''});added++}render();alert(`Imported ${added} guests.`);e.target.value=''};
$('#exportBtn').onclick=()=>{let rows=[['Name','Phone','RSVP status','Checked in','Personal link'],...guests.map(g=>[g.name,g.phone||'',g.rsvp_status||'Pending',g.checked_in?'Yes':'No',guestUrl(g)])],csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='guest-list.csv';a.click();URL.revokeObjectURL(a.href)};load();
