(()=>{'use strict';
const MAX_DURATION=5000;
function safeColor(value,fallback='#fff8f2'){const v=String(value||'').trim();return /^#[0-9a-f]{3,8}$/i.test(v)?v:fallback;}
function safeImage(value){const v=String(value||'').trim();if(!v)return'';if(/^https?:\/\//i.test(v)||/^\/uploads\//.test(v)||/^\/api\/image\//.test(v)||/^data:image\/(?:png|jpe?g|webp|avif|gif);base64,/i.test(v))return v;return'';}
function duration(value){const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(MAX_DURATION,n)):1100;}
function cssUrl(value){return String(value).replace(/["'()\\\n\r]/g,c=>`\\${c}`);}
function coverMarkup(d,mode,esc){const o=d.openingScene||{},names=mode==='km'?(d.fields?.namesKm||d.fields?.names):(d.fields?.names||'Open invitation'),subtitle=mode==='km'?(o.subtitleKm||o.subtitle||'សូមគោរពអញ្ជើញ'):(o.subtitle||'You are warmly invited'),enter=mode==='km'?(o.enterTextKm||'បើកការអញ្ជើញ'):(o.enterText||'Open invitation'),color=safeColor(o.backgroundColor),image=safeImage(o.backgroundImage),shade=o.textVariant==='light'?'#0005':'#fff3',bg=image?`background-image:linear-gradient(${shade},${shade}),url(&quot;${esc(cssUrl(image))}&quot;);background-color:${color}`:`background-color:${color}`;return `<button id="openCover" type="button" class="open-cover opening-scene-${esc(o.id||'soft-monogram')}" data-monogram="${esc(o.monogram||'')}" style="${bg};--opening-duration:${duration(o.duration)}ms" aria-label="${esc(enter)}"><span>${esc(subtitle)}</span>${o.monogram?`<b class="opening-monogram">${esc(o.monogram)}</b>`:''}<strong>${esc(names||'Invitation')}</strong><em>${esc(enter)}</em></button>`;}
function enhance(root,d){const cover=root.querySelector('#openCover');if(!cover)return;const ms=duration(d.openingScene?.duration);cover.style.transitionDuration=`${ms}ms`;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){cover.dataset.reducedMotion='true';cover.style.transition='none';}cover.addEventListener('keydown',e=>{if(e.key==='Escape'&&d.openingScene?.skipAllowed!==false){e.preventDefault();cover.click();}});cover.addEventListener('click',()=>{const hide=()=>{cover.setAttribute('aria-hidden','true');cover.hidden=true;};if(reduced||ms===0)setTimeout(hide,0);else setTimeout(hide,Math.min(ms+120,MAX_DURATION+120));},{once:true});}
window.EInviteOpeningScenes={coverMarkup,enhance,safeImage,safeColor};
})();
