(()=>{
'use strict';
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const allowed=new Set(['BR','B','STRONG','I','EM','U','S','UL','OL','LI','SPAN']);
const allowedStyles=new Set(['color','background-color','font-weight','font-style','text-decoration']);
function cleanNode(node,doc){
  if(node.nodeType===Node.TEXT_NODE)return doc.createTextNode(node.textContent||'');
  if(node.nodeType!==Node.ELEMENT_NODE)return doc.createTextNode('');
  if(!allowed.has(node.tagName)){const frag=doc.createDocumentFragment();[...node.childNodes].forEach(child=>frag.append(cleanNode(child,doc)));return frag}
  const el=doc.createElement(node.tagName.toLowerCase());
  if(node.tagName==='SPAN'&&node.getAttribute('style')){
    const safe=[];String(node.getAttribute('style')).split(';').forEach(pair=>{const [rawKey,...rest]=pair.split(':'),key=(rawKey||'').trim().toLowerCase(),value=rest.join(':').trim();if(allowedStyles.has(key)&&/^[#(),.%\w\s-]+$/.test(value))safe.push(`${key}:${value}`)});if(safe.length)el.setAttribute('style',safe.join(';'))
  }
  [...node.childNodes].forEach(child=>el.append(cleanNode(child,doc)));return el
}
function sanitizeRichText(html){
  const source=String(html??'');if(!source)return'';
  if(typeof document==='undefined')return esc(source.replace(/<[^>]+>/g,''));
  const template=document.createElement('template');template.innerHTML=source;const out=document.createElement('div');[...template.content.childNodes].forEach(node=>out.append(cleanNode(node,document)));return out.innerHTML
}
function plainText(html){if(typeof document==='undefined')return String(html??'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const div=document.createElement('div');div.innerHTML=sanitizeRichText(html);return div.textContent||''}
function imageFilterStyle(o={}){const clamp=(v,min,max,fallback)=>Math.max(min,Math.min(max,Number(v??fallback)));return`brightness(${clamp(o.imageBrightness,20,200,100)}%) contrast(${clamp(o.imageContrast,20,200,100)}%) saturate(${clamp(o.imageSaturation,0,250,100)}%) grayscale(${clamp(o.imageGrayscale,0,100,0)}%) sepia(${clamp(o.imageSepia,0,100,0)}%) hue-rotate(${clamp(o.imageHue,-180,180,0)}deg) blur(${clamp(o.imageBlur,0,20,0)}px)`}
function objectDimension(value,axis='x'){if(!value)return axis==='x'?'50%':'80px';if(String(value).includes('%'))return value;const number=parseFloat(value);if(!Number.isFinite(number))return value;return`${number/(axis==='x'?390:844)*100}%`}

function animationName(value){return({'fade-up':'fadeUp','soft-zoom':'softZoom','slide-left':'slideLeft','blur-in':'blurIn','bounce-in':'bounceIn','flip-in':'flipIn','float':'floatIn','none':'none'})[value]||'fadeUp'}
function advancedObjectStyle(o={}){const blend=['normal','multiply','screen','overlay','soft-light','darken','lighten'].includes(o.blendMode)?o.blendMode:'normal';const delay=Math.max(0,Math.min(5000,Number(o.animationDelay||0)));let background='transparent';if(o.backgroundEnabled){const hex=/^#[0-9a-f]{6}$/i.test(o.backgroundColor||'')?o.backgroundColor:'#ffffff',alpha=Math.max(0,Math.min(100,Number(o.backgroundOpacity??100)))/100,h=hex.slice(1);background=`rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},${alpha})`}return`mix-blend-mode:${blend};background:${background};animation-delay:${delay}ms`}
function advancedTextStyle(o={}){const transform=['none','uppercase','lowercase','capitalize'].includes(o.textTransform)?o.textTransform:'none',stroke=Math.max(0,Math.min(8,Number(o.textStrokeWidth||0))),strokeColor=/^#[0-9a-f]{6}$/i.test(o.textStrokeColor||'')?o.textStrokeColor:'#ffffff',shadowBlur=Math.max(0,Math.min(40,Number(o.textShadowBlur||0))),shadowColor=/^#[0-9a-f]{6}$/i.test(o.textShadowColor||'')?o.textShadowColor:'#000000',shadow=shadowBlur?`text-shadow:0 ${Math.max(1,Math.round(shadowBlur/4))}px ${shadowBlur}px ${shadowColor};`:'',gradient=o.textGradientEnabled?`background-image:linear-gradient(${Math.max(0,Math.min(360,Number(o.textGradientAngle||90)))}deg,${esc(o.textGradientStart||'#9d4555')},${esc(o.textGradientEnd||'#b58a3a')});background-clip:text;-webkit-background-clip:text;color:transparent;`:'';return`text-transform:${transform};-webkit-text-stroke:${stroke}px ${strokeColor};${shadow}${gradient}`}
function shapeFillStyle(o={}){return o.fillMode==='gradient'?`linear-gradient(${Math.max(0,Math.min(360,Number(o.gradientAngle||135)))}deg,${esc(o.gradientStart||'#d9a6ad')},${esc(o.gradientEnd||'#9d4555')})`:esc(o.fillColor||'#d9a6ad')}
function renderObject(o={},options={}){
 const id=options.id||'',pageHeight=Number(options.pageHeight||844),content=options.content!==undefined?options.content:sanitizeRichText(o.html||''),heroTitle=!!options.heroTitle;
 const borderWidth=Math.max(0,Math.min(12,Number(o.borderWidth||0))),borderRadius=Math.max(0,Math.min(120,Number(o.borderRadius||0))),shadowBlur=Math.max(0,Math.min(60,Number(o.shadowBlur||0))),opacity=Math.max(.1,Math.min(1,Number(o.opacity??1))),shadow=shadowBlur?`0 ${Math.max(2,Math.round(shadowBlur/3))}px ${shadowBlur}px ${esc(o.shadowColor||'#000000')}55`:'none';
 const height=String(o.height||'80px').includes('%')?o.height:`${parseFloat(o.height||80)/pageHeight*100}%`,top=String(o.top||'0').includes('%')?o.top:`${parseFloat(o.top||0)/pageHeight*100}%`;
 const common=`left:${esc(o.left||'0')};top:${esc(top)};width:${esc(objectDimension(o.width,'x'))};height:${esc(height)};z-index:${Number(o.zIndex||1)};transform:rotate(${Number(o.rotation||0)}deg);opacity:${opacity};border:${borderWidth}px solid ${esc(o.borderColor||'#ffffff')};border-radius:${borderRadius}px;box-shadow:${shadow};animation-name:${animationName(o.animation)};animation-duration:${Math.max(300,Math.min(3000,Number(o.duration||900)))}ms;${advancedObjectStyle(o)}`;
 if(o.type==='image'&&o.src){const masks={none:'none',circle:'ellipse(50% 50% at 50% 50%)',arch:'inset(0 round 48% 48% 12% 12%)',diamond:'polygon(50% 0,100% 50%,50% 100%,0 50%)',hexagon:'polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%)',blob:'polygon(50% 0,78% 8%,96% 35%,91% 72%,66% 100%,31% 94%,6% 68%,0 32%,22% 7%)'},frames={none:['0','transparent'],white:['8px','#ffffff'],gold:['8px','#c79b42'],dark:['8px','#201b1b']},frame=frames[o.imageFrame||'none']||frames.none;return`<div class="published-object published-image reveal" style="${common}"><img src="${esc(o.src)}" alt="${esc(o.alt||'Invitation image')}" style="object-fit:${esc(o.imageFit||'cover')};object-position:${Number(o.imagePositionX??50)}% ${Number(o.imagePositionY??50)}%;border-radius:inherit;clip-path:${masks[o.imageMask||'none']||'none'};padding:${frame[0]};background:${frame[1]};box-sizing:border-box;filter:${imageFilterStyle(o)};transform:scaleX(${o.imageFlipX?-1:1}) scaleY(${o.imageFlipY?-1:1})"></div>`}
 if(o.type==='shape'){const kind=['rectangle','circle','line'].includes(o.shapeKind)?o.shapeKind:'rectangle',radius=kind==='circle'?'999px':'inherit';return`<div class="published-object published-shape published-shape-${kind} reveal" aria-hidden="true" style="${common};background:${shapeFillStyle(o)};border-radius:${radius}"></div>`}
 const textAlign=['left','center','right'].includes(o.textAlign)?o.textAlign:'center',justify=textAlign==='left'?'flex-start':textAlign==='right'?'flex-end':'center',vertical=['top','middle','bottom'].includes(o.textVerticalAlign)?o.textVerticalAlign:'middle',alignItems=vertical==='top'?'flex-start':vertical==='bottom'?'flex-end':'center',textPadding=Math.max(0,Math.min(64,Number(o.textPadding??8))),fontSize=Number(o.fontSize||0)?`font-size:${Math.max(8,Math.min(160,Number(o.fontSize)))}px;`:'',weight=o.fontWeight==='700'?'700':'400',fontStyle=o.fontStyle==='italic'?'italic':'normal',spacing=Math.max(-2,Math.min(20,Number(o.letterSpacing||0))),lineHeight=Math.max(.8,Math.min(3,Number(o.lineHeight||1.35)));
 return`<div class="published-object published-text reveal${heroTitle?' hero-object-title':''}${o.type==='decoration'?' published-decoration':''}" style="${common};font-family:${esc(o.font||'inherit')};color:${esc(o.color||'inherit')};${fontSize}font-weight:${weight};font-style:${fontStyle};letter-spacing:${spacing}px;line-height:${lineHeight};text-align:${textAlign};justify-content:${justify};align-items:${alignItems};padding:${textPadding}px;${advancedTextStyle(o)}">${content}</div>`
}

window.EInviteRenderer={esc,sanitizeRichText,plainText,imageFilterStyle,objectDimension,animationName,advancedObjectStyle,advancedTextStyle,shapeFillStyle,renderObject};
})();
