const $=s=>document.querySelector(s),inviteId=localStorage.getItem('sovan-active-invite')||'demo-wedding',token=localStorage.getItem('sovan-auth-token');let responses=[],wishes=[],documentData={},server=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
function customLabels(){return Object.fromEntries((documentData.rsvpFields||[]).map(f=>[`custom_${f.id}`,f.label||f.labelKm||f.id]))}
function metrics(){const yes=responses.filter(r=>String(r.status).startsWith('Yes')),no=responses.filter(r=>String(r.status).startsWith('Unable')),maybe=responses.filter(r=>r.status==='Maybe'),guests=yes.reduce((n,r)=>n+Number(r.guest_count||r.count||1),0);$('#metrics').innerHTML=`<div class="response-metric"><strong>${responses.length}</strong>Responses</div><div class="response-metric"><strong>${yes.length}</strong>Attending replies</div><div class="response-metric"><strong>${guests}</strong>Attending guests</div><div class="response-metric"><strong>${wishes.length}</strong>Guest wishes</div>`}
function filteredResponses(){const q=$('#responseSearch').value.trim().toLowerCase(),filter=$('#responseFilter').value;return responses.filter(r=>{const text=`${r.name} ${r.status} ${r.note||''} ${Object.values(r.answers||{}).join(' ')}`.toLowerCase(),status=String(r.status||'');return text.includes(q)&&(filter==='all'||filter==='yes'&&status.startsWith('Yes')||filter==='no'&&status.startsWith('Unable')||filter==='maybe'&&status==='Maybe')})}
function renderResponses(){const labels=customLabels(),items=filteredResponses();$('#responseList').innerHTML=items.length?items.map(r=>`<article class="response-card" data-id="${esc(r.id)}"><div><h3>${esc(r.name)}</h3><p>${esc(r.note||'No message')}</p>${Object.entries(r.answers||{}).filter(([,v])=>String(v||'').trim()).map(([k,v])=>`<div class="custom-answer"><strong>${esc(labels[k]||k.replace(/^custom_/,''))}:</strong> ${esc(v)}</div>`).join('')}</div><label>Status<select data-status><option ${r.status==='Yes, joyfully'?'selected':''}>Yes, joyfully</option><option ${r.status==='Unable to attend'?'selected':''}>Unable to attend</option><option ${r.status==='Maybe'?'selected':''}>Maybe</option></select></label><label>Guests<input data-count type="number" min="1" max="10" value="${Number(r.guest_count||r.count||1)}"></label><div><button data-save>Save</button><button class="danger" data-delete>Delete</button><small style="display:block;margin-top:8px">${new Date(r.created_at||r.createdAt||Date.now()).toLocaleString()}</small></div></article>`).join(''):'<div class="empty-state">No RSVP responses match this view.</div>';document.querySelectorAll('.response-card').forEach(card=>{card.querySelector('[data-save]').onclick=()=>saveResponse(card);card.querySelector('[data-delete]').onclick=()=>deleteResponse(card.dataset.id)})}
function renderWishes(){$('#wishList').innerHTML=wishes.length?wishes.map(w=>`<article class="wish-card"><h3>${esc(w.name)}</h3><p>${esc(w.message)}</p><small>${new Date(w.createdAt||w.created_at||Date.now()).toLocaleString()}</small>${server?`<p><button class="danger" data-delete-wish="${esc(w.id)}">Delete</button></p>`:''}</article>`).join(''):'<div class="empty-state">No private guest wishes yet.</div>';document.querySelectorAll('[data-delete-wish]').forEach(b=>b.onclick=()=>deleteWish(b.dataset.deleteWish))}
async function saveResponse(card){if(!server)return;const id=card.dataset.id,status=card.querySelector('[data-status]').value,guestCount=Number(card.querySelector('[data-count]').value||1),button=card.querySelector('[data-save]');button.disabled=true;try{await request(`/api/invitations/${inviteId}/rsvps/${id}`,{method:'PUT',body:JSON.stringify({status,guestCount})});const item=responses.find(x=>x.id===id);if(item){item.status=status;item.guest_count=guestCount}metrics();button.textContent='Saved';setTimeout(()=>button.textContent='Save',1000)}catch(err){alert(err.message)}finally{button.disabled=false}}
async function deleteResponse(id){if(!server||!(await uiConfirm('Delete this RSVP response?',{title:'Delete RSVP response',danger:true,confirmText:'Delete'})))return;try{await request(`/api/invitations/${inviteId}/rsvps/${id}`,{method:'DELETE'});responses=responses.filter(x=>x.id!==id);metrics();renderResponses()}catch(err){alert(err.message)}}
async function deleteWish(id){if(!server||!(await uiConfirm('Delete this guest wish?',{title:'Delete guest wish',danger:true,confirmText:'Delete'})))return;try{await request(`/api/invitations/${inviteId}/wishes/${id}`,{method:'DELETE'});wishes=wishes.filter(x=>x.id!==id);metrics();renderWishes()}catch(err){alert(err.message)}}
function csvCell(v){return`"${String(v??'').replaceAll('"','""')}"`}
$('#exportRsvp').onclick=()=>{const fields=documentData.rsvpFields||[],rows=[['Name','Status','Guest count','Message',...fields.map(f=>f.label||f.labelKm||f.id)],...responses.map(r=>[r.name,r.status,r.guest_count||r.count||1,r.note||'',...fields.map(f=>(r.answers||{})[`custom_${f.id}`]||'')])],csv=rows.map(row=>row.map(csvCell).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='rsvp-responses.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#responseSearch').oninput=renderResponses;$('#responseFilter').onchange=renderResponses;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#rsvpPanel').classList.toggle('hidden',b.dataset.tab!=='rsvp');$('#wishesPanel').classList.toggle('hidden',b.dataset.tab!=='wishes')});
async function load(){try{await request('/api/health');server=true;const invite=await request(`/api/invitations/${inviteId}`);documentData=invite.document||{};[responses,wishes]=await Promise.all([request(`/api/invitations/${inviteId}/rsvps`),request(`/api/invitations/${inviteId}/wishes`)]);}catch{server=false;documentData=JSON.parse(localStorage.getItem(`sovan-invite-draft-v3:${inviteId}`)||'{}');responses=JSON.parse(localStorage.getItem(`sovan-invite-rsvps-v3:${inviteId}`)||'[]');wishes=JSON.parse(localStorage.getItem(`sovan-invite-wishes-v1:${inviteId}`)||'[]')}metrics();renderResponses();renderWishes()}
load();
