(()=>{
'use strict';
const VERSION='23.8.3';
if(window.EInviteReviewWorkflow?.version===VERSION)return;
const registry=window.EInviteCommandRegistry,bridge=window.EInviteEditorBridge,stage=document.querySelector('#stage');
if(!registry||!bridge||!stage)return;
if(!document.querySelector('link[data-v23-review]')){const link=document.createElement('link');link.rel='stylesheet';link.href='review-v23.css';link.dataset.v23Review='1';document.head.append(link)}
const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const clean=(value,max=2000)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const finite=(value,fallback=-1)=>Number.isFinite(Number(value))?Number(value):fallback;
const clamp01=value=>Math.max(0,Math.min(1,finite(value,0)));
const backendOnline=()=>window.EInviteBackend?.isAvailable?.()===true;
function setSurfaceHidden(node,hidden){if(!node)return;node.hidden=!!hidden;if(hidden){node.inert=true;node.dataset.v20AutoInert='true'}else{node.inert=false;node.removeAttribute('inert');delete node.dataset.v20AutoInert}}
const invitationId=()=>window.serverInvite?.id||window.EInviteContext?.getInvitationId?.({allowRemembered:false})||window.EInviteContext?.getInvitationId?.()||'';
const currentCanvas=()=>String(bridge.getActiveCanvasId?.()||'hero');
let drawer,pinLayer,placementBanner,comments=[],approvals=[],reviewContext={role:'',canManage:false,canEdit:false,readiness:null,notifications:[],unreadCount:0},activeTab='comments',filter='open',scope='current',query='',pinsVisible=true,pendingPlacement=null,activeThread='',loading=false,lastError='',pollTimer=0,renderQueued=0,opener=null;
const unregister=[];
function announce(message,icon='✦'){
 window.uiToast?.(message,icon);
 let live=$('#v23ReviewLive');if(!live){live=document.createElement('div');live.id='v23ReviewLive';live.className='sr-only';live.setAttribute('aria-live','polite');document.body.append(live)}
 live.textContent='';requestAnimationFrame(()=>live.textContent=message);
}
async function api(path,options={}){
 if(!backendOnline())throw Error('Team review requires the full application server.');
 const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});
 const data=await response.json().catch(()=>({}));
 if(!response.ok)throw Error(data.error||`Request failed (${response.status})`);
 return data;
}
function normalizeComment(row={}){return{id:clean(row.id,120),email:clean(row.email||'Collaborator',254),userId:clean(row.user_id||row.userId,120),objectId:clean(row.object_id||row.objectId,120),pageId:clean(row.page_id||row.pageId,120),parentId:clean(row.parent_id||row.parentId,120),x:finite(row.anchor_x??row.anchorX,-1),y:finite(row.anchor_y??row.anchorY,-1),body:clean(row.body),resolved:row.resolved===true||Number(row.resolved)===1,createdAt:finite(row.created_at??row.createdAt,Date.now()),updatedAt:finite(row.updated_at??row.updatedAt,Date.now()),canDelete:row.canDelete===true}}
function normalizeApproval(row={}){let summary=row.summary||{};if(typeof summary==='string'){try{summary=JSON.parse(summary)}catch{summary={}}}return{id:clean(row.id,120),requester:clean(row.requester_email||row.requesterEmail||'Approval request',254),requestedFrom:clean(row.requested_from||row.requestedFrom,254),status:clean(row.status,40)||'pending',note:clean(row.note),revision:finite(row.document_revision??row.documentRevision,0),fingerprint:clean(row.document_fingerprint||row.documentFingerprint,80),summary,stale:row.stale===true,createdAt:finite(row.created_at??row.createdAt,Date.now()),updatedAt:finite(row.updated_at??row.updatedAt,Date.now()),decider:clean(row.decider_email||row.deciderEmail,254),decidedAt:finite(row.decided_at??row.decidedAt,0)}}
function normalizeNotification(row={}){return{id:clean(row.id,120),kind:clean(row.kind,60),targetId:clean(row.target_id||row.targetId,120),message:clean(row.message,500),actor:clean(row.actor_email||row.actorEmail||'Collaborator',254),read:row.read===true||Boolean(row.read_at||row.readAt),readAt:finite(row.read_at??row.readAt,0),createdAt:finite(row.created_at??row.createdAt,Date.now())}}
const rootComments=()=>comments.filter(comment=>!comment.parentId);
const repliesFor=id=>comments.filter(comment=>comment.parentId===id).sort((a,b)=>a.createdAt-b.createdAt);
function pageName(canvasId){if(canvasId==='hero'||!canvasId)return'Main hero';const id=String(canvasId).replace(/^page:/,'');return(bridge.getState?.().designPages||[]).find(page=>String(page.id)===id)?.name||'Design page'}
function anchorLabel(comment){if(comment.objectId)return`Object · ${comment.objectId}`;if(comment.x>=0&&comment.y>=0)return`Pinned · ${pageName(comment.pageId)}`;return comment.pageId?pageName(comment.pageId):'Invitation'}
function timestamp(value){try{return new Date(value).toLocaleString()}catch{return''}}
function eligibleRoots(){const term=query.toLocaleLowerCase(),canvas=currentCanvas();return rootComments().filter(comment=>{if(filter==='open'&&comment.resolved)return false;if(filter==='resolved'&&!comment.resolved)return false;if(scope==='current'&&comment.pageId&&comment.pageId!==canvas)return false;if(term&&!`${comment.body} ${comment.email} ${anchorLabel(comment)} ${repliesFor(comment.id).map(reply=>reply.body).join(' ')}`.toLocaleLowerCase().includes(term))return false;return true}).sort((a,b)=>b.updatedAt-a.updatedAt)}
const latestApproval=()=>approvals.slice().sort((a,b)=>b.updatedAt-a.updatedAt)[0]||null;
function ensureShell(){
 if(drawer)return drawer;
 drawer=document.createElement('aside');drawer.id='v23ReviewDrawer';drawer.className='v23-review-drawer v23-command-surface';setSurfaceHidden(drawer,true);drawer.setAttribute('aria-label','Design review');
 drawer.innerHTML=`<header><div><small>Team review</small><h2>Comments, approval & readiness</h2></div><button type="button" data-refresh aria-label="Refresh review">↻</button><button type="button" data-close aria-label="Close review">×</button></header><nav class="v23-review-tabs" aria-label="Review sections"><button type="button" data-tab="comments" aria-selected="true">Comments <span data-comment-total></span></button><button type="button" data-tab="approvals" aria-selected="false">Approval <span data-approval-total></span></button><button type="button" data-tab="activity" aria-selected="false">Activity <span data-activity-total></span></button></nav><div class="v23-review-body"><section class="v23-review-panel" data-panel="comments"></section><section class="v23-review-panel" data-panel="approvals" hidden></section><section class="v23-review-panel" data-panel="activity" hidden></section></div><footer><span data-review-status>Review data is private to collaborators.</span><div class="v23-review-footer-actions"><button type="button" data-toggle-pins>Hide pins</button><button type="button" data-export-review>Export</button><button type="button" data-import-review>Import</button><input class="v23-review-import" type="file" accept="application/json,.json"></div></footer>`;
 document.body.append(drawer);
 drawer.querySelector('[data-close]').onclick=close;drawer.querySelector('[data-refresh]').onclick=()=>refresh({force:true});
 drawer.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{activeTab=button.dataset.tab;render()});
 drawer.querySelector('[data-toggle-pins]').onclick=()=>{pinsVisible=!pinsVisible;renderPins();renderFooter()};
 drawer.querySelector('[data-export-review]').onclick=exportReview;drawer.querySelector('[data-import-review]').onclick=()=>drawer.querySelector('.v23-review-import').click();
 drawer.querySelector('.v23-review-import').onchange=event=>{const file=event.target.files?.[0];event.target.value='';if(file)importReview(file)};
 drawer.addEventListener('click',handleDrawerClick);drawer.addEventListener('submit',handleDrawerSubmit);drawer.addEventListener('input',handleDrawerInput);
 return drawer;
}
function ensurePinLayer(){if(pinLayer?.isConnected)return pinLayer;pinLayer=document.createElement('div');pinLayer.id='v23ReviewPins';pinLayer.className='v23-review-pin-layer';pinLayer.setAttribute('aria-label','Review comment pins');stage.append(pinLayer);return pinLayer}
function ensurePlacementBanner(){if(placementBanner)return placementBanner;placementBanner=document.createElement('div');placementBanner.className='v23-review-placement-banner';setSurfaceHidden(placementBanner,true);placementBanner.textContent='Click the canvas to place this review comment · Esc to cancel';document.body.append(placementBanner);return placementBanner}
function unavailableMarkup(){return`<div class="v23-review-offline"><strong>Save this invitation to use team review.</strong><p>Comments and approvals are stored separately from the published invitation and require the application server.</p></div>`}
function commentHeader(comment){return`<div class="v23-review-comment-head"><strong>${escapeHtml(comment.email)}</strong><time>${escapeHtml(timestamp(comment.createdAt))}</time></div>`}
function threadMarkup(root){const replies=repliesFor(root.id);return`<article class="v23-review-thread${root.resolved?' is-resolved':''}${activeThread===root.id?' is-active':''}" data-thread-id="${escapeHtml(root.id)}"><div class="v23-review-comment">${commentHeader(root)}<p>${escapeHtml(root.body)}</p><div class="v23-review-anchor"><button type="button" data-jump-comment="${escapeHtml(root.id)}">${escapeHtml(anchorLabel(root))}</button>${root.resolved?'<span class="v23-review-badge">Resolved</span>':''}</div><div class="v23-review-row-actions"><button type="button" data-reply-comment="${escapeHtml(root.id)}">Reply</button><button type="button" data-resolve-comment="${escapeHtml(root.id)}">${root.resolved?'Reopen':'Resolve'}</button>${root.canDelete?`<button type="button" data-delete-comment="${escapeHtml(root.id)}">Delete</button>`:''}</div></div>${replies.map(reply=>`<div class="v23-review-comment is-reply">${commentHeader(reply)}<p>${escapeHtml(reply.body)}</p><div class="v23-review-row-actions">${reply.canDelete?`<button type="button" data-delete-comment="${escapeHtml(reply.id)}">Delete reply</button>`:''}</div></div>`).join('')}<form class="v23-review-reply-form" data-reply-form="${escapeHtml(root.id)}" hidden><textarea name="body" maxlength="2000" placeholder="Write a reply"></textarea><div class="v23-review-row-actions"><button class="primary" type="submit">Reply</button><button type="button" data-cancel-reply="${escapeHtml(root.id)}">Cancel</button></div></form></article>`}
function renderComments(){const panel=drawer?.querySelector('[data-panel="comments"]');if(!panel)return;if(!backendOnline()||!invitationId()){panel.innerHTML=unavailableMarkup();return}const selected=(bridge.getSelectedIds?.()||[])[0]||'',roots=eligibleRoots();panel.innerHTML=`<div class="v23-review-toolbar"><input data-review-search value="${escapeHtml(query)}" placeholder="Search comments" aria-label="Search comments"><select data-review-filter aria-label="Comment status"><option value="open"${filter==='open'?' selected':''}>Open comments</option><option value="resolved"${filter==='resolved'?' selected':''}>Resolved</option><option value="all"${filter==='all'?' selected':''}>All comments</option></select><select data-review-scope aria-label="Comment page scope"><option value="current"${scope==='current'?' selected':''}>Current page</option><option value="all"${scope==='all'?' selected':''}>All pages</option></select></div><form class="v23-review-compose" data-new-comment><label>New comment<textarea name="body" maxlength="2000" placeholder="Describe the change or question"></textarea></label><small>${selected?`The primary action anchors to the selected object (${escapeHtml(selected)}).`:'Add a page-level comment or place an exact canvas pin.'}</small><div class="v23-review-compose-actions"><button type="submit" class="primary">${selected?'Comment on selection':'Add page comment'}</button><button type="button" data-place-comment>Place pin</button></div></form><div class="v23-review-list">${roots.length?roots.map(threadMarkup).join(''):`<div class="v23-review-empty"><strong>No ${filter==='all'?'matching':filter} comments</strong><span>Comments can be attached to an object, page, or exact point.</span></div>`}</div>`}
function statusLabel(approval){return approval.status.replaceAll('-',' ')}
function approvalMarkup(approval){const summary=approval.summary||{};return`<article class="v23-approval-card ${escapeHtml(approval.status)}${approval.stale?' is-stale':''}" data-approval-id="${escapeHtml(approval.id)}"><div class="v23-approval-head"><strong>${escapeHtml(statusLabel(approval))}</strong>${approval.stale?'<span class="v23-review-badge warning">Design changed</span>':''}</div><p>${escapeHtml(approval.note||'No note supplied.')}</p><dl><div><dt>Requested by</dt><dd>${escapeHtml(approval.requester)}</dd></div><div><dt>Reviewer</dt><dd>${escapeHtml(approval.requestedFrom||'Any manager')}</dd></div><div><dt>Saved revision</dt><dd>${escapeHtml(approval.fingerprint||String(approval.revision))}</dd></div><div><dt>Snapshot</dt><dd>${escapeHtml(`${summary.pages||1} page(s) · ${summary.objects||0} object(s)`)}</dd></div></dl>${approval.status==='pending'?`<div class="v23-review-row-actions"><button class="primary" type="button" data-decide-approval="approved">Approve</button><button type="button" data-decide-approval="changes-requested">Request changes</button><button type="button" data-decide-approval="cancelled">Cancel</button></div>`:''}</article>`}
function readinessMarkup(){const ready=reviewContext.readiness;if(!ready)return'<div class="v23-review-readiness is-neutral"><strong>Publish readiness unavailable</strong><span>Refresh after the invitation is saved to the server.</span></div>';const blockers=Array.isArray(ready.blockers)?ready.blockers:[],state=ready.ready?'is-ready':'is-blocked';return`<section class="v23-review-readiness ${state}"><div><small>Publishing policy</small><strong>${ready.ready?'Ready to publish':'Review requirements remain'}</strong></div><dl><div><dt>Current approvals</dt><dd>${ready.validApprovals||0} / ${ready.policy?.approvalGate?(ready.policy.minApprovals||1):'not required'}</dd></div><div><dt>Open comments</dt><dd>${ready.unresolvedComments||0}${ready.policy?.unresolvedCommentsGate?' · blocking':''}</dd></div><div><dt>Pending approvals</dt><dd>${ready.pendingApprovals||0}</dd></div></dl>${blockers.length?`<ul>${blockers.map(item=>`<li>${escapeHtml(item.message)}</li>`).join('')}</ul>`:'<p>The current saved revision satisfies the configured review policy.</p>'}</section>`}
function policyMarkup(){const policy=reviewContext.readiness?.policy||{approvalGate:false,unresolvedCommentsGate:false,minApprovals:1};if(!reviewContext.canManage)return`<div class="v23-review-policy-summary"><strong>Policy managed by invitation managers</strong><span>${policy.approvalGate?`${policy.minApprovals} approval(s) required`:'Approval is advisory'} · ${policy.unresolvedCommentsGate?'Open comments block publishing':'Open comments do not block publishing'}</span></div>`;return`<form class="v23-review-policy" data-review-policy><div><strong>Optional publish gate</strong><small>Existing invitations remain ungated unless a manager enables these rules.</small></div><label><input type="checkbox" name="approvalGate"${policy.approvalGate?' checked':''}> Require current approval before publishing</label><label>Minimum approvals<select name="minApprovals">${[1,2,3,4,5].map(value=>`<option value="${value}"${Number(policy.minApprovals||1)===value?' selected':''}>${value}</option>`).join('')}</select></label><label><input type="checkbox" name="unresolvedCommentsGate"${policy.unresolvedCommentsGate?' checked':''}> Block publishing while root comments remain open</label><button type="submit">Save publishing policy</button></form>`}
function renderActivity(){const panel=drawer?.querySelector('[data-panel="activity"]');if(!panel)return;if(!backendOnline()||!invitationId()){panel.innerHTML=unavailableMarkup();return}const items=reviewContext.notifications||[];panel.innerHTML=`<div class="v23-review-activity-head"><div><strong>Review activity</strong><small>${reviewContext.unreadCount||0} unread notification(s)</small></div><button type="button" data-mark-all-read${reviewContext.unreadCount?'':' disabled'}>Mark all read</button></div><div class="v23-review-activity-list">${items.length?items.map(item=>`<button type="button" class="v23-review-notification${item.read?'':' is-unread'}" data-notification-id="${escapeHtml(item.id)}"><span>${escapeHtml(item.message||item.kind)}</span><small>${escapeHtml(item.actor)} · ${escapeHtml(timestamp(item.createdAt))}</small></button>`).join(''):'<div class="v23-review-empty"><strong>No review activity</strong><span>Comments, replies, decisions, and policy changes appear here.</span></div>'}</div>`}
function renderApprovals(){const panel=drawer?.querySelector('[data-panel="approvals"]');if(!panel)return;if(!backendOnline()||!invitationId()){panel.innerHTML=unavailableMarkup();return}const reviewers=(reviewContext.reviewers||[]).map(item=>`<option value="${escapeHtml(item.email)}">${escapeHtml(item.role)} · ${escapeHtml(item.email)}</option>`).join('');panel.innerHTML=`${readinessMarkup()}${policyMarkup()}<form class="v23-approval-request" data-request-approval><label>Reviewer email or user ID<input name="requestedFrom" maxlength="254" list="v23Reviewers" placeholder="reviewer@example.com"><datalist id="v23Reviewers">${reviewers}</datalist></label><label>Review note<textarea name="note" maxlength="2000" placeholder="Please review this saved revision"></textarea></label><button class="primary" type="submit">Request approval</button><small>Choose an invitation collaborator when possible. Approval is bound to the current saved document fingerprint.</small></form><div class="v23-approval-list">${approvals.length?approvals.map(approvalMarkup).join(''):'<div class="v23-review-empty"><strong>No approval requests</strong><span>Request approval when the design is ready for a formal decision.</span></div>'}</div>`}
function renderFooter(){if(!drawer)return;const status=drawer.querySelector('[data-review-status]');status.textContent=loading?'Refreshing review…':lastError||`${reviewContext.unreadCount||0} unread · review data is private to collaborators.`;drawer.querySelector('[data-toggle-pins]').textContent=pinsVisible?'Hide pins':'Show pins'}
function render(){ensureShell();drawer.querySelectorAll('[data-tab]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.tab===activeTab)));drawer.querySelectorAll('[data-panel]').forEach(panel=>setSurfaceHidden(panel,panel.dataset.panel!==activeTab));drawer.querySelector('[data-comment-total]').textContent=comments.length?`(${rootComments().filter(comment=>!comment.resolved).length})`:'';drawer.querySelector('[data-approval-total]').textContent=approvals.length?`(${approvals.filter(approval=>approval.status==='pending').length})`:'';drawer.querySelector('[data-activity-total]').textContent=reviewContext.unreadCount?`(${Math.min(99,reviewContext.unreadCount)})`:'';renderComments();renderApprovals();renderActivity();renderFooter();renderPins();updateLaunchers()}
function objectPinPosition(comment){if(!comment.objectId)return null;const node=stage.querySelector(`.object[data-id="${CSS.escape(comment.objectId)}"]`);if(!node)return null;const stageRect=stage.getBoundingClientRect(),rect=node.getBoundingClientRect();if(!stageRect.width||!stageRect.height)return null;return{x:clamp01((rect.left+rect.width/2-stageRect.left)/stageRect.width),y:clamp01((rect.top+Math.min(24,rect.height/2)-stageRect.top)/stageRect.height)}}
function renderPins(){const layer=ensurePinLayer();layer.hidden=!pinsVisible;if(!pinsVisible){layer.replaceChildren();return}const canvas=currentCanvas(),roots=rootComments().filter(comment=>comment.pageId===canvas||(!comment.pageId&&comment.objectId&&stage.querySelector(`.object[data-id="${CSS.escape(comment.objectId)}"]`))).filter(comment=>filter==='all'||(filter==='open'?!comment.resolved:comment.resolved));const nodes=[];roots.forEach((comment,index)=>{const position=objectPinPosition(comment)||(comment.x>=0&&comment.y>=0?{x:clamp01(comment.x),y:clamp01(comment.y)}:null);if(!position)return;const button=document.createElement('button');button.type='button';button.className=`v23-review-pin${comment.resolved?' is-resolved':''}`;button.dataset.commentPin=comment.id;button.style.left=`${(position.x*100).toFixed(3)}%`;button.style.top=`${(position.y*100).toFixed(3)}%`;button.textContent=String(index+1);button.title=comment.body.slice(0,160);button.setAttribute('aria-label',`Review comment ${index+1}: ${comment.body.slice(0,120)}`);button.onclick=event=>{event.stopPropagation();open('comments');activeThread=comment.id;render();drawer.querySelector(`[data-thread-id="${CSS.escape(comment.id)}"]`)?.scrollIntoView({block:'center'})};nodes.push(button)});layer.replaceChildren(...nodes)}
function schedulePins(){cancelAnimationFrame(renderQueued);renderQueued=requestAnimationFrame(renderPins)}
async function refresh({quiet=false}={}){const id=invitationId();if(!backendOnline()||!id){comments=[];approvals=[];reviewContext={role:'',canManage:false,canEdit:false,readiness:null,notifications:[],unreadCount:0};lastError=backendOnline()?'':'Team review requires the full application server.';render();return false}if(loading)return false;loading=true;lastError='';if(!quiet)renderFooter();try{const [commentRows,approvalRows,context]=await Promise.all([api(`/api/invitations/${encodeURIComponent(id)}/comments`),api(`/api/invitations/${encodeURIComponent(id)}/approvals`),api(`/api/invitations/${encodeURIComponent(id)}/review-context`)]);comments=commentRows.map(normalizeComment);approvals=approvalRows.map(normalizeApproval);reviewContext={...context,notifications:(context.notifications||[]).map(normalizeNotification),unreadCount:Number(context.unreadCount||0)};render();return true}catch(error){lastError=error.message;if(!quiet)announce(error.message,'!');renderFooter();return false}finally{loading=false;renderFooter()}}
async function addComment(body,{objectId='',pageId='',parentId='',point=null}={}){body=clean(body);if(!body)throw Error('Write a comment first');const selected=(bridge.getSelectedIds?.()||[])[0]||'';const payload={body,parentId:clean(parentId,120),objectId:clean(objectId||(!parentId?selected:''),120),pageId:clean(pageId||currentCanvas(),120),anchorX:point?.x??-1,anchorY:point?.y??-1};const created=normalizeComment(await api(`/api/invitations/${encodeURIComponent(invitationId())}/comments`,{method:'POST',body:JSON.stringify(payload)}));comments.push(created);activeThread=created.parentId||created.id;render();announce(created.parentId?'Reply added':'Comment added','✓');return created}
async function resolveComment(id,resolved){const root=comments.find(comment=>comment.id===id);const next=resolved??!root?.resolved;const result=await api(`/api/invitations/${encodeURIComponent(invitationId())}/comments/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({resolved:next})});const item=comments.find(comment=>comment.id===result.id);if(item){item.resolved=result.resolved;item.updatedAt=Date.now()}render();announce(result.resolved?'Comment resolved':'Comment reopened','✓');return result}
async function deleteComment(id){if(!confirm('Delete this review comment?'))return false;await api(`/api/invitations/${encodeURIComponent(invitationId())}/comments/${encodeURIComponent(id)}`,{method:'DELETE'});const item=comments.find(comment=>comment.id===id),rootId=item?.parentId||id;comments=comments.filter(comment=>comment.id!==id&&(item?.parentId||comment.parentId!==rootId));render();announce('Comment deleted','✓');return true}
function startPlacement(body){body=clean(body);if(!body)throw Error('Write the pin comment first');pendingPlacement={body};setSurfaceHidden(ensurePlacementBanner(),false);document.body.classList.add('v23-review-placing');announce('Click the canvas to place the comment pin')}
function cancelPlacement(){pendingPlacement=null;if(placementBanner)setSurfaceHidden(placementBanner,true);document.body.classList.remove('v23-review-placing')}
function onStagePointer(event){if(!pendingPlacement||!stage.contains(event.target))return;event.preventDefault();event.stopImmediatePropagation();const rect=stage.getBoundingClientRect(),point={x:clamp01((event.clientX-rect.left)/rect.width),y:clamp01((event.clientY-rect.top)/rect.height)},body=pendingPlacement.body;cancelPlacement();addComment(body,{pageId:currentCanvas(),point}).then(()=>{const field=drawer.querySelector('[data-new-comment] textarea');if(field)field.value=''}).catch(error=>announce(error.message,'!'))}
function handleDrawerInput(event){if(event.target.matches('[data-review-search]')){query=event.target.value;renderComments()}if(event.target.matches('[data-review-filter]')){filter=event.target.value;render()}if(event.target.matches('[data-review-scope]')){scope=event.target.value;renderComments()}}
function setReplyFormOpen(form,open){setSurfaceHidden(form,!open)}
function handleDrawerClick(event){const reply=event.target.closest('[data-reply-comment]'),cancel=event.target.closest('[data-cancel-reply]'),resolve=event.target.closest('[data-resolve-comment]'),remove=event.target.closest('[data-delete-comment]'),jump=event.target.closest('[data-jump-comment]'),place=event.target.closest('[data-place-comment]'),decision=event.target.closest('[data-decide-approval]'),notification=event.target.closest('[data-notification-id]'),markAll=event.target.closest('[data-mark-all-read]');if(reply){const form=drawer.querySelector(`[data-reply-form="${CSS.escape(reply.dataset.replyComment)}"]`);setReplyFormOpen(form,true);form.querySelector('textarea').focus()}if(cancel)setReplyFormOpen(drawer.querySelector(`[data-reply-form="${CSS.escape(cancel.dataset.cancelReply)}"]`),false);if(resolve)resolveComment(resolve.dataset.resolveComment).catch(error=>announce(error.message,'!'));if(remove)deleteComment(remove.dataset.deleteComment).catch(error=>announce(error.message,'!'));if(jump)jumpToComment(jump.dataset.jumpComment);if(place){const body=drawer.querySelector('[data-new-comment] textarea')?.value||'';try{startPlacement(body)}catch(error){announce(error.message,'!')}}if(decision){const card=decision.closest('[data-approval-id]'),status=decision.dataset.decideApproval,note=status==='changes-requested'?(prompt('Describe the requested changes:')||''):'';decideApproval(card.dataset.approvalId,status,note).catch(error=>announce(error.message,'!'))}if(notification)openNotification(notification.dataset.notificationId).catch(error=>announce(error.message,'!'));if(markAll&&!markAll.disabled)markNotifications([],true).catch(error=>announce(error.message,'!'))}
function handleDrawerSubmit(event){event.preventDefault();if(event.target.matches('[data-new-comment]')){const body=event.target.elements.body.value;addComment(body).then(()=>event.target.reset()).catch(error=>announce(error.message,'!'))}if(event.target.matches('[data-reply-form]')){const id=event.target.dataset.replyForm,body=event.target.elements.body.value;addComment(body,{parentId:id}).then(()=>{event.target.reset();setReplyFormOpen(event.target,false)}).catch(error=>announce(error.message,'!'))}if(event.target.matches('[data-request-approval]')){const form=event.target;requestApproval(form.elements.requestedFrom.value,form.elements.note.value).then(()=>form.reset()).catch(error=>announce(error.message,'!'))}if(event.target.matches('[data-review-policy]')){const form=event.target;updatePolicy({approvalGate:form.elements.approvalGate.checked,unresolvedCommentsGate:form.elements.unresolvedCommentsGate.checked,minApprovals:Number(form.elements.minApprovals.value||1)}).catch(error=>announce(error.message,'!'))}}
async function requestApproval(requestedFrom,note){const created=normalizeApproval(await api(`/api/invitations/${encodeURIComponent(invitationId())}/approvals`,{method:'POST',body:JSON.stringify({requestedFrom:clean(requestedFrom,254),note:clean(note)})}));approvals.unshift(created);render();announce('Approval requested for the current saved revision','✓');return created}
async function decideApproval(id,status,note=''){const result=await api(`/api/invitations/${encodeURIComponent(invitationId())}/approvals/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({status,note:clean(note)})});const item=approvals.find(approval=>approval.id===id);if(item){item.status=result.status;item.updatedAt=Date.now();item.decidedAt=result.decided_at||Date.now()}render();announce(status==='approved'?'Design approved':status==='changes-requested'?'Changes requested':'Approval cancelled','✓');return result}
async function updatePolicy(policy){const result=await api(`/api/invitations/${encodeURIComponent(invitationId())}/review-policy`,{method:'PUT',body:JSON.stringify(policy)});reviewContext.readiness=result.readiness;render();announce('Publishing policy updated','✓');return result}
async function markNotifications(ids=[],all=false){const result=await api(`/api/invitations/${encodeURIComponent(invitationId())}/review-notifications`,{method:'PUT',body:JSON.stringify({ids,all})});const set=new Set(ids);reviewContext.notifications=(reviewContext.notifications||[]).map(item=>all||set.has(item.id)?{...item,read:true,readAt:result.readAt}:item);reviewContext.unreadCount=reviewContext.notifications.filter(item=>!item.read).length;render();return result}
async function openNotification(id){const item=(reviewContext.notifications||[]).find(notification=>notification.id===id);if(!item)return false;if(!item.read)await markNotifications([id]);if(item.kind.startsWith('comment.')){activeTab='comments';render();await jumpToComment(item.targetId)}else{activeTab='approvals';render();if(item.targetId)drawer?.querySelector(`[data-approval-id="${CSS.escape(item.targetId)}"]`)?.scrollIntoView({block:'center'})}return true}
async function jumpToComment(id){const comment=comments.find(item=>item.id===id);if(!comment)return false;activeThread=comment.parentId||comment.id;if(comment.pageId&&comment.pageId!==currentCanvas()){try{if(typeof window.switchCanvas==='function')window.switchCanvas(comment.pageId);else if(comment.pageId==='hero')$('#editHeroCanvas')?.click();else document.querySelector(`[data-page-id="${CSS.escape(comment.pageId.replace(/^page:/,''))}"]`)?.click()}catch{}await new Promise(resolve=>setTimeout(resolve,120))}if(comment.objectId){const node=stage.querySelector(`.object[data-id="${CSS.escape(comment.objectId)}"]`);if(node){window.EInviteProfessionalEditor?.commands?.setSelection?.([comment.objectId],{canvas:false});bridge.select?.([comment.objectId]);node.scrollIntoView?.({block:'center',inline:'center'});node.animate?.([{outline:'4px solid #7b3f74'},{outline:'0 solid transparent'}],{duration:900})}}render();schedulePins();return true}
function open(tab='comments'){ensureShell();opener=document.activeElement;activeTab=tab;setSurfaceHidden(drawer,false);document.body.classList.add('review-workflow-v23-open');render();if(backendOnline())refresh({quiet:true});setTimeout(()=>drawer.querySelector('[data-review-search],input,textarea,button')?.focus(),0);if(backendOnline())startPolling();return true}
function showPublishReadiness(readiness){if(readiness)reviewContext.readiness=readiness;open('approvals');render();drawer?.querySelector('.v23-review-readiness')?.scrollIntoView({block:'start'});announce('Publishing requirements need attention','!');return true}
function close(){cancelPlacement();if(drawer)setSurfaceHidden(drawer,true);document.body.classList.remove('review-workflow-v23-open');stopPolling();opener?.focus?.();opener=null}
function startPolling(){if(!backendOnline()||pollTimer)return;pollTimer=setInterval(()=>{if(!document.hidden)refresh({quiet:true})},15000)}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=0}}
function updateLaunchers(){const openCount=rootComments().filter(comment=>!comment.resolved).length,latest=latestApproval(),unread=Number(reviewContext.unreadCount||0);$$('[data-v23-review-launch]').forEach(button=>{let badge=button.querySelector('.v23-review-count');const count=openCount+unread;if(count){if(!badge){badge=document.createElement('span');badge.className='v23-review-count';button.append(badge)}badge.textContent=String(Math.min(99,count));badge.title=`${openCount} open comment(s), ${unread} unread update(s)`}else badge?.remove()});$$('[data-v23-review-status]').forEach(node=>{const ready=reviewContext.readiness;if(ready?.policy&&(ready.policy.approvalGate||ready.policy.unresolvedCommentsGate)){node.textContent=ready.ready?'Publish ready':'Publish blocked';node.dataset.status=ready.ready?'approved':'changes-requested';return}if(!latest){node.textContent='No approval';node.dataset.status='';return}node.textContent=latest.stale?`${latest.status} · design changed`:latest.status.replaceAll('-',' ');node.dataset.status=latest.status})}
function installLaunchers(){const status=$('.studio-statusbar>div:last-child')||$('.studio-statusbar');if(status&&!status.querySelector('[data-v23-review-launch]')){const button=document.createElement('button');button.type='button';button.className='v23-review-launch';button.dataset.v23ReviewLaunch='1';button.dataset.commandId='review.open';button.textContent='Review';button.title='Comments and approval';status.prepend(button);const approval=document.createElement('span');approval.className='v23-review-status';approval.dataset.v23ReviewStatus='1';approval.textContent='No approval';status.prepend(approval)}const bar=$('#v23ContextToolbar');if(bar&&!bar.querySelector('[data-command-id="review.addComment"]')){const actions=bar.querySelector('div');if(actions){const button=document.createElement('button');button.type='button';button.dataset.commandId='review.addComment';button.textContent=(bridge.getSelectedIds?.()||[]).length?'Comment':'Review';actions.append(button)}}updateLaunchers()}
function exportReview(){const payload={schemaVersion:2,exportedAt:new Date().toISOString(),invitationId:invitationId(),comments:comments.map(comment=>({id:comment.id,parentId:comment.parentId,objectId:comment.objectId,pageId:comment.pageId,anchorX:comment.x,anchorY:comment.y,body:comment.body,resolved:comment.resolved,createdAt:comment.createdAt})),approvals:approvals.map(approval=>({status:approval.status,note:approval.note,requestedFrom:approval.requestedFrom,requestedAt:approval.createdAt,revision:approval.revision,fingerprint:approval.fingerprint,summary:approval.summary,stale:approval.stale})),policy:reviewContext.readiness?.policy||null,readiness:reviewContext.readiness?{ready:reviewContext.readiness.ready,validApprovals:reviewContext.readiness.validApprovals,unresolvedComments:reviewContext.readiness.unresolvedComments,blockers:reviewContext.readiness.blockers}:null},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`einvite-review-${invitationId()||'draft'}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);announce('Review report exported','✓');return payload}
async function importReview(file){if(file.size>500000){announce('Review import is limited to 500 KB','!');return false}let payload;try{payload=JSON.parse(await file.text())}catch{announce('The review file is not valid JSON','!');return false}const rows=Array.isArray(payload.comments)?payload.comments.slice(0,100):[];if(!rows.length){announce('No comments were found in this review file','!');return false}const roots=rows.filter(row=>!row.parentId),replies=rows.filter(row=>row.parentId),ids=new Map();let imported=0;for(const row of roots){if(!clean(row.body))continue;const created=await addComment(row.body,{objectId:row.objectId||'',pageId:row.pageId||'hero',point:finite(row.anchorX,-1)>=0?{x:row.anchorX,y:row.anchorY}:null});ids.set(String(row.id),created.id);if(row.resolved)await resolveComment(created.id,true);imported++}for(const row of replies){const parentId=ids.get(String(row.parentId));if(!parentId||!clean(row.body))continue;await addComment(row.body,{parentId});imported++}await refresh({quiet:true});announce(`${imported} review comments imported`,'✓');return imported}
function registerCommands(){unregister.push(...registry.registerMany([{id:'review.open',title:'Open comments and approval',category:'Review',keywords:['comment','approval','feedback','pin'],bindings:{standard:['Mod+Alt+Shift+M'],canva:['Mod+Alt+Shift+M'],photoshop:['Mod+Alt+Shift+M']},run:()=>open('comments')},{id:'review.addComment',title:'Add review comment',category:'Review',keywords:['feedback','annotation'],bindings:{standard:[],canva:[],photoshop:[]},run:()=>{open('comments');setTimeout(()=>drawer.querySelector('[data-new-comment] textarea')?.focus(),0);return true}},{id:'review.requestApproval',title:'Request design approval',category:'Review',keywords:['approve','reviewer'],bindings:{standard:[],canva:[],photoshop:[]},run:()=>open('approvals')},{id:'review.openActivity',title:'Open review activity',category:'Review',keywords:['notification','inbox','updates'],bindings:{standard:[],canva:[],photoshop:[]},run:()=>open('activity')},{id:'review.configurePolicy',title:'Configure publishing review policy',category:'Review',keywords:['publish gate','approval required','block comments'],bindings:{standard:[],canva:[],photoshop:[]},run:()=>open('approvals')},{id:'review.togglePins',title:'Show or hide review pins',category:'Review',bindings:{standard:[],canva:[],photoshop:[]},run:()=>{pinsVisible=!pinsVisible;renderPins();renderFooter();return pinsVisible}}]))}
function init(){registerCommands();ensurePinLayer();ensurePlacementBanner();installLaunchers();document.addEventListener('pointerdown',onStagePointer,true);document.addEventListener('einvite:selection-changed',installLaunchers);window.addEventListener('einvite:editor-state-replaced',schedulePins);window.addEventListener('einvite:state-applied',schedulePins);const localRevision=()=>{approvals.forEach(approval=>{if(approval.status==='pending'||approval.status==='approved')approval.stale=true});if(reviewContext.readiness){reviewContext.readiness.ready=!(reviewContext.readiness.policy?.approvalGate||reviewContext.readiness.policy?.unresolvedCommentsGate);if(reviewContext.readiness.policy?.approvalGate){reviewContext.readiness.validApprovals=0;reviewContext.readiness.ready=false;reviewContext.readiness.blockers=[{code:'approval_required',message:`${reviewContext.readiness.policy.minApprovals||1} current approval(s) required after saving`}]}}updateLaunchers()};window.addEventListener('einvite:local-revision',localRevision);const observer=new MutationObserver(records=>{if(records.some(record=>[...record.addedNodes].some(node=>node.nodeType===1&&(node.matches?.('.studio-statusbar,#v23ContextToolbar,.object')||node.querySelector?.('.studio-statusbar,#v23ContextToolbar,.object'))))){installLaunchers();schedulePins()}});observer.observe(document.body,{childList:true,subtree:true});window.EInviteLifecycle?.add?.(()=>{observer.disconnect();document.removeEventListener('pointerdown',onStagePointer,true);document.removeEventListener('einvite:selection-changed',installLaunchers);window.removeEventListener('einvite:editor-state-replaced',schedulePins);window.removeEventListener('einvite:state-applied',schedulePins);window.removeEventListener('einvite:local-revision',localRevision);unregister.splice(0).forEach(remove=>remove());stopPolling();drawer?.remove();pinLayer?.remove();placementBanner?.remove();$('#v23ReviewLive')?.remove()});document.body.classList.add('review-workflow-v23');refresh({quiet:true})}
window.EInviteReviewWorkflow={version:VERSION,open,close,showPublishReadiness,refresh,addComment,resolveComment,deleteComment,requestApproval,decideApproval,updatePolicy,markNotifications,openNotification,jumpToComment,exportReview,importReview,get comments(){return comments.map(comment=>({...comment}))},get approvals(){return approvals.map(approval=>({...approval}))},get context(){return structuredClone(reviewContext)},get pinsVisible(){return pinsVisible}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
