const $=s=>document.querySelector(s),tokenKey='sovan-auth-token';
let templates=[];
const clone=v=>structuredClone(v);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const token=localStorage.getItem(tokenKey);const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
function palette(doc){const p=doc?.palette||{};return{background:p.background||'#fff7f3',text:p.text||'#342c26',heading:p.heading||doc?.accent||'#9d4555'}}
function strip(value){const d=document.createElement('div');d.innerHTML=String(value||'');return d.textContent||''}
function titleOf(t){return strip(t.document?.objects?.title?.html||t.document?.fields?.names||t.name).slice(0,55)}
function thumb(t){const p=palette(t.document),pages=t.document?.designPages||[];return `<div class="studio-thumb" style="--thumb-bg:${p.background};--thumb-heading:${p.heading}"><strong>${esc(titleOf(t))}</strong><span class="page-stack">${pages.slice(0,5).map(()=>'<i></i>').join('')}</span></div>`}
function filtered(){const q=$('#studioSearch').value.trim().toLowerCase(),category=$('#studioCategory').value,favorites=$('#studioFavorites').checked;return templates.filter(t=>(category==='all'||t.category===category)&&(!favorites||t.favorite)&&(!q||`${t.name} ${t.description||''} ${(t.tags||[]).join(' ')}`.toLowerCase().includes(q)))}
function render(){const grid=$('#studioGrid'),items=filtered();grid.innerHTML=items.length?'':'<div class="empty"><h2>No templates found</h2><p>Create a design in the invitation editor and choose “Save complete design as template”.</p></div>';items.forEach(t=>{const card=document.createElement('article');card.className='studio-card';card.innerHTML=`${thumb(t)}<div class="studio-body"><div class="studio-title"><div><h2>${esc(t.name)}</h2><span class="meta">${esc(t.category)} · Updated ${new Date(t.updatedAt).toLocaleDateString()}</span></div><button class="star${t.favorite?' active':''}" title="Favorite">★</button></div><p>${esc(t.description||'Reusable invitation design')}</p><div class="tags">${(t.tags||[]).map(x=>`<span>${esc(x)}</span>`).join('')}<span class="version-badge">v${t.currentVersion||1}</span><span class="version-badge">${t.visibility==='public'?'Marketplace':'Private'}</span></div><div class="studio-actions"><button data-action="preview">Preview</button><button data-action="use" class="primary">Use</button><button data-action="edit-design">Edit design</button><button data-action="meta">Details</button><button data-action="versions">Versions</button><button data-action="visibility">${t.visibility==='public'?'Remove from marketplace':'Publish to marketplace'}</button><button data-action="duplicate">Duplicate</button><button data-action="delete" class="danger">Delete</button></div></div>`;card.querySelector('.star').onclick=()=>favorite(t);card.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions(b.dataset.action,t));grid.append(card)})}
async function load(){try{const me=await api('/api/auth/me');if(!me.user){location.href='dashboard.html';return}$('#studioAccount').textContent=me.user.email;templates=await api('/api/templates');render()}catch(error){$('#studioGrid').innerHTML=`<div class="empty"><h2>Template Studio needs the local backend</h2><p>${esc(error.message)}</p></div>`}}
async function favorite(t){try{const updated=await api(`/api/templates/${t.id}`,{method:'PUT',body:JSON.stringify({favorite:!t.favorite})});templates[templates.findIndex(x=>x.id===t.id)]=updated;render()}catch(error){alert(error.message)}}
async function actions(action,t){if(action==='preview')return preview(t);if(action==='use')return useTemplate(t,false);if(action==='edit-design')return useTemplate(t,true);if(action==='meta')return editMeta(t);if(action==='versions')return versions(t);if(action==='visibility'){const makePublic=t.visibility!=='public',message=makePublic?'Publish this template to the shared marketplace? Anyone using this server will be able to create invitations from it.':'Remove this template from the shared marketplace? Existing invitations created from it will not be affected.';if(!(await uiConfirm(message,{title:makePublic?'Publish template':'Remove from marketplace',confirmText:makePublic?'Publish':'Remove'})))return;try{const updated=await api(`/api/templates/${t.id}`,{method:'PUT',body:JSON.stringify({visibility:makePublic?'public':'private'})});templates[templates.findIndex(x=>x.id===t.id)]=updated;render()}catch(error){alert(error.message)}return}if(action==='duplicate'){try{const copy=await api(`/api/templates/${t.id}/duplicate`,{method:'POST',body:'{}'});templates.unshift(copy);render()}catch(error){alert(error.message)}return}if(action==='delete'){if(!(await uiConfirm(`Delete template “${t.name}” and its version history?`,{title:'Delete template',danger:true,confirmText:'Delete permanently'})))return;try{await api(`/api/templates/${t.id}`,{method:'DELETE'});templates=templates.filter(x=>x.id!==t.id);render()}catch(error){alert(error.message)}}}
async function useTemplate(t,editDesign){const name=await uiPrompt(editDesign?'Name the temporary invitation used to edit this template:':'Choose a name for the new invitation:',editDesign?`${t.name} — Template Edit`:'New Invitation',{title:editDesign?'Edit template design':'Create from template',confirmText:'Continue'});if(!name)return;try{const doc=clone(t.document);doc.fields={...(doc.fields||{}),names:name};const item=await api('/api/invitations',{method:'POST',body:JSON.stringify({slug:name,document:doc})});localStorage.setItem('sovan-active-invite',item.id);location.href=`index.html${editDesign?`?templateEdit=${encodeURIComponent(t.id)}`:''}`}catch(error){alert(error.message)}}
function previewPage(page,master){const bg=page.useMasterBackground&&master?.enabled?master:page;const image=bg?.backgroundImage?`background-image:linear-gradient(rgba(0,0,0,${Number(bg.backgroundOverlay||0)/100}),rgba(0,0,0,${Number(bg.backgroundOverlay||0)/100})),url('${esc(bg.backgroundImage)}');background-size:${bg.backgroundSize||'cover'};background-position:center;`:'';return `<div class="preview-page" style="--page-bg:${esc(bg?.background||'#fff')};${image}"><strong>${esc(page.name||'Visual page')}</strong></div>`}
function preview(t){const p=palette(t.document),pages=t.document?.designPages||[];$('#studioDialogBody').innerHTML=`<div class="studio-preview"><div class="preview-phone"><div class="preview-screen" style="--p-bg:${p.background};--p-text:${p.text};--p-heading:${p.heading}"><div class="preview-hero"><h2>${esc(titleOf(t))}</h2></div>${pages.map(x=>previewPage(x,t.document.masterPageStyle)).join('')}</div></div><div><p class="invite-kicker">${esc(t.category)}</p><h1>${esc(t.name)}</h1><p>${esc(t.description||'')}</p><p><strong>Current version:</strong> ${t.currentVersion||1}</p><p><strong>Visual pages:</strong> ${pages.length}</p><p><strong>Sections:</strong> ${(t.document?.sectionOrder||[]).filter(x=>!String(x).startsWith('page:')).join(', ')}</p><div class="tags">${(t.tags||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><button id="previewUse" class="primary">Create invitation from this template</button></div></div>`;$('#previewUse').onclick=()=>{$('#studioDialog').close();useTemplate(t,false)};$('#studioDialog').showModal()}
function editMeta(t){$('#studioDialogBody').innerHTML=`<h1>Edit template details</h1><form id="metaForm" class="form-grid"><label>Name<input id="metaName" value="${esc(t.name)}" required maxlength="120"></label><label>Category<select id="metaCategory"><option>Wedding</option><option>Birthday</option><option>Business</option><option>Other</option></select></label><label class="wide">Description<textarea id="metaDescription" maxlength="500">${esc(t.description||'')}</textarea></label><label class="wide">Tags — comma separated<input id="metaTags" value="${esc((t.tags||[]).join(', '))}"></label><div class="wide dialog-actions"><button class="primary">Save details</button></div></form>`;$('#metaCategory').value=['Wedding','Birthday','Business','Other'].includes(t.category)?t.category:'Other';$('#metaForm').onsubmit=async e=>{e.preventDefault();try{const updated=await api(`/api/templates/${t.id}`,{method:'PUT',body:JSON.stringify({name:$('#metaName').value.trim(),category:$('#metaCategory').value,description:$('#metaDescription').value.trim(),tags:$('#metaTags').value.split(',').map(x=>x.trim()).filter(Boolean)})});templates[templates.findIndex(x=>x.id===t.id)]=updated;$('#studioDialog').close();render()}catch(error){alert(error.message)}};$('#studioDialog').showModal()}
async function versions(t){try{const items=await api(`/api/templates/${t.id}/versions`);$('#studioDialogBody').innerHTML=`<h1>Version history — ${esc(t.name)}</h1><p>Restoring an older version creates a new current version, so history remains intact.</p><div>${items.map(v=>`<div class="version-row"><strong>Version ${v.version}</strong><span>${new Date(v.createdAt).toLocaleString()}</span>${v.version===(t.currentVersion||1)?'<span class="version-badge">Current</span>':`<button data-version="${v.version}">Restore</button>`}</div>`).join('')}</div>`;$('#studioDialogBody').querySelectorAll('[data-version]').forEach(b=>b.onclick=async()=>{if(!(await uiConfirm(`Restore version ${b.dataset.version} as a new current version?`,{title:'Restore template version',confirmText:'Restore'})))return;try{const updated=await api(`/api/templates/${t.id}/restore`,{method:'POST',body:JSON.stringify({version:Number(b.dataset.version)})});templates[templates.findIndex(x=>x.id===t.id)]=updated;$('#studioDialog').close();render()}catch(error){alert(error.message)}});$('#studioDialog').showModal()}catch(error){alert(error.message)}}
$('#studioClose').onclick=()=>$('#studioDialog').close();$('#refreshBtn').onclick=load;$('#studioSearch').oninput=render;$('#studioCategory').onchange=render;$('#studioFavorites').onchange=render;load();
