"""Cumulative V34-V52 schema. All migrations are additive and preserve V32 records."""
from __future__ import annotations
import json, time

SCHEMA_VERSION = 27


def _try(db, statement: str) -> None:
    try:
        db.execute(statement)
    except Exception:
        pass


def ensure_future_schema(connect) -> None:
    statements = [
        """CREATE TABLE IF NOT EXISTS future_schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at INTEGER NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}')""",
        """CREATE TABLE IF NOT EXISTS editor_workspace_profiles(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,name TEXT NOT NULL,mode TEXT NOT NULL DEFAULT 'quick',layout_json TEXT NOT NULL DEFAULT '{}',shortcuts_json TEXT NOT NULL DEFAULT '{}',is_default INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(workspace_id,user_id,name))""",
        "CREATE INDEX IF NOT EXISTS idx_editor_profiles_user ON editor_workspace_profiles(workspace_id,user_id,updated_at DESC)",
        """CREATE TABLE IF NOT EXISTS ai_routing_policies(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,providers_json TEXT NOT NULL DEFAULT '[]',model_profiles_json TEXT NOT NULL DEFAULT '{}',fallback_json TEXT NOT NULL DEFAULT '[]',budget_json TEXT NOT NULL DEFAULT '{}',evaluation_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(workspace_id,name))""",
        """CREATE TABLE IF NOT EXISTS ai_saved_workflows_v35(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,owner_id TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',prompt_template TEXT NOT NULL DEFAULT '',tool_policy_json TEXT NOT NULL DEFAULT '{}',context_policy_json TEXT NOT NULL DEFAULT '{}',confirmation_policy_json TEXT NOT NULL DEFAULT '{}',visibility TEXT NOT NULL DEFAULT 'private',version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_ai_workflows_workspace ON ai_saved_workflows_v35(workspace_id,updated_at DESC)",
        """CREATE TABLE IF NOT EXISTS ai_budget_ledger_v35(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,provider TEXT NOT NULL,model TEXT NOT NULL DEFAULT '',input_units INTEGER NOT NULL DEFAULT 0,output_units INTEGER NOT NULL DEFAULT 0,cost_micros INTEGER NOT NULL DEFAULT 0,request_count INTEGER NOT NULL DEFAULT 1,period_key TEXT NOT NULL,created_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_ai_budget_period ON ai_budget_ledger_v35(workspace_id,period_key,created_at DESC)",
        """CREATE TABLE IF NOT EXISTS marketplace_templates_v36(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,owner_id TEXT NOT NULL,title TEXT NOT NULL,slug TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'invitation',description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',visibility TEXT NOT NULL DEFAULT 'private',license_type TEXT NOT NULL DEFAULT 'free',price_minor INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'USD',current_version INTEGER NOT NULL DEFAULT 1,compatibility_json TEXT NOT NULL DEFAULT '{}',preview_json TEXT NOT NULL DEFAULT '{}',moderation_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(workspace_id,slug))""",
        "CREATE INDEX IF NOT EXISTS idx_marketplace_status ON marketplace_templates_v36(status,visibility,updated_at DESC)",
        """CREATE TABLE IF NOT EXISTS marketplace_template_versions_v36(id TEXT PRIMARY KEY,template_id TEXT NOT NULL,version INTEGER NOT NULL,package_json TEXT NOT NULL,manifest_json TEXT NOT NULL DEFAULT '{}',fingerprint TEXT NOT NULL,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(template_id,version))""",
        """CREATE TABLE IF NOT EXISTS marketplace_installations_v36(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,template_id TEXT NOT NULL,template_version INTEGER NOT NULL,installed_by TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',license_json TEXT NOT NULL DEFAULT '{}',settings_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(workspace_id,template_id))""",
        """CREATE TABLE IF NOT EXISTS enterprise_protocols_v42(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,name TEXT NOT NULL,protocol_type TEXT NOT NULL DEFAULT 'government-ceremony',classification TEXT NOT NULL DEFAULT 'internal',document_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'draft',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_enterprise_protocol_invite ON enterprise_protocols_v42(invitation_id,updated_at DESC)",
        """CREATE TABLE IF NOT EXISTS enterprise_approval_steps_v42(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,protocol_id TEXT NOT NULL DEFAULT '',step_order INTEGER NOT NULL,step_type TEXT NOT NULL,required_role TEXT NOT NULL,assignee_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',decision_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_enterprise_approval_invite ON enterprise_approval_steps_v42(invitation_id,step_order)",
        """CREATE TABLE IF NOT EXISTS enterprise_directory_entries_v42(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,entry_type TEXT NOT NULL,name TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',organization TEXT NOT NULL DEFAULT '',rank_order INTEGER NOT NULL DEFAULT 0,contact_json TEXT NOT NULL DEFAULT '{}',metadata_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS animation_projects_v44(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,page_id TEXT NOT NULL DEFAULT 'hero',name TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,timeline_json TEXT NOT NULL DEFAULT '{}',audio_json TEXT NOT NULL DEFAULT '{}',reduced_motion_json TEXT NOT NULL DEFAULT '{}',fingerprint TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_animation_project_invite ON animation_projects_v44(invitation_id,updated_at DESC)",
        """CREATE TABLE IF NOT EXISTS animation_exports_v44(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,project_id TEXT NOT NULL,job_id TEXT NOT NULL DEFAULT '',format TEXT NOT NULL,settings_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'queued',result_asset_id TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS custom_domains_v45(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,hostname TEXT NOT NULL,environment TEXT NOT NULL DEFAULT 'production',status TEXT NOT NULL DEFAULT 'pending',verification_token TEXT NOT NULL,verification_json TEXT NOT NULL DEFAULT '{}',certificate_status TEXT NOT NULL DEFAULT 'pending',redirect_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(hostname))""",
        "CREATE INDEX IF NOT EXISTS idx_custom_domains_invite ON custom_domains_v45(invitation_id,updated_at DESC)",
        """CREATE TABLE IF NOT EXISTS publication_environments_v45(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,name TEXT NOT NULL,environment_type TEXT NOT NULL,slug TEXT NOT NULL DEFAULT '',domain_id TEXT NOT NULL DEFAULT '',access_json TEXT NOT NULL DEFAULT '{}',schedule_json TEXT NOT NULL DEFAULT '{}',snapshot_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(invitation_id,name))""",
        """CREATE TABLE IF NOT EXISTS data_merge_sources_v47(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,name TEXT NOT NULL,source_type TEXT NOT NULL DEFAULT 'csv',columns_json TEXT NOT NULL DEFAULT '[]',mapping_json TEXT NOT NULL DEFAULT '{}',validation_json TEXT NOT NULL DEFAULT '{}',row_count INTEGER NOT NULL DEFAULT 0,checksum TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS data_merge_jobs_v47(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,source_id TEXT NOT NULL,platform_job_id TEXT NOT NULL DEFAULT '',mode TEXT NOT NULL DEFAULT 'preview',status TEXT NOT NULL DEFAULT 'queued',configuration_json TEXT NOT NULL DEFAULT '{}',progress_json TEXT NOT NULL DEFAULT '{}',result_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_merge_jobs_invite ON data_merge_jobs_v47(invitation_id,created_at DESC)",
        """CREATE TABLE IF NOT EXISTS generated_invitation_variants_v47(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,merge_job_id TEXT NOT NULL,row_key TEXT NOT NULL,guest_id TEXT NOT NULL DEFAULT '',variant_json TEXT NOT NULL DEFAULT '{}',public_token_hash TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(merge_job_id,row_key))""",
        """CREATE TABLE IF NOT EXISTS plugin_manifests_v48(id TEXT PRIMARY KEY,plugin_key TEXT NOT NULL,version TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',publisher TEXT NOT NULL DEFAULT '',manifest_json TEXT NOT NULL,signature TEXT NOT NULL DEFAULT '',fingerprint TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(plugin_key,version))""",
        """CREATE TABLE IF NOT EXISTS plugin_installations_v48(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,plugin_key TEXT NOT NULL,plugin_version TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'disabled',configuration_json TEXT NOT NULL DEFAULT '{}',installed_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(workspace_id,plugin_key))""",
        """CREATE TABLE IF NOT EXISTS plugin_grants_v48(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,plugin_key TEXT NOT NULL,permission TEXT NOT NULL,scope_json TEXT NOT NULL DEFAULT '{}',granted_by TEXT NOT NULL,created_at INTEGER NOT NULL,revoked_at INTEGER,UNIQUE(workspace_id,plugin_key,permission))""",
        """CREATE TABLE IF NOT EXISTS event_programs_v52(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,name TEXT NOT NULL,event_type TEXT NOT NULL DEFAULT 'ceremony',timezone TEXT NOT NULL DEFAULT 'Asia/Phnom_Penh',start_at INTEGER,end_at INTEGER,status TEXT NOT NULL DEFAULT 'planning',program_json TEXT NOT NULL DEFAULT '{}',operations_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_event_program_invite ON event_programs_v52(invitation_id,start_at)",
        """CREATE TABLE IF NOT EXISTS event_tasks_v52(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,program_id TEXT NOT NULL DEFAULT '',title TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'general',assignee_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'todo',priority TEXT NOT NULL DEFAULT 'normal',due_at INTEGER,dependencies_json TEXT NOT NULL DEFAULT '[]',details_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        "CREATE INDEX IF NOT EXISTS idx_event_tasks_invite ON event_tasks_v52(invitation_id,status,due_at)",
        """CREATE TABLE IF NOT EXISTS event_vendors_v52(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,contact_json TEXT NOT NULL DEFAULT '{}',contract_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'active',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS event_incidents_v52(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,program_id TEXT NOT NULL DEFAULT '',severity TEXT NOT NULL DEFAULT 'low',title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'open',location_json TEXT NOT NULL DEFAULT '{}',reported_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,resolved_at INTEGER)""",
        """CREATE TABLE IF NOT EXISTS event_automations_v52(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,name TEXT NOT NULL,trigger_type TEXT NOT NULL,trigger_json TEXT NOT NULL DEFAULT '{}',conditions_json TEXT NOT NULL DEFAULT '[]',actions_json TEXT NOT NULL DEFAULT '[]',enabled INTEGER NOT NULL DEFAULT 0,last_run_at INTEGER,next_run_at INTEGER,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS event_automation_runs_v52(id TEXT PRIMARY KEY,automation_id TEXT NOT NULL,workspace_id TEXT NOT NULL,invitation_id TEXT NOT NULL,status TEXT NOT NULL,trigger_json TEXT NOT NULL DEFAULT '{}',result_json TEXT NOT NULL DEFAULT '{}',started_at INTEGER NOT NULL,completed_at INTEGER)""",
    ]
    with connect() as db:
        for statement in statements:
            db.execute(statement)
        # Additive document ownership fields used by the selected milestones.
        for statement in (
            "ALTER TABLE invitations ADD COLUMN future_feature_flags_json TEXT NOT NULL DEFAULT '{}'",
            "ALTER TABLE invitations ADD COLUMN active_publication_environment TEXT NOT NULL DEFAULT 'production'",
            "ALTER TABLE publications ADD COLUMN environment_name TEXT NOT NULL DEFAULT 'production'",
            "ALTER TABLE publications ADD COLUMN custom_domain_id TEXT NOT NULL DEFAULT ''",
            "ALTER TABLE user_templates ADD COLUMN marketplace_template_id TEXT NOT NULL DEFAULT ''",
        ):
            _try(db, statement)
        now = int(time.time() * 1000)
        detail = {"documentSchema": SCHEMA_VERSION, "milestones": ["V34", "V35", "V36", "V42", "V44", "V45", "V47", "V48", "V52"]}
        db.execute(
            "INSERT INTO future_schema_migrations(version,name,applied_at,detail_json) VALUES(?,?,?,?) ON CONFLICT(version) DO UPDATE SET name=excluded.name,detail_json=excluded.detail_json",
            (SCHEMA_VERSION, "V34-V52 selected cumulative capabilities", now, json.dumps(detail, separators=(",", ":"))),
        )
