#!/usr/bin/env python3
"""Phase 2a (V54.1) — Shared photo album contract test.

End-to-end HTTP test: host publishes invitation, guest uploads a photo via
multipart, photo enters pending status, host moderates (approves), guest
sees the approved photo, host hides the photo, guest no longer sees it,
uploader can delete their own photo.
"""
from __future__ import annotations
import json
import urllib.request
import urllib.error
from http.cookiejar import CookieJar
from pathlib import Path

from v14_test_utils import app_server

ROOT = Path(__file__).resolve().parents[1]


# A valid 1x1 transparent PNG (generated by Pillow so PIL.verify passes).
PNG_BYTES = bytes.fromhex(
    '89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489'
    '0000000d49444154789c63f8cfc0c00000040101004706cade0000000049454e44'
    'ae426082'
)


class Client:
    def __init__(self, base):
        self.base = base
        self.jar = CookieJar()
        self.opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(self.jar))
        self.token = ''

    def request(self, path, method='GET', body=None, expected=200, headers=None):
        payload = None if body is None else json.dumps(body).encode('utf-8')
        hdr = {'Accept': 'application/json', **(headers or {})}
        if payload is not None: hdr['Content-Type'] = 'application/json'
        if self.token: hdr['Authorization'] = f'Bearer {self.token}'
        req = urllib.request.Request(self.base + path, data=payload, method=method, headers=hdr)
        try:
            with self.opener.open(req, timeout=15) as response:
                status = response.status; raw = response.read()
        except urllib.error.HTTPError as exc:
            status = exc.code; raw = exc.read()
        if status != expected:
            raise AssertionError(f'{method} {path}: expected {expected}, got {status}: {raw[:500]!r}')
        return json.loads(raw or b'{}')

    def upload_multipart(self, path, file_bytes, filename, mime, fields=None, expected=201):
        boundary = '----p2aalbum0boundary0' + '0' * 8
        parts = []
        if fields:
            for name, value in fields.items():
                parts.append(f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"\r\n\r\n{value}\r\n'.encode('utf-8'))
        parts.append(f'--{boundary}\r\nContent-Disposition: form-data; name="file"; filename="{filename}"\r\nContent-Type: {mime}\r\n\r\n'.encode('utf-8'))
        parts.append(file_bytes)
        parts.append(f'\r\n--{boundary}--\r\n'.encode('utf-8'))
        body = b''.join(parts)
        hdr = {'Content-Type': f'multipart/form-data; boundary={boundary}', 'Content-Length': str(len(body))}
        if self.token: hdr['Authorization'] = f'Bearer {self.token}'
        req = urllib.request.Request(self.base + path, data=body, method='POST', headers=hdr)
        try:
            with self.opener.open(req, timeout=15) as response:
                status = response.status; raw = response.read()
        except urllib.error.HTTPError as exc:
            status = exc.code; raw = exc.read()
        if status != expected:
            raise AssertionError(f'POST {path}: expected {expected}, got {status}: {raw[:500]!r}')
        return json.loads(raw or b'{}')


def run():
    with app_server({'EINVITE_REQUIRE_EMAIL_VERIFICATION': '0',
                     'EINVITE_ALLOW_NO_SCANNER': '1',
                     'EINVITE_TEST_SCANNER_EICAR': '1'}) as (_process, base, _data):
        client = Client(base)
        registered = client.request('/api/auth/register', 'POST',
                                     {'email': 'p2a-album@example.com', 'password': 'strong-password-123'}, 201)
        client.token = registered.get('token', '')

        doc = {'schemaVersion': 13, 'eventType': 'Wedding',
               'fields': {'names': 'Album Couple', 'date': '2027-05-14', 'venue': 'Album Hall'},
               'objects': {}, 'designPages': [], 'sectionOrder': [],
               'settings': {'rsvpEnabled': False, 'wishesEnabled': False}}
        invitation = client.request('/api/invitations', 'POST', {'slug': 'p2a-album-test', 'document': doc}, 201)
        invite_id = invitation['id']
        client.request(f'/api/invitations/{invite_id}/publish', 'POST', {'document': doc}, 201)

        # Guest uploads a photo (no auth — published invitation).
        uploaded = client.upload_multipart(f'/api/invitations/{invite_id}/album',
                                            PNG_BYTES, 'test.png', 'image/png',
                                            fields={'caption': 'Test photo'})
        assert uploaded['id'], 'photo id missing'
        assert uploaded['status'] == 'pending', f'expected pending, got {uploaded["status"]}'

        # Guest lists album: should see no photos (only approved).
        # Use an unauthenticated client to simulate a guest.
        guest_client = Client(base); guest_client.token = ''
        listing = guest_client.request(f'/api/invitations/{invite_id}/album')
        assert len(listing['photos']) == 0, f'guest should not see pending photos, got: {listing}'

        # Host moderates: approve the photo.
        moderated = client.request(f'/api/invitations/{invite_id}/album/{uploaded["id"]}/moderate', 'POST',
                                    {'status': 'approved'}, 200)
        assert moderated['status'] == 'approved'

        # Guest now sees the approved photo.
        listing = guest_client.request(f'/api/invitations/{invite_id}/album')
        assert len(listing['photos']) == 1, f'guest should see 1 approved photo, got: {len(listing["photos"])}'
        assert listing['photos'][0]['status'] == 'approved'
        assert listing['photos'][0]['caption'] == 'Test photo'

        # Host hides the photo.
        client.request(f'/api/invitations/{invite_id}/album/{uploaded["id"]}/moderate', 'POST',
                        {'status': 'hidden'}, 200)
        listing = guest_client.request(f'/api/invitations/{invite_id}/album')
        assert len(listing['photos']) == 0, 'hidden photo should not appear for guests'

        # Host sees all statuses.
        host_listing = client.request(f'/api/invitations/{invite_id}/album',
                                       headers={'Authorization': f'Bearer {client.token}'})
        assert len(host_listing['photos']) == 1
        assert host_listing['photos'][0]['status'] == 'hidden'

        # Reject non-image upload.
        try:
            guest_client.upload_multipart(f'/api/invitations/{invite_id}/album',
                                    b'not an image', 'evil.txt', 'text/plain',
                                    fields={'caption': 'bad'}, expected=400)
        except AssertionError as exc:
            raise AssertionError(f'Expected 400 for non-image upload, got: {exc}')

        # V54.4 — MalwareDetected rejection. Upload the EICAR test signature
        # (declared as image/png so it passes the MIME allow-list and reaches
        # the malware-scanner gate). The dev-only test-mode hook recognises
        # the EICAR signature when EINVITE_TEST_SCANNER_EICAR=1 AND
        # EINVITE_ALLOW_NO_SCANNER=1, returning HTTP 422 with
        # code=malware_detected. This proves the upload path enforces the
        # scan BEFORE bytes reach ObjectStorage, without requiring a running
        # ClamAV daemon in CI.
        eicar_bytes = b'X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'
        malware_rejected = False
        try:
            guest_client.upload_multipart(f'/api/invitations/{invite_id}/album',
                                          eicar_bytes, 'eicar.png', 'image/png',
                                          fields={'caption': 'eicar'},
                                          expected=422)
            malware_rejected = True
        except AssertionError as exc:
            raise AssertionError(f'Expected 422 for EICAR upload, got: {exc}')
        assert malware_rejected, 'EICAR upload should have been rejected with HTTP 422'

        # Delete the uploaded photo (host).
        deleted = client.request(f'/api/invitations/{invite_id}/album/{uploaded["id"]}', 'DELETE', expected=200)
        assert deleted['deleted'] is True

        print('P2A_ALBUM_TEST_PASSED')


if __name__ == '__main__':
    run()
