#!/usr/bin/env python3
from __future__ import annotations
import importlib.util
from pathlib import Path
from browser_runtime import launch_chromium,skipped
ROOT=Path(__file__).resolve().parents[1]
def build():
 spec=importlib.util.spec_from_file_location('inline_v212',ROOT/'tests'/'inline_editor_runtime_test.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod);return mod.build_inline_editor()
def main():
 try:from playwright.sync_api import sync_playwright
 except Exception as exc:return skipped('V21_2_ACCESSIBLE_EDITING',exc)
 with sync_playwright() as p:
  try:browser=launch_chromium(p)
  except Exception as exc:return skipped('V21_2_ACCESSIBLE_EDITING',exc)
  page=browser.new_page(viewport={'width':1440,'height':1000});page.set_default_timeout(50000);errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
  page.set_content(build(),wait_until='load',timeout=60000);page.wait_for_timeout(1800)
  if page.locator('#finalTourDismiss').count() and page.locator('#finalTourDismiss').is_visible():page.locator('#finalTourDismiss').click()
  page.wait_for_function('()=>window.RichTextEditing&&window.RichTextRenderer&&window.EInviteEditorBridge')
  page.evaluate("""()=>{EInviteEditorBridge.transact('Create rich editing fixture',doc=>{const base=structuredClone(doc.objects.title);doc.objects['rich-edit']={...base,layerName:'Rich editing test',left:'8%',top:'15%',width:'80%',height:'260px',zIndex:99,richTextModelVersion:1,richText:{version:1,entities:{},paragraphs:[{id:'p-main',paragraphStyleId:'body',locale:'en',direction:'ltr',overrides:{},list:{type:'none',level:0,start:1,marker:'disc'},tabStops:[],runs:[{id:'r-main',text:'Hello ',locale:'en',marks:{}},{id:'r-kh',text:'ក្ខ',locale:'km',marks:{}}]}]}};doc.objects['rich-edit'].html=RichTextDocumentModel.exportLegacyHtml(doc.objects['rich-edit'].richText);doc.objects['rich-edit'].text=RichTextDocumentModel.exportPlainText(doc.objects['rich-edit'].richText)});EInviteEditorBridge.select(['rich-edit']);window.__rtCommands=[];window.addEventListener('einvite:editor-command',e=>window.__rtCommands.push(e.detail))}""");page.wait_for_timeout(350)
  # Toolbar semantics and controlled root.
  ui=page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content');return{controlled:c.dataset.richTextControlled,role:c.getAttribute('role'),multi:c.getAttribute('aria-multiline'),tools:!!document.querySelector('[data-rich-text-tools]'),names:[...document.querySelectorAll('[data-rich-text-tools] button')].map(x=>x.getAttribute('aria-label'))}}""")
  assert ui['controlled']=='true' and ui['role']=='textbox' and ui['multi']=='true' and ui['tools'] and {'Underline','Strikethrough','Bulleted list','Numbered list','Create or edit link'}<=set(ui['names']),ui
  # Type three characters; one coalesced history command.
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),m=state.objects['rich-edit'].richText,p=m.paragraphs[0],r=p.runs.at(-1),pos={paragraphId:p.id,runId:r.id,offset:r.text.length};c.focus();RichTextEditing.restore(c,{anchor:pos,focus:pos})}""");page.wait_for_timeout(80)
  for ch in 'ABC': page.evaluate("ch=>document.querySelector('.object[data-id=rich-edit] .content').dispatchEvent(new InputEvent('beforeinput',{inputType:'insertText',data:ch,bubbles:true,cancelable:true}))",ch)
  page.evaluate("()=>RichTextEditing.flush()");page.wait_for_timeout(250)
  typed=page.evaluate("""()=>({plain:RichTextDocumentModel.exportPlainText(state.objects['rich-edit'].richText),commands:__rtCommands.map(x=>({label:x.label,coalesced:x.coalesced})),historySelection:state.editorModel.richTextSelection})""")
  assert typed['plain']=='Hello ក្ខABC' and len([x for x in typed['commands'] if x['label']=='Type text'])==1 and typed['commands'][-1]['coalesced'] is True,typed
  # Undo/redo restores content and a valid caret selection.
  page.evaluate("()=>EInviteEditorBridge.undo()");page.wait_for_timeout(220);assert page.evaluate("()=>RichTextDocumentModel.exportPlainText(state.objects['rich-edit'].richText)")=='Hello ក្ខ'
  page.evaluate("()=>EInviteEditorBridge.redo()");page.wait_for_timeout(220);redo=page.evaluate("""()=>({plain:RichTextDocumentModel.exportPlainText(state.objects['rich-edit'].richText),sel:state.editorModel.richTextSelection,dom:!!getSelection()?.anchorNode?.parentElement?.closest?.('.content[data-rich-text-controlled=true]')})""");assert redo['plain']=='Hello ក្ខABC' and redo['sel']['objectId']=='rich-edit' and redo['dom'],redo
  # Replace with a short fixture and commit one IME composition.
  page.evaluate("""()=>EInviteEditorBridge.transact('Reset rich fixture',doc=>{const o=doc.objects['rich-edit'];o.richText={version:1,entities:{},paragraphs:[{id:'p-ime',paragraphStyleId:'body',locale:'en',direction:'ltr',overrides:{},list:{type:'none',level:0,start:1,marker:'disc'},tabStops:[],runs:[{id:'r-ime',text:'X',locale:'en',marks:{}}]}]};o.html=RichTextDocumentModel.exportLegacyHtml(o.richText);o.text='X'})""");page.wait_for_timeout(180)
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),pos={paragraphId:'p-ime',runId:'r-ime',offset:1};c.focus();RichTextEditing.restore(c,{anchor:pos,focus:pos})}""");page.wait_for_timeout(100)
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content');c.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''}));c.dispatchEvent(new InputEvent('beforeinput',{inputType:'insertCompositionText',data:'ក្ខ',bubbles:true,cancelable:true}));c.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'ក្ខ'}))}""");page.wait_for_timeout(250)
  ime=page.evaluate("""()=>({plain:RichTextDocumentModel.exportPlainText(state.objects['rich-edit'].richText),ime:__rtCommands.filter(x=>x.label==='IME composition').length})""");assert ime=={'plain':'Xក្ខ','ime':1},ime
  # Khmer coeng cluster must delete as one grapheme.
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),m=state.objects['rich-edit'].richText,p=m.paragraphs[0],r=p.runs.at(-1),pos={paragraphId:p.id,runId:r.id,offset:r.text.length};c.focus();RichTextEditing.restore(c,{anchor:pos,focus:pos})}""");page.wait_for_timeout(80);page.evaluate("()=>document.querySelector('.object[data-id=rich-edit] .content').dispatchEvent(new InputEvent('beforeinput',{inputType:'deleteContentBackward',bubbles:true,cancelable:true}))");page.wait_for_timeout(180);assert page.evaluate("()=>RichTextDocumentModel.exportPlainText(state.objects['rich-edit'].richText)")=='X'
  # Paragraph split and join.
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),p=state.objects['rich-edit'].richText.paragraphs[0],r=p.runs[0],pos={paragraphId:p.id,runId:r.id,offset:1};c.focus();RichTextEditing.restore(c,{anchor:pos,focus:pos});c.dispatchEvent(new InputEvent('beforeinput',{inputType:'insertParagraph',bubbles:true,cancelable:true}))}""");page.wait_for_timeout(180);assert page.evaluate("()=>state.objects['rich-edit'].richText.paragraphs.length")==2
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),p=state.objects['rich-edit'].richText.paragraphs[1],r=p.runs[0],pos={paragraphId:p.id,runId:r.id,offset:0};c.focus();RichTextEditing.restore(c,{anchor:pos,focus:pos});c.dispatchEvent(new InputEvent('beforeinput',{inputType:'deleteContentBackward',bubbles:true,cancelable:true}))}""");page.wait_for_timeout(180);assert page.evaluate("()=>state.objects['rich-edit'].richText.paragraphs.length")==1
  # Ranged mark, list, indent/outdent, and tab insertion.
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),p=state.objects['rich-edit'].richText.paragraphs[0],r=p.runs[0];RichTextEditing.restore(c,{anchor:{paragraphId:p.id,runId:r.id,offset:0},focus:{paragraphId:p.id,runId:r.id,offset:r.text.length}});c.dispatchEvent(new InputEvent('beforeinput',{inputType:'formatBold',bubbles:true,cancelable:true}))}""");page.wait_for_timeout(160);assert page.evaluate("()=>state.objects['rich-edit'].richText.paragraphs[0].runs.some(r=>r.marks.strong)")
  page.evaluate("""()=>document.querySelector('.object[data-id=rich-edit] .content').dispatchEvent(new KeyboardEvent('keydown',{key:'8',ctrlKey:true,shiftKey:true,bubbles:true,cancelable:true}))""");page.wait_for_timeout(120)
  page.evaluate("""()=>document.querySelector('.object[data-id=rich-edit] .content').dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}))""");page.wait_for_timeout(120)
  page.evaluate("""()=>document.querySelector('.object[data-id=rich-edit] .content').dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}))""");page.wait_for_timeout(160);lst=page.evaluate("()=>state.objects['rich-edit'].richText.paragraphs[0].list");assert lst['type']=='bullet' and lst['level']==0,lst
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),p=state.objects['rich-edit'].richText.paragraphs[0];p.list={type:'none',level:0,start:1,marker:'disc'};apply();const r=state.objects['rich-edit'].richText.paragraphs[0].runs.at(-1),pos={paragraphId:p.id,runId:r.id,offset:r.text.length};RichTextEditing.restore(c,{anchor:pos,focus:pos});c.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}))}""");page.wait_for_timeout(160);assert '\t' in page.evaluate("()=>RichTextDocumentModel.exportPlainText(state.objects['rich-edit'].richText)")
  # Safe link through actual toolbar, with an accessible link name.
  page.evaluate("""()=>{const values=['https://example.com/path','Official details'];window.prompt=()=>values.shift()||'';const c=document.querySelector('.object[data-id=rich-edit] .content'),p=state.objects['rich-edit'].richText.paragraphs[0],r=p.runs[0];RichTextEditing.restore(c,{anchor:{paragraphId:p.id,runId:r.id,offset:0},focus:{paragraphId:p.id,runId:r.id,offset:1}})}""");page.wait_for_timeout(80);page.get_by_role('button',name='Create or edit link').click();page.wait_for_timeout(180)
  link=page.evaluate("""()=>{const o=state.objects['rich-edit'],entity=Object.values(o.richText.entities)[0],a=document.querySelector('.object[data-id=rich-edit] a.rt-link');return{url:entity?.url,title:entity?.title,name:a?.getAttribute('aria-label')}}""");assert link=={'url':'https://example.com/path','title':'Official details','name':'Official details'},link
  # Paste is plain-text only; hostile markup is never interpreted.
  page.evaluate("""()=>{const c=document.querySelector('.object[data-id=rich-edit] .content'),dt=new DataTransfer();dt.setData('text/plain','<img src=x onerror=alert(1)>SAFE');c.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true,cancelable:true}))}""");page.wait_for_timeout(180);paste=page.evaluate("""()=>({plain:RichTextDocumentModel.exportPlainText(state.objects['rich-edit'].richText),images:document.querySelectorAll('.object[data-id=rich-edit] .content img').length,scripts:document.querySelectorAll('.object[data-id=rich-edit] .content script').length})""");assert 'SAFE' in paste['plain'] and paste['images']==0 and paste['scripts']==0,paste
  assert not errors,errors;browser.close()
 print('V21_2_ACCESSIBLE_EDITING_TEST_PASSED');return 0
if __name__=='__main__':raise SystemExit(main())
