const $=s=>document.querySelector(s);localStorage.removeItem('sovan-auth-token');let state={users:[],templates:[],invitations:[],ai:{providers:[],modelRoles:{},modelDirectory:{}},tab:'users'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
function matches(...values){const q=$('#adminSearch').value.trim().toLowerCase();return !q||values.join(' ').toLowerCase().includes(q)}
function renderUsers(){const items=state.users.filter(u=>matches(u.email,u.role,u.plan,u.uploadEnabled?'uploads allowed':'uploads disabled'));$('#usersPanel').innerHTML=items.map(u=>`<article class="admin-row" data-user="${esc(u.id)}"><div><h3>${esc(u.email)}</h3><small>${new Date(u.createdAt).toLocaleDateString()}</small></div><span>${u.invitationCount} invitations</span><span>${u.templateCount} templates</span><select data-role title="Account role"><option value="customer" ${u.role==='customer'?'selected':''}>Customer</option><option value="designer" ${u.role==='designer'?'selected':''}>Designer</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrator</option></select><select data-plan title="Account plan"><option value="free" ${u.plan==='free'?'selected':''}>Free</option><option value="creator" ${u.plan==='creator'?'selected':''}>Creator</option><option value="studio" ${u.plan==='studio'?'selected':''}>Studio</option></select><label class="admin-upload-toggle"><input type="checkbox" data-upload-enabled ${u.uploadEnabled?'checked':''}> Allow uploads</label><div><button data-save-role>Save role</button> <button data-save-plan>Save plan</button> <button data-save-uploads>Save uploads</button></div></article>`).join('')||'<p>No users found.</p>';document.querySelectorAll('[data-save-role]').forEach(b=>b.onclick=()=>saveRole(b.closest('[data-user]')));document.querySelectorAll('[data-save-plan]').forEach(b=>b.onclick=()=>savePlan(b.closest('[data-user]')));document.querySelectorAll('[data-save-uploads]').forEach(b=>b.onclick=()=>saveUploads(b.closest('[data-user]')))}
function renderTemplates(){const items=state.templates.filter(t=>matches(t.name,t.category,t.ownerEmail,t.visibility));$('#templatesPanel').innerHTML=items.map(t=>`<article class="admin-row" data-template="${esc(t.id)}"><div><h3>${esc(t.name)}</h3><small>${esc(t.ownerEmail)} · v${t.currentVersion}</small></div><span>${esc(t.category)}</span><span>${t.visibility==='public'?'Marketplace':'Private'}</span><select data-visibility><option value="private" ${t.visibility!=='public'?'selected':''}>Private</option><option value="public" ${t.visibility==='public'?'selected':''}>Marketplace</option></select><button data-save-template>Save</button></article>`).join('')||'<p>No templates found.</p>';document.querySelectorAll('[data-save-template]').forEach(b=>b.onclick=()=>saveTemplate(b.closest('[data-template]')))}
function renderInvitations(){const items=state.invitations.filter(i=>matches(i.title,i.slug,i.ownerEmail,i.accessMode));$('#invitationsPanel').innerHTML=items.map(i=>`<article class="admin-row" data-invite="${esc(i.id)}"><div><h3>${esc(i.title)}</h3><small>${esc(i.ownerEmail||'Unknown owner')} · /i/${esc(i.slug)}</small></div><span>${i.views} views</span><span>${esc(i.accessMode)}</span><span>${i.published?'Published':'Offline'}</span><button data-toggle-published>${i.published?'Unpublish':'Republish'}</button></article>`).join('')||'<p>No invitations found.</p>';document.querySelectorAll('[data-toggle-published]').forEach(b=>b.onclick=()=>toggleInvitation(b.closest('[data-invite]')))}
function renderAI(){
 const host=$('#aiPanel'),ai=state.ai||{},providers=(ai.providers||[]).filter(p=>matches(p.label,p.id,p.kind,p.endpointLabel,p.healthy?'healthy':'unavailable'));
 const roles=Object.entries(ai.modelRoles||{}).map(([role,value])=>`<span><b>${esc(role)}</b>: ${esc(value.selection||'not selected')} · ${value.available?'available':'unavailable'}</span>`).join(' · ');
 const directory=ai.modelDirectory||{},directoryText=!directory.configured?'not configured':directory.available?`${(directory.files||[]).length} compatible file(s) discovered; runtime registration still required.`:'configured but unavailable';
 const cards=providers.map(provider=>{const modelLines=(provider.models||[]).slice(0,30).map(model=>{const context=model.contextLength?` · context ${esc(model.contextLength)}`:'';return `<small><b>${esc(model.name||model.id)}</b> · ${esc(model.type||'text')} · tools ${model.toolCalling?'yes':'no'} · vision ${model.vision?'yes':'no'} · structured ${model.structuredOutput?'yes':'no'}${context}</small>`}).join('<br>')||'<small>No models discovered.</small>';return `<article class="admin-row"><div><h3>${esc(provider.label||provider.id)}</h3><small>${esc(provider.endpointLabel||'Server configured')} · ${esc(provider.kind||'local')}</small></div><span>${provider.healthy?'Healthy':'Unavailable'}</span><span>${(provider.models||[]).length} models</span><span>Checked ${provider.checkedAt?new Date(provider.checkedAt).toLocaleString():'—'}</span><div>${modelLines}</div></article>`}).join('');
 host.innerHTML=`<div class="provider-note"><b>Model routing</b><p>${roles||'No local model roles selected.'}</p><p>Local model directory: ${directoryText}</p></div>${cards||'<p>No local AI providers are enabled. Configure them with server environment variables; browser users cannot set arbitrary endpoints.</p>'}`;
}
function render(){renderUsers();renderTemplates();renderInvitations();renderAI()}
async function saveRole(row){try{const id=row.dataset.user,role=row.querySelector('[data-role]').value;await api(`/api/admin/users/${id}/role`,{method:'PUT',body:JSON.stringify({role})});const item=state.users.find(x=>x.id===id);if(item)item.role=role;renderUsers()}catch(e){alert(e.message)}}
async function savePlan(row){try{const id=row.dataset.user,plan=row.querySelector('[data-plan]').value;await api(`/api/admin/users/${id}/plan`,{method:'PUT',body:JSON.stringify({plan})});const item=state.users.find(x=>x.id===id);if(item)item.plan=plan;renderUsers()}catch(e){alert(e.message)}}
async function saveUploads(row){try{const id=row.dataset.user,enabled=row.querySelector('[data-upload-enabled]').checked;const result=await api(`/api/admin/users/${id}/uploads`,{method:'PUT',body:JSON.stringify({enabled})});const item=state.users.find(x=>x.id===id);if(item)item.uploadEnabled=result.uploadEnabled;renderUsers()}catch(e){alert(e.message)}}
async function saveTemplate(row){try{const id=row.dataset.template,visibility=row.querySelector('[data-visibility]').value;await api(`/api/admin/templates/${id}/visibility`,{method:'PUT',body:JSON.stringify({visibility})});const item=state.templates.find(x=>x.id===id);if(item)item.visibility=visibility;renderTemplates()}catch(e){alert(e.message)}}
async function toggleInvitation(row){try{const id=row.dataset.invite,item=state.invitations.find(x=>x.id===id),published=!item.published;await api(`/api/admin/invitations/${id}/published`,{method:'PUT',body:JSON.stringify({published})});item.published=published;renderInvitations()}catch(e){alert(e.message)}}
document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.adminTab;document.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.admin-panel').forEach(x=>x.classList.remove('active'));$(`#${state.tab}Panel`).classList.add('active')});$('#adminSearch').oninput=render;
async function init(){try{const me=await api('/api/auth/me');if(me.user?.role!=='admin')throw Error('Administrator access required');const [overview,users,templates,invitations,ai]=await Promise.all([api('/api/admin/overview'),api('/api/admin/users'),api('/api/admin/templates'),api('/api/admin/invitations'),api('/api/admin/ai/providers')]);state={...state,users,templates,invitations,ai};$('#adminMetrics').innerHTML=Object.entries(overview).map(([key,value])=>`<div class="admin-metric"><strong>${value}</strong>${esc(key.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()))}</div>`).join('');render()}catch(e){document.querySelector('.admin-page').innerHTML=`<h1>Administration unavailable</h1><p>${esc(e.message)}</p><a href="dashboard.html" class="button-link">Back to dashboard</a>`}}
init();
