(()=>{'use strict';
const $=s=>document.querySelector(s),inviteId=window.EInviteContext?.getInvitationId({allowRemembered:false})||window.EInviteContext?.getInvitationId()||'',queueKey=`einvite-checkin-queue:${inviteId}`;let guests=[],invitation=null,stream=null,scanTimer=null;
const api=async(path,options={})=>{const r=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const queue=()=>{try{return JSON.parse(localStorage.getItem(queueKey)||'[]')}catch{return[]}},saveQueue=q=>localStorage.setItem(queueKey,JSON.stringify(q));
function setNetwork(){const online=navigator.onLine;$('#networkState').textContent=online?'Online':'Offline';$('#networkState').classList.toggle('offline',!online);renderQueue()}
function renderQueue(){const q=queue(),el=$('#pendingQueue');el.hidden=!q.length;el.textContent=q.length?`${q.length} check-in change${q.length===1?'':'s'} waiting to sync when the connection returns.`:''}
function render(){const q=$('#guestSearch').value.trim().toLowerCase(),filtered=guests.filter(g=>`${g.name} ${g.phone||''} ${g.group_name||''} ${g.table_name||''}`.toLowerCase().includes(q)),checked=guests.filter(g=>g.checked_in).length;$('#checkinSummary').textContent=`${checked} of ${guests.length} guests checked in`;$('#checkinStats').innerHTML=`<span class="checkin-stat"><strong>${checked}</strong> in</span><span class="checkin-stat"><strong>${guests.length-checked}</strong> remaining</span>`;$('#checkinList').innerHTML=filtered.map(g=>`<article class="checkin-person ${g.checked_in?'checked':''}" data-guest-id="${esc(g.id)}"><div><strong>${esc(g.name)}</strong><small>${[g.group_name,g.table_name&&`Table ${g.table_name}`,g.seat_label&&`Seat ${g.seat_label}`,g.phone].filter(Boolean).map(esc).join(' · ')}</small></div><button data-check-id="${esc(g.id)}" class="${g.checked_in?'':'primary'}">${g.checked_in?'Undo check-in':'Check in'}</button></article>`).join('')||'<p>No matching guests.</p>';document.querySelectorAll('[data-check-id]').forEach(b=>b.onclick=()=>toggle(b.dataset.checkId))}
async function load(){if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable()){window.EInviteBackend.message($('#checkinList'),'Guest check-in synchronization requires the full application server.');$('#scanQrBtn').disabled=true;return}try{invitation=await api(`/api/invitations/${encodeURIComponent(inviteId)}`);guests=await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests`);$('#eventName').textContent=invitation.document?.fields?.names||'Guest check-in';$('#backToGuests').href=window.EInviteContext.route(inviteId,'guests');render();await flushQueue()}catch(e){$('#checkinList').innerHTML=`<p>Could not load this guest list: ${esc(e.message)}</p>`}}
async function toggle(id,explicit){const g=guests.find(x=>x.id===id);if(!g)return;const checked=explicit??!g.checked_in;g.checked_in=checked;g.checked_in_at=checked?Date.now():null;render();if(!navigator.onLine){const q=queue().filter(x=>x.guestId!==id);q.push({guestId:id,checkedIn:checked,createdAt:Date.now()});saveQueue(q);renderQueue();return}try{const result=await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${encodeURIComponent(id)}/check-in`,{method:'PUT',body:JSON.stringify({checkedIn:checked})});if(result.alreadyCheckedIn){const notice=$('#checkinNotice');notice.textContent=`${g.name} was already checked in.`;setTimeout(()=>{if(notice.textContent.includes(g.name))notice.textContent=''},3500)}}catch(e){const q=queue().filter(x=>x.guestId!==id);q.push({guestId:id,checkedIn:checked,createdAt:Date.now()});saveQueue(q);renderQueue()}}
async function flushQueue(){if(!navigator.onLine)return;let q=queue(),remaining=[];for(const item of q){try{await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${encodeURIComponent(item.guestId)}/check-in`,{method:'PUT',body:JSON.stringify({checkedIn:item.checkedIn})})}catch{remaining.push(item)}}saveQueue(remaining);renderQueue();if(q.length&&!remaining.length){guests=await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests`);render()}}
function guestFromScanned(value){let text=String(value||'');try{const u=new URL(text,location.origin),token=u.searchParams.get('g')||u.searchParams.get('guest');if(token)return guests.find(g=>g.token===token)}catch{}return guests.find(g=>g.id===text)}
async function openScanner(){if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){alert('Camera QR scanning is not supported in this browser. Use guest search instead.');return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('#scannerVideo').srcObject=stream;await $('#scannerVideo').play();$('#scannerDialog').showModal();const detector=new BarcodeDetector({formats:['qr_code']});const tick=async()=>{if(!stream)return;try{const codes=await detector.detect($('#scannerVideo'));if(codes[0]){const guest=guestFromScanned(codes[0].rawValue);if(guest){await toggle(guest.id,true);closeScanner();document.querySelector(`[data-guest-id="${CSS.escape(guest.id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});return}$('#scannerStatus').textContent='This QR code does not belong to a guest in this invitation.'}}catch{}scanTimer=setTimeout(tick,260)};tick()}catch(e){alert(`Camera could not be opened: ${e.message}`)}}
function closeScanner(){clearTimeout(scanTimer);scanTimer=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('#scannerVideo').srcObject=null;$('#scannerDialog').close()}
$('#guestSearch').oninput=render;$('#scanQrBtn').onclick=openScanner;$('#closeScanner').onclick=closeScanner;$('#scannerDialog').addEventListener('close',()=>{if(stream)closeScanner()});window.addEventListener('online',()=>{setNetwork();flushQueue()});window.addEventListener('offline',setNetwork);setNetwork();load();if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});
})();
