(()=>{
'use strict';
if(window.EInviteCollaborationCenter?.version>=24.5)return;
const registry=window.EInviteCommandRegistry,review=window.EInviteReviewWorkflow,bridge=window.EInviteEditorBridge;
if(!registry||!review||!bridge)return;
if(!document.querySelector('link[data-v24-collaboration]')){const link=document.createElement('link');link.rel='stylesheet';link.href='collaboration-v24.css';link.dataset.v24Collaboration='1';document.head.append(link)}
const STORE_KEY='einvite-v24-review-assignments',MAX_ASSIGNMENTS=500,cleanup=[],unregister=[];
let dialog=null,opener=null,activeTab='summary',query='',remoteAssignments={},remoteLoaded=false;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=(v,max=200)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max);
const invitationId=()=>window.serverInvite?.id||window.EInviteContext?.getInvitationId?.({allowRemembered:false})||window.EInviteContext?.getInvitationId?.()||'local-draft';
function on(t,type,fn,opt){t?.addEventListener?.(type,fn,opt);cleanup.push(()=>t?.removeEventListener?.(type,fn,opt))}
function readAll(){try{const data=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');return data&&typeof data==='object'?data:{}}catch{return{}}}
function writeAll(data){try{localStorage.setItem(STORE_KEY,JSON.stringify(data));return true}catch{return false}}
function localAssignments(){const all=readAll();return all[invitationId()]&&typeof all[invitationId()]==='object'?all[invitationId()]:{}}
function assignmentMap(){return remoteLoaded?remoteAssignments:localAssignments()}
function normalizeTask(row={}){return{assignee:String(row.assignee_email||row.assignee||''),assigneeId:String(row.assignee_id||''),dueDate:String(row.due_date||row.dueDate||'').slice(0,10),priority:['low','normal','high'].includes(row.priority)?row.priority:'normal',status:['open','in-progress','blocked','resolved'].includes(row.status)?row.status:'open',updatedAt:Number(row.updated_at||row.updatedAt||0)}}
async function taskApi(path,options={}){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||`Request failed (${response.status})`);return data}
async function loadAssignments(){const id=invitationId();if(!id||id==='local-draft'){remoteLoaded=false;return assignmentMap()}try{const rows=await taskApi(`/api/invitations/${encodeURIComponent(id)}/review-tasks`);remoteAssignments=Object.fromEntries((Array.isArray(rows)?rows:[]).map(row=>[String(row.comment_id||row.commentId),normalizeTask(row)]));remoteLoaded=true;const all=readAll();all[id]=remoteAssignments;writeAll(all);return remoteAssignments}catch{remoteLoaded=false;return assignmentMap()}}
function saveAssignments(map){const all=readAll(),entries=Object.entries(map).sort((a,b)=>Number(b[1]?.updatedAt||0)-Number(a[1]?.updatedAt||0)).slice(0,MAX_ASSIGNMENTS);all[invitationId()]=Object.fromEntries(entries);if(!writeAll(all))throw Error('Browser storage is unavailable');window.dispatchEvent(new CustomEvent('einvite:review-assignments-changed'));return all[invitationId()]}
function rootComments(){return review.comments.filter(c=>!c.parentId)}
function assignmentFor(id){return assignmentMap()[id]||{}}
async function updateAssignment(id,patch){const map={...assignmentMap()},current=map[id]||{};map[id]={...current,...patch,updatedAt:Date.now()};if(!map[id].assignee&&!map[id].dueDate&&(map[id].priority||'normal')==='normal'&&(map[id].status||'open')==='open')delete map[id];remoteAssignments=map;saveAssignments(map);render();const invite=invitationId();if(invite&&invite!=='local-draft'){try{const row=await taskApi(`/api/invitations/${encodeURIComponent(invite)}/review-tasks/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({assignee:map[id]?.assignee||'',dueDate:map[id]?.dueDate||'',priority:map[id]?.priority||'normal',status:map[id]?.status||'open'})});if(row){remoteAssignments={...remoteAssignments,[id]:normalizeTask(row)};remoteLoaded=true;saveAssignments(remoteAssignments);render()}}catch(error){window.EInviteFeedback?.toast?.(`Task saved locally: ${error.message}`)}}return assignmentMap()[id]||null}
function reviewers(){return review.context?.reviewers||[]}
function pageName(id){if(!id||id==='hero')return'Hero';const doc=bridge.getState?.()||{},page=(doc.designPages||[]).find(p=>String(p.id)===String(id).replace(/^page:/,''));return page?.name||page?.title||String(id).replace(/^page:/,'Page ')}
function threadStats(){const roots=rootComments(),map=assignmentMap(),now=Date.now();return{total:roots.length,open:roots.filter(c=>!c.resolved).length,resolved:roots.filter(c=>c.resolved).length,assigned:roots.filter(c=>map[c.id]?.assignee).length,overdue:roots.filter(c=>!c.resolved&&map[c.id]?.dueDate&&new Date(map[c.id].dueDate).getTime()<now).length,high:roots.filter(c=>!c.resolved&&map[c.id]?.priority==='high').length}}
function pageSummary(){const groups=new Map;for(const comment of rootComments()){const key=comment.pageId||'hero',row=groups.get(key)||{id:key,open:0,resolved:0,total:0};row.total++;comment.resolved?row.resolved++:row.open++;groups.set(key,row)}return[...groups.values()].sort((a,b)=>b.open-a.open||pageName(a.id).localeCompare(pageName(b.id)))}
function statusFor(comment){if(comment.resolved)return'resolved';const a=assignmentFor(comment.id);if(a.status==='in-progress')return'in-progress';if(a.status==='blocked')return'blocked';return'open'}
function dueLabel(value){if(!value)return'No due date';const date=new Date(`${value}T23:59:59`),days=Math.ceil((date-Date.now())/86400000);if(days<0)return`${Math.abs(days)} day${Math.abs(days)===1?'':'s'} overdue`;if(days===0)return'Due today';if(days===1)return'Due tomorrow';return`Due in ${days} days`}
function renderSummary(host){const stats=threadStats(),readiness=review.context?.readiness||{},approvals=review.approvals||[],pages=pageSummary();host.innerHTML=`<section class="v24-collab-metrics"><article><strong>${stats.open}</strong><span>Open comments</span></article><article><strong>${stats.overdue}</strong><span>Overdue</span></article><article><strong>${stats.assigned}</strong><span>Assigned</span></article><article><strong>${Number(readiness.validApprovals||0)}</strong><span>Current approvals</span></article></section><section class="v24-collab-readiness ${readiness.ready?'is-ready':'is-blocked'}"><div><small>Publishing readiness</small><h3>${readiness.ready?'Ready for publication':'Review work remains'}</h3><p>${readiness.blockers?.length?readiness.blockers.map(x=>esc(x.message||x.code)).join(' · '):'No enabled review-policy blockers were reported.'}</p></div><button type="button" data-open-review="approvals">Open approval</button></section><section><div class="v24-collab-section-head"><h3>Page review summary</h3><button type="button" data-export-summary>Export CSV</button></div><div class="v24-collab-pages">${pages.length?pages.map(page=>`<button type="button" data-page="${esc(page.id)}"><strong>${esc(pageName(page.id))}</strong><span>${page.open} open · ${page.resolved} resolved</span><b>${page.total}</b></button>`).join(''):'<div class="v24-collab-empty">No page comments yet.</div>'}</div></section><section><h3>Approval activity</h3><div class="v24-collab-approvals">${approvals.length?approvals.slice(0,8).map(a=>`<article class="${esc(a.status)}"><strong>${esc(a.requestedFrom||'Reviewer')}</strong><span>${esc(a.status)}${a.stale?' · stale revision':''}</span><small>${esc(a.note||'No review note')}</small></article>`).join(''):'<div class="v24-collab-empty">No approval requests yet.</div>'}</div></section>`}
function filteredComments(){const q=query.toLowerCase();return rootComments().filter(c=>!q||[c.body,c.author,c.pageId,assignmentFor(c.id).assignee].join(' ').toLowerCase().includes(q)).sort((a,b)=>{const aa=assignmentFor(a.id),bb=assignmentFor(b.id),priority={high:0,normal:1,low:2};return(priority[aa.priority]??1)-(priority[bb.priority]??1)||String(aa.dueDate||'9999').localeCompare(String(bb.dueDate||'9999'))||Number(b.createdAt)-Number(a.createdAt)})}
function renderAssignments(host){const people=reviewers(),rows=filteredComments();host.innerHTML=`<section class="v24-collab-toolbar"><input type="search" data-search value="${esc(query)}" placeholder="Search review tasks"><button type="button" data-open-review="comments">New comment</button></section><datalist id="v24ReviewerList">${people.map(p=>`<option value="${esc(p.email||p.id)}">${esc(p.role||'reviewer')}</option>`).join('')}</datalist><section class="v24-assignment-list">${rows.length?rows.map(comment=>{const a=assignmentFor(comment.id),status=statusFor(comment);return`<article data-comment-id="${esc(comment.id)}" class="${status}"><div class="v24-assignment-copy"><small>${esc(pageName(comment.pageId))} · ${esc(comment.author||'Reviewer')}</small><strong>${esc(comment.body.slice(0,180))}</strong><span>${esc(dueLabel(a.dueDate))}</span></div><label>Assignee<input list="v24ReviewerList" data-field="assignee" value="${esc(a.assignee||'')}" placeholder="Unassigned"></label><label>Due<input type="date" data-field="dueDate" value="${esc(a.dueDate||'')}"></label><label>Priority<select data-field="priority"><option value="normal"${(a.priority||'normal')==='normal'?' selected':''}>Normal</option><option value="high"${a.priority==='high'?' selected':''}>High</option><option value="low"${a.priority==='low'?' selected':''}>Low</option></select></label><label>Status<select data-field="status"${comment.resolved?' disabled':''}><option value="open"${status==='open'?' selected':''}>Open</option><option value="in-progress"${status==='in-progress'?' selected':''}>In progress</option><option value="blocked"${status==='blocked'?' selected':''}>Blocked</option><option value="resolved"${status==='resolved'?' selected':''}>Resolved</option></select></label><div class="v24-assignment-actions"><button type="button" data-jump-comment="${esc(comment.id)}">Open</button>${comment.resolved?`<button type="button" data-reopen="${esc(comment.id)}">Reopen</button>`:`<button type="button" class="primary" data-resolve="${esc(comment.id)}">Resolve</button>`}</div></article>`}).join(''):'<div class="v24-collab-empty">No matching review tasks.</div>'}</section>`}
function mentionOptions(){return reviewers().map(p=>({label:`@${p.email||p.id}`,role:p.role||'reviewer'}))}
function renderMentions(host){const people=mentionOptions();host.innerHTML=`<section class="v24-mention-helper"><h3>Mention a collaborator</h3><p>Select a collaborator to copy an @mention, then paste it into a review comment or reply. Mentions remain part of the private review text.</p><div>${people.length?people.map(p=>`<button type="button" data-copy-mention="${esc(p.label)}"><strong>${esc(p.label)}</strong><span>${esc(p.role)}</span></button>`).join(''):'<div class="v24-collab-empty">Add invitation collaborators to use mention suggestions.</div>'}</div></section><section class="v24-collab-note"><strong>Notification behavior</strong><p>The existing review system notifies invitation owners and collaborators about comments and replies. V24.5 adds mention assistance and task organization; it does not claim full real-time simultaneous editing.</p></section>`}
function ensureDialog(){if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='v24CollaborationDialog';dialog.className='v24-collaboration-dialog';dialog.innerHTML=`<header><div><small>Invitation team workflow</small><h2>Collaboration center</h2></div><button type="button" data-close aria-label="Close">×</button></header><nav><button type="button" data-tab="summary">Summary</button><button type="button" data-tab="assignments">Assignments</button><button type="button" data-tab="mentions">Mentions</button></nav><main data-body></main><footer><span data-footer></span><button type="button" data-close>Done</button></footer>`;document.body.append(dialog);dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.querySelector('nav').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;activeTab=b.dataset.tab;render()};dialog.querySelector('[data-body]').addEventListener('input',e=>{if(e.target.matches('[data-search]')){query=e.target.value;render();return}const row=e.target.closest('[data-comment-id]'),field=e.target.dataset.field;if(row&&field)updateAssignment(row.dataset.commentId,{[field]:e.target.value})});dialog.querySelector('[data-body]').addEventListener('click',async e=>{const openReview=e.target.closest('[data-open-review]'),jump=e.target.closest('[data-jump-comment]'),resolve=e.target.closest('[data-resolve]'),reopen=e.target.closest('[data-reopen]'),page=e.target.closest('[data-page]'),copy=e.target.closest('[data-copy-mention]');try{if(openReview){dialog.close();review.open(openReview.dataset.openReview);return}if(jump){await review.jumpToComment(jump.dataset.jumpComment);dialog.close();return}if(resolve){await review.resolveComment(resolve.dataset.resolve,true);render();return}if(reopen){await review.resolveComment(reopen.dataset.reopen,false);render();return}if(page){const id=page.dataset.page;if(typeof window.switchCanvas==='function')window.switchCanvas(id);dialog.close();return}if(copy){await navigator.clipboard.writeText(copy.dataset.copyMention);window.EInviteFeedback?.toast?.('Mention copied');return}if(e.target.closest('[data-export-summary]'))exportCsv()}catch(error){window.EInviteFeedback?.toast?.(error.message,'error')}});dialog.addEventListener('close',()=>{opener?.focus?.();opener=null});return dialog}
function render(){const d=dialog;if(!d)return;d.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===activeTab)));const host=d.querySelector('[data-body]');if(activeTab==='assignments')renderAssignments(host);else if(activeTab==='mentions')renderMentions(host);else renderSummary(host);const stats=threadStats();d.querySelector('[data-footer]').textContent=`${stats.open} open · ${stats.overdue} overdue · ${review.context?.unreadCount||0} unread activity`}
async function open(tab='summary'){const d=ensureDialog();opener=document.activeElement;activeTab=tab;d.showModal();d.querySelector('[data-body]').innerHTML='<div class="v24-collab-loading">Refreshing private review data…</div>';await Promise.all([review.refresh({quiet:true}),loadAssignments()]);render();d.querySelector('input,button')?.focus();return true}
function csvCell(v){const text=String(v??'');return/[",\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
function exportCsv(){const map=assignmentMap(),rows=[['Page','Comment','Author','Resolved','Assignee','Due date','Priority','Task status'],...rootComments().map(c=>{const a=map[c.id]||{};return[pageName(c.pageId),c.body,c.author,c.resolved?'Yes':'No',a.assignee||'',a.dueDate||'',a.priority||'normal',statusFor(c)]})],blob=new Blob([rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`invitation-review-summary-${invitationId()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);return rows.length-1}
function installLauncher(){const host=document.querySelector('.studio-statusbar>div:last-child')||document.querySelector('.studio-statusbar');if(host&&!host.querySelector('[data-v24-collaboration-launch]')){const b=document.createElement('button');b.type='button';b.dataset.v24CollaborationLaunch='1';b.dataset.commandId='collaboration.open';b.textContent='Team';b.title='Review summary, assignments, and mentions';host.prepend(b)}}
function register(){unregister.push(...registry.registerMany([{id:'collaboration.open',title:'Open collaboration center',category:'Review',keywords:['team','assign','due date','mentions','summary'],bindings:{standard:['Mod+Alt+Shift+C'],canva:['Mod+Alt+Shift+C'],photoshop:['Mod+Alt+Shift+C']},run:()=>open('summary')},{id:'collaboration.assignments',title:'Open review assignments',category:'Review',bindings:{standard:[],canva:[],photoshop:[]},run:()=>open('assignments')},{id:'collaboration.exportSummary',title:'Export review summary CSV',category:'Review',bindings:{standard:[],canva:[],photoshop:[]},run:exportCsv}]))}
function install(){register();installLauncher();const observer=new MutationObserver(installLauncher);observer.observe(document.body,{childList:true,subtree:true});cleanup.push(()=>observer.disconnect());on(window,'einvite:review-assignments-changed',render);document.body.classList.add('collaboration-v24');window.EInviteCollaborationCenter=Object.freeze({version:24.5,open,assignments:{list:assignmentMap,refresh:loadAssignments,update:updateAssignment},summary:threadStats,exportCsv})}
function destroy(){cleanup.splice(0).forEach(fn=>{try{fn()}catch{}});unregister.splice(0).forEach(fn=>{try{fn()}catch{}});dialog?.remove();document.body.classList.remove('collaboration-v24');delete window.EInviteCollaborationCenter}
window.EInviteLifecycle?.add?.(destroy);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
