(()=>{
'use strict';
const VERSION=13;
const kits={
 'royal-khmer-gold':{id:'royal-khmer-gold',name:'Royal Khmer Gold',category:'Heritage',description:'Regal Khmer ornament, warm ivory surfaces and ceremonial gold.',preview:['#3b2415','#b88a2a','#fff8e7'],headingFont:'Cormorant Garamond',bodyFont:'Inter',khmerHeadingFont:'Moul',khmerBodyFont:'Noto Sans Khmer',primary:'#8a5b16',secondary:'#c8a14a',background:'#fff8e7',surface:'#fffdf7',text:'#3b2b1e',muted:'#7d6a55',accent:'#b88a2a',buttonStyle:'royal',photoFrame:'gold-line',ornament:'khmer-diamond',divider:'double-gold',spacing:'generous',radius:'soft',shadow:'ceremonial',motion:'graceful',opening:'royal-khmer-gate',desktopLayout:'ambient-frame'},
 'modern-cambodian-luxury':{id:'modern-cambodian-luxury',name:'Modern Cambodian Luxury',category:'Contemporary',description:'Editorial charcoal, champagne accents and refined modern typography.',preview:['#171717','#d7b56d','#f4efe7'],headingFont:'Playfair Display',bodyFont:'Inter',khmerHeadingFont:'Battambang',khmerBodyFont:'Noto Sans Khmer',primary:'#171717',secondary:'#d7b56d',background:'#f4efe7',surface:'#ffffff',text:'#202020',muted:'#6b655e',accent:'#b28a42',buttonStyle:'editorial',photoFrame:'offset',ornament:'minimal-line',divider:'hairline',spacing:'balanced',radius:'minimal',shadow:'editorial',motion:'cinematic',opening:'minimal-editorial',desktopLayout:'editorial-split'},
 'botanical-blush':{id:'botanical-blush',name:'Botanical Blush',category:'Romantic',description:'Soft botanical color, airy spacing and elegant floral details.',preview:['#754c57','#dba8af','#fff7f4'],headingFont:'Cormorant Garamond',bodyFont:'Manrope',khmerHeadingFont:'Koulen',khmerBodyFont:'Noto Sans Khmer',primary:'#754c57',secondary:'#dba8af',background:'#fff7f4',surface:'#ffffff',text:'#3d3033',muted:'#7b696d',accent:'#b86f7d',buttonStyle:'pill',photoFrame:'soft-arch',ornament:'botanical',divider:'floral',spacing:'generous',radius:'rounded',shadow:'soft',motion:'soft',opening:'floral-reveal',desktopLayout:'full-width'}
};
const openingDefaults={id:'soft-monogram',monogram:'',subtitle:'You are warmly invited',backgroundColor:'#fff8f2',backgroundImage:'',decorative:true,enterText:'Open invitation',enterTextKm:'បើកការអញ្ជើញ',duration:1100,textVariant:'dark',skipAllowed:true};
function copy(v){return JSON.parse(JSON.stringify(v));}
function migrate(input){const hadOpening=Boolean(input&&input.openingScene);const d=input&&typeof input==='object'?input:{};d.schemaVersion=Math.max(Number(d.schemaVersion||0),VERSION);d.styleKit={id:d.styleKit?.id||'',overrides:{...(d.styleKit?.overrides||{})},templateDefaults:d.styleKit?.templateDefaults||null};d.openingScene={...openingDefaults,...(d.openingScene||{})};if(d.openingStyle&&!hadOpening){const map={soft:'soft-monogram',curtain:'silk-curtain',night:'cinematic-photo',minimal:'minimal-editorial'};d.openingScene.id=map[d.openingStyle]||'soft-monogram';}d.desktopGuestLayout=d.desktopGuestLayout||d.styleKit?.overrides?.desktopLayout||kits[d.styleKit?.id]?.desktopLayout||'ambient-frame';d.socialCard={photo:'',alignment:'center',textVariant:'dark',language:d.languageMode||'both',monogram:'',...(d.socialCard||{})};d.experience={focusMode:false,...(d.experience||{})};d.settings={...(d.settings||{})};d.settings.musicSource=d.settings.musicSource||(d.youtubeId?'youtube':d.soundcloudUrl?'soundcloud':d.music?.url?'uploaded':'none');d.settings.musicStartAfterOpen=d.settings.musicStartAfterOpen!==false;d.settings.musicLoop=d.settings.musicLoop!==false;d.settings.musicVolume=Math.max(0,Math.min(1,Number(d.settings.musicVolume??0.75)));d.settings.musicFadeIn=Math.max(0,Math.min(10,Number(d.settings.musicFadeIn??1.2)));d.settings.showMusicControl=d.settings.showMusicControl!==false;d.settings.youtubeDisplayMode=['background','embedded','featured'].includes(d.settings.youtubeDisplayMode)?d.settings.youtubeDisplayMode:'background';d.settings.rsvpCloseDate=String(d.settings.rsvpCloseDate||'').slice(0,10);d.settings.rsvpMaxGuests=Math.max(1,Math.min(50,Number(d.settings.rsvpMaxGuests||10)));d.settings.rsvpQuestions={meal:false,transport:false,accommodation:false,...(d.settings.rsvpQuestions||{})};return window.EInviteEditorSchema?.migrate?window.EInviteEditorSchema.migrate(d):d;}
function snapshotDefaults(d){return {palette:copy(d.palette||{}),accent:d.accent,sectionStyles:copy(d.sectionStyles||{}),sectionAnimations:copy(d.sectionAnimations||{}),masterPageStyle:copy(d.masterPageStyle||{}),openingScene:copy(d.openingScene||openingDefaults),desktopGuestLayout:d.desktopGuestLayout,objectFonts:Object.fromEntries(Object.entries(d.objects||{}).map(([id,o])=>[id,o.font||'']))};}
function applyKit(documentData,id){const d=migrate(documentData),kit=kits[id];if(!kit)return d;if(!d.styleKit.templateDefaults)d.styleKit.templateDefaults=snapshotDefaults(d);d.styleKit.id=id;d.palettePreset='custom';d.palette={background:kit.background,surface:kit.surface,text:kit.text,heading:kit.primary};d.accent=kit.accent;d.desktopGuestLayout=kit.desktopLayout;d.openingScene={...d.openingScene,id:kit.opening};Object.keys(d.sectionStyles||{}).forEach(k=>{d.sectionStyles[k]={...(d.sectionStyles[k]||{}),backgroundEnabled:false,textColorEnabled:false,radius:kit.radius==='rounded'?24:kit.radius==='soft'?14:4};});const motion={graceful:{preset:'fade-up',duration:1000},cinematic:{preset:'soft-zoom',duration:1150},soft:{preset:'fade-up',duration:850}}[kit.motion]||{preset:'fade-up',duration:900};Object.keys(d.sectionAnimations||{}).forEach(k=>{d.sectionAnimations[k]={...(d.sectionAnimations[k]||{}),...motion};});if(d.masterPageStyle&&typeof d.masterPageStyle==='object')d.masterPageStyle={...d.masterPageStyle,background:kit.background};Object.entries(d.objects||{}).forEach(([id,o])=>{if(o.type!=='text')return;const khmer=Boolean(o.html&&/[\u1780-\u17FF]/.test(o.html)),heading=id==='title'||/title|heading/i.test(String(o.layerName||''))||Number(o.fontSize||0)>=34;o.font=heading?(khmer?kit.khmerHeadingFont:kit.headingFont):(khmer?kit.khmerBodyFont:kit.bodyFont);});d.styleKit.overrides={};return d;}
function restoreDefaults(documentData){const d=migrate(documentData),x=d.styleKit?.templateDefaults;if(!x)return d;d.palette=copy(x.palette);d.accent=x.accent;d.sectionStyles=copy(x.sectionStyles);d.sectionAnimations=copy(x.sectionAnimations);d.masterPageStyle=copy(x.masterPageStyle);d.openingScene=copy(x.openingScene);d.desktopGuestLayout=x.desktopGuestLayout;Object.entries(x.objectFonts||{}).forEach(([id,font])=>{if(d.objects?.[id])d.objects[id].font=font;});d.styleKit={id:'',overrides:{},templateDefaults:null};return d;}
window.EInviteExperience={VERSION,kits,openingDefaults,migrate,applyKit,restoreDefaults,snapshotDefaults,copy};
})();
