(()=>{'use strict';
const COPY={
 en:{nav:'Invitation sections',previous:'Previous section',next:'Next section',share:'Share invitation',top:'Back to top',open:'Open section list',section:'Section'},
 km:{nav:'ផ្នែកនៃធៀបអញ្ជើញ',previous:'ផ្នែកមុន',next:'ផ្នែកបន្ទាប់',share:'ចែករំលែកការអញ្ជើញ',top:'ត្រឡប់ទៅខាងលើ',open:'បើកបញ្ជីផ្នែក',section:'ផ្នែក'}
};
const SECTION_LABELS=[
 ['.artistic-hero-section','Invitation','ធៀបអញ្ជើញ'],['.guest-hero','Event details','ព័ត៌មានកម្មវិធី'],['.photo-gallery','Photo gallery','វិចិត្រសាលរូបថត'],['.video-section','Featured video','វីដេអូពិសេស'],['.countdown-section','Countdown','រាប់ថយក្រោយ'],['.event-journey','Events & ceremonies','កម្មវិធី និងពិធី'],['.schedule-section','Schedule','កាលវិភាគ'],['.custom-blocks','More details','ព័ត៌មានបន្ថែម'],['.guest-information','Guest information','ព័ត៌មានសម្រាប់ភ្ញៀវ'],['.venue-section','Venue','ទីតាំងកម្មវិធី'],['.contact-section','Contact','ទំនាក់ទំនង'],['#guestWish,.guest-wishes-form','Send wishes','ផ្ញើពាក្យជូនពរ'],['#rsvp,.rsvp-closed','RSVP','ឆ្លើយតបការអញ្ជើញ']
];
const visibleText=(element,language)=>{const candidates=[...element.querySelectorAll('h1,h2,h3,[aria-label]')];for(const item of candidates){if(getComputedStyle(item).display==='none'||item.hidden)continue;const translated=item.matches(`.i18n-${language}`)?item:item.querySelector(`.i18n-${language}`),value=(item.getAttribute('aria-label')||translated?.textContent||item.innerText||'').replace(/\s+/g,' ').trim();if(value)return value}return''};
const journeySections=root=>{const content=root.querySelector('.guest-layout-content')||root;return [...content.children].filter(element=>element.matches('section,form,.custom-blocks')&&!element.hidden)};
function enhance(root,documentData){
 if(!root||root.dataset.guestJourneyApplied==='true'||documentData?.settings?.guestNavigationEnabled===false)return;
 const sections=journeySections(root);if(sections.length<2)return;root.dataset.guestJourneyApplied='true';if(!root.dataset.language)root.dataset.language=documentData?.languageMode==='km'?'km':'en';
 const cover=root.querySelector('#openCover'),hasMusic=!!root.querySelector('#musicToggle');if(hasMusic)root.classList.add('guest-journey-has-music');
 sections.forEach((section,index)=>{section.dataset.guestWaypoint=String(index);if(!section.id)section.id=`invitation-section-${index+1}`;section.setAttribute('tabindex','-1')});
 const dock=document.createElement('nav');dock.className='guest-journey';dock.dataset.ready=cover?'false':'true';dock.setAttribute('aria-label',COPY.en.nav);dock.innerHTML='<span class="guest-journey-progress" aria-hidden="true"><i></i></span><button type="button" data-journey-prev><span aria-hidden="true">‹</span></button><button type="button" class="guest-journey-current" data-journey-menu aria-haspopup="true" aria-expanded="false"><small></small><strong></strong></button><button type="button" data-journey-next><span aria-hidden="true">›</span></button><button type="button" data-journey-share><span aria-hidden="true">↗</span></button><button type="button" data-journey-top><span aria-hidden="true">↑</span></button>';
 const menu=document.createElement('div');menu.className='guest-journey-menu';menu.hidden=true;menu.setAttribute('role','dialog');menu.setAttribute('aria-modal','false');menu.innerHTML='<div role="list"></div>';
 const live=document.createElement('p');live.className='guest-journey-live';live.setAttribute('aria-live','polite');
 root.append(dock,menu,live);
 const previous=dock.querySelector('[data-journey-prev]'),next=dock.querySelector('[data-journey-next]'),share=dock.querySelector('[data-journey-share]'),top=dock.querySelector('[data-journey-top]'),menuButton=dock.querySelector('[data-journey-menu]'),count=dock.querySelector('small'),title=dock.querySelector('strong'),progress=dock.querySelector('.guest-journey-progress i'),list=menu.querySelector('[role="list"]');let active=0,scheduled=false;
 const language=()=>root.dataset.language==='km'||documentData?.languageMode==='km'?'km':'en';
 const copy=()=>COPY[language()];
 const label=(section,index)=>{const words=SECTION_LABELS.find(([selector])=>section.matches(selector));return words?words[language()==='km'?2:1]:visibleText(section,language())||`${copy().section} ${index+1}`};
 const closeMenu=(restore=false)=>{menu.hidden=true;menuButton.setAttribute('aria-expanded','false');if(restore)menuButton.focus()};
 const go=index=>{const target=sections[Math.max(0,Math.min(sections.length-1,index))];closeMenu();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});target.focus({preventScroll:true})};
 const refreshLanguage=()=>{const words=copy();dock.setAttribute('aria-label',words.nav);previous.setAttribute('aria-label',words.previous);next.setAttribute('aria-label',words.next);share.setAttribute('aria-label',words.share);top.setAttribute('aria-label',words.top);menuButton.setAttribute('aria-label',words.open);[...list.children].forEach((button,index)=>button.textContent=label(sections[index],index));title.textContent=label(sections[active],active)};
 sections.forEach((section,index)=>{const button=document.createElement('button');button.type='button';button.dataset.journeyTarget=String(index);button.setAttribute('role','listitem');button.onclick=()=>go(index);list.append(button)});
 const update=()=>{scheduled=false;const anchor=innerHeight*.38;let best=0,distance=Infinity;sections.forEach((section,index)=>{const rect=section.getBoundingClientRect(),candidate=rect.top<=anchor&&rect.bottom>=anchor?0:Math.min(Math.abs(rect.top-anchor),Math.abs(rect.bottom-anchor));if(candidate<distance){best=index;distance=candidate}});active=best;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),ratio=Math.max(0,Math.min(1,scrollY/max));progress.style.transform=`scaleX(${ratio})`;count.textContent=`${active+1} / ${sections.length}`;title.textContent=label(sections[active],active);previous.disabled=active===0;next.disabled=active===sections.length-1;dock.dataset.scrolled=scrollY>Math.min(420,innerHeight*.55)?'true':'false';[...list.children].forEach((button,index)=>button.setAttribute('aria-current',index===active?'true':'false'))};
 const schedule=()=>{if(!scheduled){scheduled=true;requestAnimationFrame(update)}};
 previous.onclick=()=>go(active-1);next.onclick=()=>go(active+1);top.onclick=()=>{closeMenu();scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};share.onclick=()=>{const open=window.EInvitePublicShare?.open;if(open)open(share);else document.querySelector('#shareInvitation')?.click()};menuButton.onclick=()=>{menu.hidden=!menu.hidden;menuButton.setAttribute('aria-expanded',String(!menu.hidden));if(!menu.hidden){const current=list.querySelector('[aria-current="true"]')||list.firstElementChild;current?.focus()}};
 addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule,{passive:true});document.addEventListener('pointerdown',event=>{if(!menu.hidden&&!menu.contains(event.target)&&!menuButton.contains(event.target))closeMenu()});menu.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closeMenu(true)}});root.addEventListener('click',event=>{if(event.target.closest('[data-guest-lang]'))requestAnimationFrame(()=>{refreshLanguage();update()})});
 if(cover)cover.addEventListener('click',()=>requestAnimationFrame(()=>{dock.dataset.ready='true';update()}),{once:true});
 refreshLanguage();update();
}
window.EInviteGuestJourney={enhance};
})();
