(()=>{
'use strict';
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const allowed=new Set(['BR','B','STRONG','I','EM','U','S','UL','OL','LI','SPAN','A']);
const dropWithContent=new Set(['SCRIPT','STYLE','IFRAME','OBJECT','EMBED','SVG','MATH','TEMPLATE','NOSCRIPT']);
const allowedStyles=new Set(['color','background-color','font-weight','font-style','text-decoration','text-align']);
function safeStyleValue(key,value){
  const v=String(value||'').trim();if(!v||/[\\<>]/.test(v)||/url\s*\(|expression\s*\(|javascript\s*:/i.test(v))return'';
  if(key==='color'||key==='background-color')return /^(?:#[0-9a-f]{3,8}|(?:rgb|rgba|hsl|hsla)\([0-9.,%\s+-]+\)|[a-z]{1,24})$/i.test(v)?v:'';
  if(key==='font-weight')return /^(?:normal|bold|[1-9]00)$/i.test(v)?v:'';
  if(key==='font-style')return /^(?:normal|italic|oblique)$/i.test(v)?v:'';
  if(key==='text-decoration')return /^(?:none|underline|line-through|overline)(?:\s+(?:underline|line-through|overline))*$/i.test(v)?v:'';
  if(key==='text-align')return /^(?:left|center|right|justify)$/i.test(v)?v:'';
  return'';
}
function safeHref(value){const raw=String(value||'').trim();if(!raw)return'';if(/^(?:https?:|mailto:|tel:)/i.test(raw)||raw.startsWith('/')||raw.startsWith('#'))return raw;return''}
function cleanNode(node,doc){
  if(node.nodeType===Node.TEXT_NODE)return doc.createTextNode(node.textContent||'');
  if(node.nodeType!==Node.ELEMENT_NODE)return doc.createTextNode('');
  if(dropWithContent.has(node.tagName))return doc.createTextNode('');
  if(!allowed.has(node.tagName)){const frag=doc.createDocumentFragment();[...node.childNodes].forEach(child=>frag.append(cleanNode(child,doc)));return frag}
  const el=doc.createElement(node.tagName.toLowerCase());
  if(node.tagName==='SPAN'&&node.getAttribute('style')){
    const safe=[];String(node.getAttribute('style')).split(';').forEach(pair=>{const [rawKey,...rest]=pair.split(':'),key=(rawKey||'').trim().toLowerCase(),value=safeStyleValue(key,rest.join(':'));if(allowedStyles.has(key)&&value)safe.push(`${key}:${value}`)});if(safe.length)el.setAttribute('style',safe.join(';'))
  }
  if(node.tagName==='A'){
    const href=safeHref(node.getAttribute('href'));if(href)el.setAttribute('href',href);
    const target=node.getAttribute('target');if(target==='_blank'){el.setAttribute('target','_blank');el.setAttribute('rel','noopener noreferrer')}
  }
  [...node.childNodes].forEach(child=>el.append(cleanNode(child,doc)));return el
}
function sanitizeRichText(html){
  const source=String(html??'');if(!source)return'';
  if(typeof document==='undefined')return esc(source.replace(/<(?:script|style|iframe|object|embed|svg|math|template|noscript)\b[^>]*>[\s\S]*?<\/\s*(?:script|style|iframe|object|embed|svg|math|template|noscript)\s*>/gi,'').replace(/<[^>]+>/g,''));
  const template=document.createElement('template');template.innerHTML=source;const out=document.createElement('div');[...template.content.childNodes].forEach(node=>out.append(cleanNode(node,document)));return out.innerHTML
}
function plainText(html){if(typeof document==='undefined')return String(html??'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const div=document.createElement('div');div.innerHTML=sanitizeRichText(html);return div.textContent||''}
function imageAdjustmentState(o={}){const state={...o};let layers=o.imageAdjustmentLayers||[];if(typeof layers==='string'){try{layers=JSON.parse(layers)}catch{layers=[]}}if(!Array.isArray(layers))layers=[];for(const layer of layers){if(!layer||layer.enabled===false)continue;const value=Number(layer.value||0);switch(layer.type){case'brightness':state.imageBrightness=Number(state.imageBrightness??100)+value;break;case'contrast':state.imageContrast=Number(state.imageContrast??100)+value;break;case'saturation':state.imageSaturation=Number(state.imageSaturation??100)+value;break;case'hue':state.imageHue=Number(state.imageHue||0)+value;break;case'blur':state.imageBlur=Number(state.imageBlur||0)+Math.max(0,value);break;case'grayscale':state.imageGrayscale=Math.max(Number(state.imageGrayscale||0),value);break;case'sepia':state.imageSepia=Math.max(Number(state.imageSepia||0),value);break;case'vibrance':state.imageVibrance=Number(state.imageVibrance||0)+value;break;case'temperature':state.imageTemperature=Number(state.imageTemperature||0)+value;break;case'gamma':state.imageGamma=Number(state.imageGamma||1)*Math.max(.25,value||1);break}}return state}
function imageFilterStyle(o={}){o=imageAdjustmentState(o);const clamp=(v,min,max,fallback)=>Math.max(min,Math.min(max,Number(v??fallback))),vibrance=clamp(o.imageVibrance,-100,100,0),temperature=clamp(o.imageTemperature,-100,100,0),saturation=clamp(o.imageSaturation,0,250,100)*(1+vibrance/250),sepia=Math.max(0,Math.min(100,clamp(o.imageSepia,0,100,0)+Math.max(0,temperature)*.18)),hue=clamp(o.imageHue,-180,180,0)+temperature*.08,levelsBlack=clamp(o.imageLevelsBlack,0,80,0),levelsWhite=clamp(o.imageLevelsWhite,20,100,100),levelRange=Math.max(20,levelsWhite-levelsBlack),gamma=clamp(o.imageGamma,.25,3,1),shadows=clamp(o.imageCurveShadows,-100,100,0),highlights=clamp(o.imageCurveHighlights,-100,100,0),gammaBrightness=100+(1-gamma)*28,curveBrightness=shadows*.10+highlights*.06,curveContrast=(highlights-shadows)*.12,contrast=clamp(o.imageContrast,20,200,100)*(100/levelRange)+curveContrast,brightness=clamp(o.imageBrightness,20,200,100)*(1-levelsBlack/220)*((gammaBrightness+curveBrightness)/100);return`brightness(${Math.max(15,Math.min(240,brightness))}%) contrast(${Math.max(15,Math.min(260,contrast))}%) saturate(${saturation}%) grayscale(${clamp(o.imageGrayscale,0,100,0)}%) sepia(${sepia}%) hue-rotate(${hue}deg) blur(${clamp(o.imageBlur,0,20,0)}px)`}
function imageTransformStyle(o={}){const px=Math.max(-60,Math.min(60,Number(o.imagePerspectiveX||0))),py=Math.max(-60,Math.min(60,Number(o.imagePerspectiveY||0))),wx=Math.max(-30,Math.min(30,Number(o.imageWarpX||0))),wy=Math.max(-30,Math.min(30,Number(o.imageWarpY||0)));return`perspective(900px) rotateY(${px}deg) rotateX(${py}deg) skew(${wx}deg,${wy}deg) scaleX(${o.imageFlipX?-1:1}) scaleY(${o.imageFlipY?-1:1})`}
function imageMaskStyle(o={}){const feather=Math.max(0,Math.min(50,Number(o.imageMaskFeather||0))),strength=Math.max(0,Math.min(100,Number(o.imageGradientMask||0)));if(!strength&&!feather)return'';const edge=Math.max(0,100-feather),alpha=Math.max(0,Math.min(1,strength/100));return`-webkit-mask-image:linear-gradient(to bottom,rgba(0,0,0,1) 0%,rgba(0,0,0,1) ${edge}%,rgba(0,0,0,${1-alpha}) 100%);mask-image:linear-gradient(to bottom,rgba(0,0,0,1) 0%,rgba(0,0,0,1) ${edge}%,rgba(0,0,0,${1-alpha}) 100%);`}
function objectDimension(value,axis='x'){if(!value)return axis==='x'?'50%':'80px';if(String(value).includes('%'))return value;const number=parseFloat(value);if(!Number.isFinite(number))return value;return`${number/(axis==='x'?390:844)*100}%`}
function animationName(value){return({'fade-up':'fadeUp','soft-zoom':'softZoom','slide-left':'slideLeft','blur-in':'blurIn','bounce-in':'bounceIn','flip-in':'flipIn','float':'floatIn','none':'none'})[value]||'fadeUp'}
function advancedObjectStyle(o={}){const blend=['normal','multiply','screen','overlay','soft-light','darken','lighten'].includes(o.blendMode)?o.blendMode:'normal';const delay=Math.max(0,Math.min(5000,Number(o.animationDelay||0)));let background='transparent';if(o.backgroundEnabled){const hex=/^#[0-9a-f]{6}$/i.test(o.backgroundColor||'')?o.backgroundColor:'#ffffff',alpha=Math.max(0,Math.min(100,Number(o.backgroundOpacity??100)))/100,h=hex.slice(1);background=`rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},${alpha})`}return`mix-blend-mode:${blend};background:${background};animation-delay:${delay}ms`}
function advancedTextStyle(o={}){const transform=['none','uppercase','lowercase','capitalize'].includes(o.textTransform)?o.textTransform:'none',stroke=Math.max(0,Math.min(8,Number(o.textStrokeWidth||0))),strokeColor=/^#[0-9a-f]{6}$/i.test(o.textStrokeColor||'')?o.textStrokeColor:'#ffffff',shadowBlur=Math.max(0,Math.min(40,Number(o.textShadowBlur||0))),shadowColor=/^#[0-9a-f]{6}$/i.test(o.textShadowColor||'')?o.textShadowColor:'#000000',shadow=shadowBlur?`text-shadow:0 ${Math.max(1,Math.round(shadowBlur/4))}px ${shadowBlur}px ${shadowColor};`:'',gradient=o.textGradientEnabled?`background-image:linear-gradient(${Math.max(0,Math.min(360,Number(o.textGradientAngle||90)))}deg,${esc(o.textGradientStart||'#9d4555')},${esc(o.textGradientEnd||'#b58a3a')});background-clip:text;-webkit-background-clip:text;color:transparent;`:'';return`text-transform:${transform};-webkit-text-stroke:${stroke}px ${strokeColor};${shadow}${gradient}`}
function typographyProjection(o={},documentModel={},options={}){
 const documentData=documentModel&&typeof documentModel==='object'?documentModel:{};
 if(globalThis.TypographyDocumentModel){const catalog=TypographyDocumentModel.normalizeCatalog(documentData.typography||{}),normalized=o.typographyModelVersion?o:TypographyDocumentModel.normalizeObject(options.id||o.id||'',o,catalog);return TypographyDocumentModel.resolveObjectTypography({...documentData,typography:catalog},normalized,{text:options.text??plainText(o.html||''),locale:options.locale})}
 const t=globalThis.EInviteTypography?.normalizeTypography?globalThis.EInviteTypography.normalizeTypography(o):{...o,font:'noto-serif',fontSize:32,textAutoFit:'none',textAutoFitMax:32,textMinFontSize:10,textWrap:'normal',textColumns:1,textColumnGap:24,textAlign:'center'};
 return{...t,fontStack:globalThis.EInviteFontRegistry?.stack?EInviteFontRegistry.stack(t.font):"Georgia,serif",locale:/[\u1780-\u17ff]/u.test(String(options.text||o.html||''))?'km':'en'}
}
function typographyFontStack(font){return globalThis.EInviteFontRegistry?.stack?globalThis.EInviteFontRegistry.stack(font):'Georgia,serif'}
function typographyLayoutStyle(model={}){if(!globalThis.TypographyLayoutService)throw new Error('TypographyLayoutService must load before renderer-core.js');return TypographyLayoutService.styleString(TypographyLayoutService.styleObject(model).flow)}
function typographyOuterStyle(model={}){if(!globalThis.TypographyLayoutService)throw new Error('TypographyLayoutService must load before renderer-core.js');return TypographyLayoutService.styleString(TypographyLayoutService.styleObject(model).outer)}
function renderedElementModel(node){if(node?.__typographyModel)return node.__typographyModel;if(!node)return null;const style=getComputedStyle(node);return{styleId:node.dataset.textStyleId||'body',font:node.dataset.font||'noto-serif',fontPairing:node.dataset.fontPairing||'serif-formal',fontStack:style.fontFamily,fontSize:Number(node.dataset.fontSize||parseFloat(style.fontSize)||32),textAutoFit:node.dataset.textAutoFit==='fit'?'fit':'none',textAutoFitMax:Number(node.dataset.textAutoFitMax||node.dataset.fontSize||32),textMinFontSize:Number(node.dataset.textMinFontSize||10),fontWeight:style.fontWeight==='700'?'700':'400',fontStyle:style.fontStyle==='italic'?'italic':'normal',lineHeight:Number.parseFloat(style.lineHeight)/Math.max(1,Number.parseFloat(style.fontSize))||1.35,letterSpacing:Number.parseFloat(style.letterSpacing)||0,textAlign:node.dataset.textAlign||style.textAlign||'left',textVerticalAlign:style.justifyContent==='flex-start'?'top':style.justifyContent==='flex-end'?'bottom':'middle',textWrap:node.dataset.textWrap||'normal',textColumns:Number(node.dataset.textColumns||1),textColumnGap:Number(node.dataset.textColumnGap||24),textPadding:Number.parseFloat(style.padding)||0,locale:node.lang==='km'?'km':'en',color:style.color}}
function fitTypographyElement(outer,{set=true,model=null}={}){if(!outer)return null;const resolved=model||renderedElementModel(outer);if(!resolved)return null;const result=TypographyLayoutService.fit(outer,resolved,{set});return result?.computedSize??null}
function installResponsiveTypography(root=document){return TypographyLayoutService.installResponsive(root,{modelFor:renderedElementModel})}
const RendererAdapters=Object.freeze({
 project(documentModel,object,options={}){return typographyProjection(object,documentModel,options)},
 outerStyle(model){return typographyOuterStyle(model)},
 flowStyle(model){return typographyLayoutStyle(model)},
 attributes(model){return`data-typography-v19="true" data-typography-model-version="1" data-text-style-id="${esc(model.styleId||'body')}" data-font-pairing="${esc(model.fontPairing||'serif-formal')}" data-font="${esc(model.compatibilityFont||model.font)}" data-font-size="${model.fontSize}" data-text-auto-fit="${model.textAutoFit}" data-text-auto-fit-max="${model.textAutoFitMax}" data-text-min-font-size="${model.textMinFontSize}" data-text-wrap="${model.textWrap}" data-text-columns="${model.textColumns}" data-text-column-gap="${model.textColumnGap}" data-text-align="${model.textAlign}" lang="${model.locale==='km'?'km':'en'}"`},
 renderThumbnail(root,documentModel,objects,options={}){return TypographyLayoutService.renderThumbnail(root,{documentModel,objects,renderObject,project:RendererAdapters.project,...options})}
});
function shapeFillStyle(o={}){return o.fillMode==='gradient'?`linear-gradient(${Math.max(0,Math.min(360,Number(o.gradientAngle||135)))}deg,${esc(o.gradientStart||'#d9a6ad')},${esc(o.gradientEnd||'#9d4555')})`:esc(o.fillColor||'#d9a6ad')}
function responsiveImageAttributes(o={}){
 const src=String(o.src||''),width=Math.max(0,Number(o.intrinsicWidth||0)),height=Math.max(0,Number(o.intrinsicHeight||0));
 let attrs='';if(width&&height)attrs+=` width="${Math.round(width)}" height="${Math.round(height)}"`;
 const match=src.match(/^\/uploads\/([^?#]+)$/i),explicit=String(o.responsiveBase||'').trim();let base='';
 if(/^\/api\/(?:image|media)\/[^#]+$/i.test(explicit))base=explicit;else if(/^\/api\/media\/[^#]+$/i.test(src))base=src;else if(match&&!/\.gif$/i.test(match[1]))base=`/api/image/${encodeURIComponent(decodeURIComponent(match[1]))}`;
 if(base&&!/\.gif(?:$|[?#])/i.test(src)){const safe=esc(base),join=base.includes('?')?'&amp;':'?';attrs+=` srcset="${safe}${join}w=480&amp;format=webp 480w, ${safe}${join}w=960&amp;format=webp 960w, ${safe}${join}w=1440&amp;format=webp 1440w, ${safe}${join}w=1920&amp;format=webp 1920w" sizes="(max-width: 600px) 100vw, (max-width: 1200px) 80vw, 1200px"`}
 return attrs
}
function renderObject(o={},options={}){
 const id=options.id||'',pageHeight=Number(options.pageHeight||844),content=options.content!==undefined?options.content:(globalThis.RichTextRenderer?.renderObject(o,options.document||{},options)||sanitizeRichText(o.html||'')),heroTitle=!!options.heroTitle;
 const borderWidth=Math.max(0,Math.min(12,Number(o.borderWidth||0))),borderRadius=Math.max(0,Math.min(120,Number(o.borderRadius||0))),shadowBlur=Math.max(0,Math.min(60,Number(o.shadowBlur||0))),opacity=Math.max(.1,Math.min(1,Number(o.opacity??1))),shadow=shadowBlur?`0 ${Math.max(2,Math.round(shadowBlur/3))}px ${shadowBlur}px ${esc(o.shadowColor||'#000000')}55`:'none';
 const height=String(o.height||'80px').includes('%')?o.height:`${parseFloat(o.height||80)/pageHeight*100}%`,top=String(o.top||'0').includes('%')?o.top:`${parseFloat(o.top||0)/pageHeight*100}%`;
 const common=`left:${esc(o.left||'0')};top:${esc(top)};width:${esc(objectDimension(o.width,'x'))};height:${esc(height)};z-index:${Number(o.zIndex||1)};transform:rotate(${Number(o.rotation||0)}deg);opacity:${opacity};border:${borderWidth}px solid ${esc(o.borderColor||'#ffffff')};border-radius:${borderRadius}px;box-shadow:${shadow};animation-name:${animationName(o.animation)};animation-duration:${Math.max(300,Math.min(3000,Number(o.duration||900)))}ms;${advancedObjectStyle(o)}`;
 if(o.type==='image'&&o.src){const masks={none:'none',circle:'ellipse(50% 50% at 50% 50%)',arch:'inset(0 round 48% 48% 12% 12%)',diamond:'polygon(50% 0,100% 50%,50% 100%,0 50%)',hexagon:'polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%)',blob:'polygon(50% 0,78% 8%,96% 35%,91% 72%,66% 100%,31% 94%,6% 68%,0 32%,22% 7%)'},frames={none:['0','transparent'],white:['8px','#ffffff'],gold:['8px','#c79b42'],dark:['8px','#201b1b']},frame=frames[o.imageFrame||'none']||frames.none;return`<div class="published-object published-image reveal" data-object-id="${esc(id)}" style="${common};${o.dominantColor?`background:${esc(o.dominantColor)};`:''}"><img src="${esc(o.src)}"${responsiveImageAttributes(o)} alt="${esc(o.alt||'Invitation image')}" loading="lazy" decoding="async" style="object-fit:${esc(o.imageFit||'cover')};object-position:${Number(o.imagePositionX??50)}% ${Number(o.imagePositionY??50)}%;border-radius:inherit;clip-path:${masks[o.imageMask||'none']||'none'};padding:${frame[0]};background:${frame[1]};box-sizing:border-box;filter:${imageFilterStyle(o)};transform:${imageTransformStyle(o)};${imageMaskStyle(o)}"></div>`}
 if(o.type==='shape'){const kind=['rectangle','circle','line'].includes(o.shapeKind)?o.shapeKind:'rectangle',radius=kind==='circle'?'999px':'inherit';return`<div class="published-object published-shape published-shape-${kind} reveal" data-object-id="${esc(id)}" aria-hidden="true" style="${common};background:${shapeFillStyle(o)};border-radius:${radius}"></div>`}
 const t=RendererAdapters.project(options.document||{},o,{id,text:plainText(content),locale:options.locale});
 const outerStyle=RendererAdapters.outerStyle(t),flowStyle=RendererAdapters.flowStyle(t),attrs=RendererAdapters.attributes(t);
 return`<div class="published-object published-text reveal${heroTitle?' hero-object-title':''}${o.type==='decoration'?' published-decoration':''}" data-object-id="${esc(id)}" ${attrs} style="${common};${outerStyle}${advancedTextStyle(o)}"><div class="typography-flow" style="${flowStyle}">${content}</div></div>`
}
window.EInviteTypographyRendererAdapters=RendererAdapters;
window.EInviteRenderer={esc,sanitizeRichText,plainText,RendererAdapters,typographyProjection,typographyFontStack,typographyLayoutStyle,typographyOuterStyle,fitTypographyElement,installResponsiveTypography,imageFilterStyle,imageTransformStyle,imageMaskStyle,objectDimension,animationName,advancedObjectStyle,advancedTextStyle,shapeFillStyle,responsiveImageAttributes,renderObject};
})();
