(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const SIZES={og:[1200,630],square:[1080,1080],story:[1080,1920]};
function cleanUrl(url=location.href){const u=new URL(url,location.href);['g','guest','guestToken','access','access_token','token'].forEach(k=>u.searchParams.delete(k));return u.href;}
function fitImage(ctx,img,w,h){const scale=Math.max(w/img.naturalWidth,h/img.naturalHeight),sw=w/scale,sh=h/scale,sx=Math.max(0,(img.naturalWidth-sw)/2),sy=Math.max(0,(img.naturalHeight-sh)/2);ctx.drawImage(img,sx,sy,sw,sh,0,0,w,h)}
function loadImage(url){return new Promise(resolve=>{if(!url)return resolve(null);const img=new Image();try{if(new URL(url,location.href).origin!==location.origin)img.crossOrigin='anonymous'}catch{}img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=url})}
function wrap(ctx,text,x,y,max,line,limit=4){const value=String(text||'').trim();if(!value)return y;const units=/\s/.test(value)?value.split(/\s+/):Array.from(value),joiner=/\s/.test(value)?' ':'';let row='',yy=y,count=0;for(const unit of units){const next=row?row+joiner+unit:unit;if(ctx.measureText(next).width>max&&row){ctx.fillText(row,x,yy);yy+=line;row=unit;if(++count>=limit-1)break}else row=next}if(row&&count<limit)ctx.fillText(row,x,yy);return yy+line}
function cardText(d){const s=d.socialCard||{},f=d.fields||{},language=s.language||d.languageMode||'both',en=f.names||'Invitation',km=f.namesKm||'';let names=[en],venue=f.venue||'';if(language==='km'){names=[km||en];venue=f.venueKm||venue}else if(language==='both'&&km&&km!==en){names=[en,km];venue=[f.venue,f.venueKm].filter(Boolean).join(' · ')}return{language,names,date:f.date||'',venue}}
async function draw(canvas,d,format='og'){
  const [w,h]=SIZES[format]||SIZES.og;canvas.width=w;canvas.height=h;
  const ctx=canvas.getContext('2d'),kit=window.EInviteExperience?.kits?.[d.styleKit?.id]||{},s=d.socialCard||{},t=cardText(d),background=kit.background||d.palette?.background||'#fff8f2',accent=kit.accent||d.accent||'#9d4555',text=s.textVariant==='light'?'#fff':kit.text||d.palette?.text||'#342c26';
  ctx.fillStyle=background;ctx.fillRect(0,0,w,h);
  const photo=await loadImage(s.photo);
  if(photo){fitImage(ctx,photo,w,h);ctx.fillStyle=s.textVariant==='light'?'rgba(0,0,0,.46)':'rgba(255,248,242,.68)';ctx.fillRect(0,0,w,h)}else{if(s.textVariant==='light'){ctx.fillStyle=accent;ctx.fillRect(0,0,w,h)}const grd=ctx.createLinearGradient(0,0,w,h);grd.addColorStop(0,accent+'33');grd.addColorStop(1,'#ffffff00');ctx.fillStyle=grd;ctx.fillRect(0,0,w,h)}
  ctx.strokeStyle=accent;ctx.lineWidth=Math.max(3,w/300);ctx.strokeRect(w*.045,h*.07,w*.91,h*.86);
  const align=['left','center','right'].includes(s.alignment)?s.alignment:'center';ctx.textAlign=align;ctx.textBaseline='alphabetic';const x=align==='left'?w*.1:align==='right'?w*.9:w*.5;
  ctx.fillStyle=accent;ctx.font=`700 ${Math.round(w*.025)}px Inter, Arial, sans-serif`;ctx.fillText(t.language==='km'?'សូមគោរពអញ្ជើញ':'YOU ARE INVITED',x,h*.19);
  if(s.monogram){ctx.globalAlpha=.11;ctx.fillStyle=accent;ctx.font=`700 ${Math.round(w*.28)}px ${kit.headingFont||'Georgia'}, serif`;ctx.textAlign='center';ctx.fillText(s.monogram,w*.5,h*.58);ctx.globalAlpha=1;ctx.textAlign=align}
  ctx.fillStyle=text;let y=h*(t.names.length>1?.34:.39);for(const name of t.names){const khmer=/[\u1780-\u17FF]/.test(name),font=khmer?(kit.khmerHeadingFont||'Noto Sans Khmer'):(kit.headingFont||'Georgia');ctx.font=`700 ${Math.round(w*(t.names.length>1?.048:.064))}px "${font}", serif`;y=wrap(ctx,name,x,y,w*.76,Math.round(w*.07),2)+Math.round(w*.012)}
  ctx.font=`500 ${Math.round(w*.027)}px Inter, Arial, sans-serif`;if(t.date){ctx.fillText(t.date,x,Math.max(y,h*.67));y=Math.max(y,h*.67)+Math.round(w*.047)}
  if(t.venue){const khmer=/[\u1780-\u17FF]/.test(t.venue),font=khmer?(kit.khmerBodyFont||'Noto Sans Khmer'):(kit.bodyFont||'Arial');ctx.font=`400 ${Math.round(w*.024)}px "${font}", sans-serif`;wrap(ctx,t.venue,x,y,w*.72,Math.round(w*.034),3)}
  return canvas;
}
function download(canvas,name){try{const a=document.createElement('a');a.download=name;a.href=canvas.toDataURL('image/png',.92);a.click()}catch{window.uiToast?.('This photo source cannot be exported from the browser. Use the published-card download instead.','!')}}
async function downloadUrl(url,name,button){try{if(button)button.disabled=true;const r=await fetch(url,{credentials:'same-origin'});if(!r.ok){const data=await r.json().catch(()=>({}));throw Error(data.error||`Download failed (${r.status})`)}const blob=await r.blob(),a=document.createElement('a');a.download=name;a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);return true}catch(err){window.uiToast?.(err?.message||'This download is not available yet.','!');if(button&&/QR generation is unavailable/i.test(err?.message||'')){button.hidden=true;button.setAttribute('aria-hidden','true')}return false}finally{if(button&&!button.hidden)button.disabled=false}}
function render(host){
  const d=state.socialCard||{};
  host.innerHTML=`<div class="ei-field-grid"><label>Social cover photo URL<div class="ei-inline-field"><input id="eiSocialPhoto" value="${esc(d.photo||'')}" placeholder="Choose an uploaded photo"><button type="button" id="eiChooseSocialPhoto">Choose material</button></div></label><label>Text alignment<select id="eiSocialAlign"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label><label>Text color<select id="eiSocialText"><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Language<select id="eiSocialLanguage"><option value="en">English</option><option value="km">Khmer</option><option value="both">Bilingual</option></select></label><label>Monogram<input id="eiSocialMonogram" maxlength="8" value="${esc(d.monogram||'')}"></label><label>Format<select id="eiSocialFormat"><option value="og">Open Graph · 1200×630</option><option value="square">Square · 1080×1080</option><option value="story">Story · 1080×1920</option></select></label></div><div class="ei-social-preview"><canvas id="eiSocialCanvas" aria-label="Social invitation card preview"></canvas></div><div class="ei-share-actions" style="margin-top:14px"><button id="eiCopyLink">Copy public link</button><button id="eiCopyMessage">Copy invitation message</button><a id="eiTelegram" target="_blank" rel="noopener noreferrer">Telegram</a><a id="eiWhatsapp" target="_blank" rel="noopener noreferrer">WhatsApp</a><a id="eiFacebook" target="_blank" rel="noopener noreferrer">Facebook</a><button id="eiRegenerateSocial">Regenerate preview</button><button id="eiDownloadSocial">Download preview</button><button id="eiDownloadPublishedSocial">Download published card</button><button id="eiDownloadQr">Download branded QR</button><button id="eiSaveSocial" class="primary">Save settings</button></div>`;
  const canvas=host.querySelector('#eiSocialCanvas'),format=host.querySelector('#eiSocialFormat');host.querySelector('#eiSocialAlign').value=d.alignment||'center';host.querySelector('#eiSocialText').value=d.textVariant||'dark';host.querySelector('#eiSocialLanguage').value=d.language||state.languageMode||'both';let refreshToken=0;
  const refresh=async()=>{state.socialCard={...(state.socialCard||{}),photo:host.querySelector('#eiSocialPhoto').value.trim(),alignment:host.querySelector('#eiSocialAlign').value,textVariant:host.querySelector('#eiSocialText').value,language:host.querySelector('#eiSocialLanguage').value,monogram:host.querySelector('#eiSocialMonogram').value.trim()};const token=++refreshToken;await draw(canvas,state,format.value);if(token!==refreshToken)return};
  host.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',refresh));refresh();
  host.querySelector('#eiChooseSocialPhoto').onclick=()=>typeof openMaterialPicker==='function'?openMaterialPicker('Choose social cover',(url)=>{host.querySelector('#eiSocialPhoto').value=url;refresh()}):window.uiToast?.('Open Materials and copy an uploaded image URL.','!');
  const url=cleanUrl(serverInvite?.slug?`${location.origin}/i/${serverInvite.slug}`:location.href),msg=`You are invited to ${state.fields?.names||'our event'}${state.fields?.date?` — ${state.fields.date}`:''}. ${url}`;host.querySelector('#eiTelegram').href=`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(msg)}`;host.querySelector('#eiWhatsapp').href=`https://wa.me/?text=${encodeURIComponent(msg)}`;host.querySelector('#eiFacebook').href=`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;
  host.querySelector('#eiCopyLink').onclick=()=>navigator.clipboard.writeText(url);host.querySelector('#eiCopyMessage').onclick=()=>navigator.clipboard.writeText(msg);host.querySelector('#eiRegenerateSocial').onclick=refresh;host.querySelector('#eiDownloadSocial').onclick=()=>download(canvas,`invitation-${format.value}.png`);
  host.querySelector('#eiDownloadPublishedSocial').onclick=e=>serverInvite?.slug?downloadUrl(`/api/public/${encodeURIComponent(serverInvite.slug)}/social-card.png?format=${encodeURIComponent(format.value)}`,`invitation-${format.value}.png`,e.currentTarget):window.uiToast?.('Publish the invitation first.','!');
  host.querySelector('#eiDownloadQr').onclick=e=>serverInvite?.slug?downloadUrl(`/api/public/${encodeURIComponent(serverInvite.slug)}/qr-card.png`,'invitation-qr.png',e.currentTarget):window.uiToast?.('Publish the invitation first.','!');
  host.querySelector('#eiSaveSocial').onclick=()=>{refresh();save();window.uiToast?.('Social card settings saved. Republish to update public metadata.','✓')};
}
window.EInviteSocialCard={draw,render,cleanUrl,cardText};
})();
