(()=>{'use strict';
const E=()=>window.EInviteExperience,esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
let previewBase=null,previewKitId='';
function applyAndSave(next,message){previewBase=null;previewKitId='';state=E().migrate(next);apply();save();window.uiToast?.(message,'✦');renderExperience();}
function previewKit(id){if(!previewBase)previewBase=E().copy(state);previewKitId=id;state=E().migrate(E().applyKit(E().copy(previewBase),id));apply();window.uiToast?.('Style preview is temporary until you apply it.','◌');renderExperience('styles');}
function keepPreview(message='Style kit applied'){if(!previewBase)return;previewBase=null;previewKitId='';save();window.uiToast?.(message,'✦');renderExperience('styles');}
function cancelPreview(message='Style preview cancelled'){if(!previewBase)return;state=E().migrate(previewBase);previewBase=null;previewKitId='';apply();if(message)window.uiToast?.(message,'↶');renderExperience('styles');}
function sceneOptions(){return[
 ['soft-monogram','Soft Monogram','#fff7f4','#e8cfd1','#6f3c4a'],['royal-khmer-gate','Royal Khmer Gate','#2f1b10','#8a5b16','#f4d98f'],['silk-curtain','Silk Curtain','#4a111d','#a43d4f','#fff1d5'],['floral-reveal','Floral Reveal','#fffaf8','#e7c5ca','#754c57'],['cinematic-photo','Cinematic Photo','#121212','#555','#fff'],['minimal-editorial','Minimal Editorial','#f4efe7','#ddd2c2','#171717']];}
function stylePanel(){const preview=previewBase?`<div class="ei-kit-preview-banner" role="status"><div><strong>Previewing ${esc(E().kits[previewKitId]?.name||'style kit')}</strong><small>This preview has not been saved.</small></div><button id="eiCancelKitPreview">Cancel</button><button id="eiKeepKitPreview" class="primary">Apply preview</button></div>`:'';return `${preview}<div class="ei-style-grid">${Object.values(E().kits).map(k=>`<article class="ei-style-card ${state.styleKit?.id===k.id?'is-active':''}"><div class="ei-style-preview" style="background:linear-gradient(145deg,${k.preview[2]},${k.preview[1]});color:${k.preview[0]}"><span>${esc(k.name)}</span></div><div class="ei-style-copy"><small>${esc(k.category)}</small><h3>${esc(k.name)}</h3><p>${esc(k.description)}</p><div class="ei-style-actions"><button data-preview-kit="${k.id}">Preview</button><button class="primary" data-apply-kit="${k.id}">Apply</button></div></div></article>`).join('')}</div><div class="ei-exp-footer"><label>Desktop layout <select id="eiDesktopLayout"><option value="ambient-frame">Ambient Frame</option><option value="editorial-split">Editorial Split</option><option value="full-width">Full Width</option></select></label><button id="eiRestoreDefaults">Restore template defaults</button></div>`;}
function openingPanel(){const o=state.openingScene||E().openingDefaults;return `<div class="ei-scene-grid">${sceneOptions().map(([id,name,a,b,t])=>`<button class="ei-scene-card ${o.id===id?'is-active':''}" data-scene="${id}" style="--scene-a:${a};--scene-b:${b};--scene-text:${t}"><span>✦</span><strong>${name}</strong></button>`).join('')}</div><div class="ei-field-grid" style="margin-top:18px"><label>Optional monogram<input id="eiMonogram" maxlength="8" value="${esc(o.monogram||'')}"></label><label>Subtitle<input id="eiOpeningSubtitle" maxlength="120" value="${esc(o.subtitle||'')}"></label><label>Enter button — English<input id="eiEnterText" maxlength="40" value="${esc(o.enterText||'Open invitation')}"></label><label>Enter button — Khmer<input id="eiEnterTextKm" class="khmer-text" maxlength="60" value="${esc(o.enterTextKm||'បើកការអញ្ជើញ')}"></label><label>Background color<input id="eiOpeningColor" type="color" value="${/^#[0-9a-f]{6}$/i.test(o.backgroundColor||'')?o.backgroundColor:'#fff8f2'}"></label><label>Background image<div class="ei-inline-field"><input id="eiOpeningImage" value="${esc(o.backgroundImage||'')}" placeholder="Choose an uploaded image"><button type="button" id="eiChooseOpeningImage">Choose material</button></div></label><label>Text variant<select id="eiOpeningText"><option value="dark">Dark text</option><option value="light">Light text</option></select></label><label>Scene duration<input id="eiOpeningDuration" type="range" min="400" max="2500" step="100" value="${Math.max(400,Math.min(2500,Number(o.duration||1100)))}"></label></div><label><input id="eiOpeningDecor" type="checkbox" ${o.decorative!==false?'checked':''}> Decorative elements</label><label><input id="eiOpeningSkip" type="checkbox" ${o.skipAllowed!==false?'checked':''}> Allow skip / enter immediately</label><div class="ei-exp-footer"><button id="eiSaveOpening" class="primary">Save opening scene</button></div>`;}
function renderExperience(tab='styles'){const body=document.querySelector('#eiExperienceBody');if(!body)return;document.querySelectorAll('[data-ei-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.eiTab===tab)));if(tab==='styles')body.innerHTML=stylePanel();else if(tab==='opening')body.innerHTML=openingPanel();else return;bind(body,tab);}
function bind(body,tab){
 if(tab==='styles'){
  body.querySelector('#eiKeepKitPreview')?.addEventListener('click',()=>keepPreview());body.querySelector('#eiCancelKitPreview')?.addEventListener('click',()=>cancelPreview());
  const dl=body.querySelector('#eiDesktopLayout');dl.value=state.desktopGuestLayout||'ambient-frame';dl.onchange=()=>{if(previewBase)cancelPreview('');state.desktopGuestLayout=dl.value;state.styleKit={...(state.styleKit||{}),overrides:{...(state.styleKit?.overrides||{}),desktopLayout:dl.value}};save()};
  body.querySelectorAll('[data-apply-kit]').forEach(b=>b.onclick=()=>{const base=previewBase||state;applyAndSave(E().applyKit(E().copy(base),b.dataset.applyKit),'Style kit applied')});
  body.querySelectorAll('[data-preview-kit]').forEach(b=>b.onclick=()=>previewKit(b.dataset.previewKit));
  body.querySelector('#eiRestoreDefaults').onclick=()=>applyAndSave(E().restoreDefaults(previewBase||state),'Template defaults restored');
 }
 if(tab==='opening'){
  body.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{state.openingScene={...(state.openingScene||E().openingDefaults),id:b.dataset.scene};renderExperience('opening')});
  body.querySelector('#eiOpeningText').value=state.openingScene?.textVariant||'dark';
  body.querySelector('#eiChooseOpeningImage')?.addEventListener('click',()=>typeof openMaterialPicker==='function'?openMaterialPicker('Choose opening background',(url)=>{body.querySelector('#eiOpeningImage').value=url}):window.uiToast?.('Open Materials and copy an uploaded image URL.','!'));
  body.querySelector('#eiSaveOpening').onclick=()=>{state.openingScene={...(state.openingScene||E().openingDefaults),monogram:body.querySelector('#eiMonogram').value.trim(),subtitle:body.querySelector('#eiOpeningSubtitle').value.trim(),enterText:body.querySelector('#eiEnterText').value.trim()||'Open invitation',enterTextKm:body.querySelector('#eiEnterTextKm').value.trim()||'បើកការអញ្ជើញ',backgroundColor:body.querySelector('#eiOpeningColor').value,backgroundImage:body.querySelector('#eiOpeningImage').value.trim(),textVariant:body.querySelector('#eiOpeningText').value,duration:Number(body.querySelector('#eiOpeningDuration').value),decorative:body.querySelector('#eiOpeningDecor').checked,skipAllowed:body.querySelector('#eiOpeningSkip').checked};state.openingStyle=state.openingScene.id;const legacy=document.querySelector('#openingStyle');if(legacy)legacy.value=state.openingStyle;save();window.uiToast?.('Opening scene saved','✦')};
 }
}
function init(){
 if(!document.body.matches('[data-page="editor"],[data-page="index"]'))return;state=E().migrate(state);
 const focus=document.createElement('button');focus.id='eiFocusToggle';focus.className='ei-focus-toggle';focus.textContent='Focus';focus.setAttribute('aria-pressed',localStorage.getItem('einvite-focus-mode')==='true'?'true':'false');focus.onclick=()=>{const on=focus.getAttribute('aria-pressed')!=='true';focus.setAttribute('aria-pressed',String(on));document.body.classList.toggle('ei-focus-mode',on);localStorage.setItem('einvite-focus-mode',String(on))};if(focus.getAttribute('aria-pressed')==='true')document.body.classList.add('ei-focus-mode');
 const launch=document.createElement('button');launch.className='primary ei-experience-launch';launch.textContent='Style & Experience';launch.setAttribute('aria-haspopup','dialog');document.body.append(focus,launch);
 const dialog=document.createElement('dialog');dialog.id='eiExperienceDialog';dialog.className='ei-experience-dialog';dialog.innerHTML=`<div class="ei-exp-head"><div><small>Visual experience</small><h2>Invitation Style & Flow</h2></div><div class="ei-exp-tabs" role="tablist"><button data-ei-tab="styles" aria-selected="true">Style Kits</button><button data-ei-tab="opening">Opening</button><button data-ei-tab="storyboard">Storyboard</button><button data-ei-tab="social">Share Card</button><button data-ei-tab="checks">Design Check</button></div><button id="eiExperienceClose" aria-label="Close experience studio">×</button></div><div class="ei-exp-body" id="eiExperienceBody"></div>`;document.body.append(dialog);
 launch.onclick=()=>{renderExperience('styles');dialog.showModal()};dialog.querySelector('#eiExperienceClose').onclick=()=>dialog.close();dialog.querySelectorAll('[data-ei-tab]').forEach(b=>b.onclick=()=>{const tab=b.dataset.eiTab;if(previewBase&&tab!=='styles')cancelPreview('');if(tab==='storyboard')window.EInviteStoryboard?.render(dialog.querySelector('#eiExperienceBody'));else if(tab==='social')window.EInviteSocialCard?.render(dialog.querySelector('#eiExperienceBody'));else if(tab==='checks')window.EInviteStoryboard?.renderChecks(dialog.querySelector('#eiExperienceBody'));else renderExperience(tab);document.querySelectorAll('[data-ei-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)))});dialog.addEventListener('close',()=>{if(previewBase)cancelPreview('');launch.focus()});
 const quick=document.createElement('div');quick.className='ei-quick-toolbar';quick.hidden=true;quick.innerHTML='<button data-q="duplicate" title="Duplicate" aria-label="Duplicate selected object">⧉</button><button data-q="front" title="Bring forward" aria-label="Bring selected object forward">↑</button><button data-q="back" title="Send backward" aria-label="Send selected object backward">↓</button><button data-q="delete" title="Delete" aria-label="Delete selected object">⌫</button><button data-q="advanced" title="Advanced inspector" aria-label="Open advanced inspector">•••</button>';document.body.append(quick);
 document.addEventListener('click',()=>setTimeout(()=>quick.hidden=!document.querySelector('.selected,[data-selected="true"]'),0),true);quick.querySelector('[data-q="delete"]').onclick=()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Delete',bubbles:true}));quick.querySelector('[data-q="duplicate"]').onclick=()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'d',ctrlKey:true,bubbles:true}));quick.querySelector('[data-q="front"]').onclick=()=>document.querySelector('[data-arrange="forward"]')?.click();quick.querySelector('[data-q="back"]').onclick=()=>document.querySelector('[data-arrange="backward"]')?.click();quick.querySelector('[data-q="advanced"]').onclick=()=>document.querySelector('.right')?.scrollIntoView({behavior:'smooth'});
}
window.renderExperience=renderExperience;window.EInviteStyleKitUI={previewKit,keepPreview,cancelPreview};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
