const $=s=>document.querySelector(s);localStorage.removeItem('sovan-auth-token');
let templates=[];
function setTemplateState(state,message=''){const grid=$('#studioGrid');document.documentElement.dataset.templatesState=state;if(grid){grid.dataset.loadState=state;grid.setAttribute('aria-busy',String(state==='loading'));if(message)grid.dataset.loadMessage=message;else delete grid.dataset.loadMessage}}
const clone=v=>structuredClone(v);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',}});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
function palette(doc){const p=doc?.palette||{};return{background:p.background||'#fff7f3',text:p.text||'#342c26',heading:p.heading||doc?.accent||'#9d4555'}}
function strip(value){const d=document.createElement('div');d.innerHTML=String(value||'');return d.textContent||''}
function titleOf(t){return strip(t.document?.objects?.title?.html||t.document?.fields?.names||t.name).slice(0,55)}
function thumb(t){const p=palette(t.document),pages=t.document?.designPages||[];return `<div class="studio-thumb" style="--thumb-bg:${p.background};--thumb-heading:${p.heading}"><strong>${esc(titleOf(t))}</strong><span class="page-stack">${pages.slice(0,5).map(()=>'<i></i>').join('')}</span></div>`}
function filtered(){const q=$('#studioSearch').value.trim().toLowerCase(),category=$('#studioCategory').value,source=$('#studioSource')?.value||'all',favorites=$('#studioFavorites').checked;return templates.filter(t=>(source==='all'||source==='builtin'&&t.source==='builtin'||source==='mine'&&t.source==='mine'||source==='marketplace'&&t.source==='marketplace')&&(category==='all'||t.category===category)&&(!favorites||t.favorite)&&(!q||`${t.name} ${t.description||''} ${(t.tags||[]).join(' ')}`.toLowerCase().includes(q)))}
function render(){const grid=$('#studioGrid'),items=filtered();grid.innerHTML=items.length?'':'<div class="empty"><h2>No templates match these filters</h2><p>Try another category or template source.</p></div>';items.forEach(t=>{const readOnly=t.source!=='mine';const card=document.createElement('article');card.className='studio-card';card.innerHTML=`${thumb(t)}<div class="studio-body"><div class="studio-title"><div><h2>${esc(t.name)}</h2><span class="meta">${esc(t.category)} · ${t.source==='builtin'?'Built-in':t.source==='marketplace'?'Marketplace':'Your template'}</span></div>${readOnly?'':`<button class="star${t.favorite?' active':''}" title="Favorite" aria-label="Toggle favorite">★</button>`}</div><p>${esc(t.description||'Reusable invitation design')}</p><div class="tags">${(t.tags||[]).map(x=>`<span>${esc(x)}</span>`).join('')}<span class="version-badge">${t.source==='builtin'?'Built-in':t.source==='marketplace'?`${esc(t.licenseType||'personal')} license`:t.marketplaceStatus==='pending'?'Pending review':t.marketplaceStatus==='rejected'?'Review rejected':`v${t.currentVersion||1}`}</span></div><div class="studio-actions"><button data-action="preview">Preview</button><button data-action="use" class="primary">Use</button>${readOnly?'':`<button data-action="edit-design">Edit design</button><button data-action="meta">Details</button><button data-action="versions">Versions</button><button data-action="visibility">${t.visibility==='public'?'Remove from marketplace':'Publish to marketplace'}</button><button data-action="duplicate">Duplicate</button><button data-action="delete" class="danger">Delete</button>`}</div></div>`;card.querySelector('.star')?.addEventListener('click',()=>favorite(t));card.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions(b.dataset.action,t));grid.append(card)});setTemplateState(items.length?'loaded':'empty')}
async function load(){
 setTemplateState('loading');
 const grid=$('#studioGrid');if(grid)grid.innerHTML='<div class="empty template-loading"><h2>Loading templates…</h2></div>';
 if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;
 if(window.EInviteBackend&&!window.EInviteBackend.isAvailable()){
  templates=(window.EInviteBuiltinTemplates||[]).map(t=>({...clone(t),source:'builtin'}));$('#studioAccount').textContent='Static preview';render();
  const notice=document.createElement('div');notice.className='server-required-v14';notice.innerHTML='<strong>Built-in template preview</strong><p>Creating server invitations, personal templates, marketplace publishing, and version history require the full application server.</p>';$('#studioGrid')?.before(notice);return;
 }
 try{
  const me=await api('/api/auth/me');if(!me.user){$('#studioGrid').innerHTML='<div class="empty template-error"><h2>Sign in to manage templates</h2><p>Authentication is required for personal and marketplace templates.</p></div>';setTemplateState('error','Authentication required');return}
  $('#studioAccount').textContent=me.user.email;
  const [mine,marketplace]=await Promise.all([api('/api/templates'),api('/api/template-marketplace').catch(()=>[])]);
  const builtins=(window.EInviteBuiltinTemplates||[]).map(t=>({...clone(t),source:'builtin'})),own=mine.map(t=>({...t,source:'mine'})),ownIds=new Set(own.map(t=>t.id)),shared=marketplace.filter(t=>!ownIds.has(t.id)).map(t=>({...t,source:'marketplace'}));templates=[...builtins,...own,...shared];render();
 }catch(error){$('#studioGrid').innerHTML=`<div class="empty template-error"><h2>Template Studio needs the local backend</h2><p>${esc(error.message)}</p></div>`;setTemplateState('error',error.message)}
}
async function favorite(t){if(window.EInviteBackend&&!window.EInviteBackend.isAvailable())return window.EInviteBackend.message($('#studioGrid'));try{const updated=await api(`/api/templates/${t.id}`,{method:'PUT',body:JSON.stringify({favorite:!t.favorite})});templates[templates.findIndex(x=>x.id===t.id)]=updated;render()}catch(error){alert(error.message)}}
async function actions(action,t){if(action==='preview')return preview(t);if(window.EInviteBackend&&!window.EInviteBackend.isAvailable())return window.EInviteBackend.message($('#studioGrid'));if(action==='use')return useTemplate(t,false);if(action==='edit-design')return useTemplate(t,true);if(action==='meta')return editMeta(t);if(action==='versions')return versions(t);if(action==='visibility'){const makePublic=t.visibility!=='public',message=makePublic?'Publish this template to the shared marketplace? Anyone using this server will be able to create invitations from it.':'Remove this template from the shared marketplace? Existing invitations created from it will not be affected.';if(!(await uiConfirm(message,{title:makePublic?'Publish template':'Remove from marketplace',confirmText:makePublic?'Publish':'Remove'})))return;try{const updated=await api(`/api/templates/${t.id}`,{method:'PUT',body:JSON.stringify({visibility:makePublic?'public':'private'})});templates[templates.findIndex(x=>x.id===t.id)]=updated;render()}catch(error){alert(error.message)}return}if(action==='duplicate'){try{const copy=await api(`/api/templates/${t.id}/duplicate`,{method:'POST',body:'{}'});templates.unshift(copy);render()}catch(error){alert(error.message)}return}if(action==='delete'){if(!(await uiConfirm(`Delete template “${t.name}” and its version history?`,{title:'Delete template',danger:true,confirmText:'Delete permanently'})))return;try{await api(`/api/templates/${t.id}`,{method:'DELETE'});templates=templates.filter(x=>x.id!==t.id);render()}catch(error){alert(error.message)}}}
async function useTemplate(t,editDesign){if(window.EInviteBackend&&!window.EInviteBackend.isAvailable())return window.EInviteBackend.message($('#studioGrid'));const name=await uiPrompt(editDesign?'Name the temporary invitation used to edit this template:':'Choose a name for the new invitation:',editDesign?`${t.name} — Template Edit`:'New Invitation',{title:editDesign?'Edit template design':'Create from template',confirmText:'Continue'});if(!name)return;try{const doc=clone(t.document);doc.fields={...(doc.fields||{}),names:name};const item=await api('/api/invitations',{method:'POST',body:JSON.stringify({slug:name,document:doc})});localStorage.setItem('sovan-active-invite',item.id);location.href=`/invitations/${encodeURIComponent(item.id)}/editor${editDesign?`?templateEdit=${encodeURIComponent(t.id)}`:''}`}catch(error){alert(error.message)}}
function previewPage(page,master){const bg=page.useMasterBackground&&master?.enabled?master:page;const image=bg?.backgroundImage?`background-image:linear-gradient(rgba(0,0,0,${Number(bg.backgroundOverlay||0)/100}),rgba(0,0,0,${Number(bg.backgroundOverlay||0)/100})),url('${esc(bg.backgroundImage)}');background-size:${bg.backgroundSize||'cover'};background-position:center;`:'';return `<div class="preview-page" style="--page-bg:${esc(bg?.background||'#fff')};${image}"><strong>${esc(page.name||'Visual page')}</strong></div>`}
function preview(t){const p=palette(t.document),pages=t.document?.designPages||[];$('#studioDialogBody').innerHTML=`<div class="studio-preview"><div class="preview-phone"><div class="preview-screen" style="--p-bg:${p.background};--p-text:${p.text};--p-heading:${p.heading}"><div class="preview-hero"><h2>${esc(titleOf(t))}</h2></div>${pages.map(x=>previewPage(x,t.document.masterPageStyle)).join('')}</div></div><div><p class="invite-kicker">${esc(t.category)}</p><h1>${esc(t.name)}</h1><p>${esc(t.description||'')}</p><p><strong>Current version:</strong> ${t.currentVersion||1}</p><p><strong>Visual pages:</strong> ${pages.length}</p><p><strong>Sections:</strong> ${(t.document?.sectionOrder||[]).filter(x=>!String(x).startsWith('page:')).join(', ')}</p><div class="tags">${(t.tags||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><button id="previewUse" class="primary">Create invitation from this template</button></div></div>`;$('#previewUse').onclick=()=>{$('#studioDialog').close();useTemplate(t,false)};$('#studioDialog').showModal()}
function editMeta(t){$('#studioDialogBody').innerHTML=`<h1>Edit template details</h1><form id="metaForm" class="form-grid"><label>Name<input id="metaName" value="${esc(t.name)}" required maxlength="120"></label><label>Category<select id="metaCategory"><option>Wedding</option><option>Birthday</option><option>Business</option><option>Other</option></select></label><label class="wide">Description<textarea id="metaDescription" maxlength="500">${esc(t.description||'')}</textarea></label><label class="wide">Tags — comma separated<input id="metaTags" value="${esc((t.tags||[]).join(', '))}"></label><label>Marketplace license<select id="metaLicense"><option value="personal">Personal use</option><option value="commercial">Commercial use</option><option value="extended">Extended studio use</option></select></label><div class="wide dialog-actions"><button class="primary">Save details</button></div></form>`;$('#metaCategory').value=['Wedding','Birthday','Business','Other'].includes(t.category)?t.category:'Other';$('#metaLicense').value=['personal','commercial','extended'].includes(t.licenseType)?t.licenseType:'personal';$('#metaForm').onsubmit=async e=>{e.preventDefault();try{const updated=await api(`/api/templates/${t.id}`,{method:'PUT',body:JSON.stringify({name:$('#metaName').value.trim(),category:$('#metaCategory').value,description:$('#metaDescription').value.trim(),tags:$('#metaTags').value.split(',').map(x=>x.trim()).filter(Boolean),licenseType:$('#metaLicense').value})});templates[templates.findIndex(x=>x.id===t.id)]=updated;$('#studioDialog').close();render()}catch(error){alert(error.message)}};$('#studioDialog').showModal()}
async function versions(t){try{const items=await api(`/api/templates/${t.id}/versions`);$('#studioDialogBody').innerHTML=`<h1>Version history — ${esc(t.name)}</h1><p>Restoring an older version creates a new current version, so history remains intact.</p><div>${items.map(v=>`<div class="version-row"><strong>Version ${v.version}</strong><span>${new Date(v.createdAt).toLocaleString()}</span>${v.version===(t.currentVersion||1)?'<span class="version-badge">Current</span>':`<button data-version="${v.version}">Restore</button>`}</div>`).join('')}</div>`;$('#studioDialogBody').querySelectorAll('[data-version]').forEach(b=>b.onclick=async()=>{if(!(await uiConfirm(`Restore version ${b.dataset.version} as a new current version?`,{title:'Restore template version',confirmText:'Restore'})))return;try{const updated=await api(`/api/templates/${t.id}/restore`,{method:'POST',body:JSON.stringify({version:Number(b.dataset.version)})});templates[templates.findIndex(x=>x.id===t.id)]=updated;$('#studioDialog').close();render()}catch(error){alert(error.message)}});$('#studioDialog').showModal()}catch(error){alert(error.message)}}
$('#studioClose').onclick=()=>$('#studioDialog').close();$('#refreshBtn').onclick=load;$('#studioSearch').oninput=render;$('#studioCategory').onchange=render;$('#studioSource').onchange=render;$('#studioFavorites').onchange=render;load();
