const $=s=>document.querySelector(s);localStorage.removeItem('sovan-auth-token');
const fmtBytes=n=>{n=Number(n||0);if(n<1e6)return `${(n/1e3).toFixed(n<1e5?1:0)} KB`;if(n<1e9)return `${(n/1e6).toFixed(n<1e8?1:0)} MB`;return `${(n/1e9).toFixed(1)} GB`};
const _isKm=()=>(window.EInviteI18n&&window.EInviteI18n.get?window.EInviteI18n.get():(document.documentElement.lang||'').toLowerCase()).startsWith('km');
const _txt=(en,km)=>_isKm()?(km!=null?km:en):en;
let _accountState={};
function renderStaticTexts(){if($('#emailVerificationStatus'))$('#emailVerificationStatus').textContent=_accountState.verified?_txt('Verified','Verified'):_txt('Not verified','Not verified');if($('#usageNote'))$('#usageNote').textContent=_accountState.enforced?_txt('Your plan limits are currently enforced.','Your plan limits are currently enforced.'):_txt('Usage limits are informational in this development build; an administrator can assign plans manually.','Usage limits are informational in this development build; an administrator can assign plans manually.');if($('#accountUploadPermission'))$('#accountUploadPermission').textContent=_accountState.uploadEnabled?_txt('Allowed','Allowed'):_txt('Disabled by administrator','Disabled by administrator')}
function installAppearanceSetting(){
 const grid=$('.account-grid'),profile=grid?.querySelector('.account-card');if(!grid||!profile||$('#accountAppearance'))return;
 const card=document.createElement('section');card.className='account-card';card.id='accountAppearance';
 card.innerHTML='<h2><span class="i18n i18n-en">Appearance</span><span class="i18n i18n-km khmer-text" lang="km">Appearance</span></h2><p class="download-note"><span class="i18n i18n-en">Choose the interface used on this device.</span><span class="i18n i18n-km khmer-text" lang="km">Choose the interface used on this device.</span></p><div class="account-appearance-actions" role="group" aria-label="Interface appearance"><button type="button" data-account-theme="light"><span class="i18n i18n-en">☀ Light</span><span class="i18n i18n-km khmer-text" lang="km">☀ Light</span></button><button type="button" data-account-theme="dark"><span class="i18n i18n-en">☾ Dark</span><span class="i18n i18n-km khmer-text" lang="km">☾ Dark</span></button></div>';
 profile.after(card);
 const refresh=()=>{const mode=localStorage.getItem('einvite-theme-mode')==='dark'?'dark':'light';card.querySelectorAll('[data-account-theme]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.accountTheme===mode)))};
 card.addEventListener('click',event=>{const button=event.target.closest('[data-account-theme]');if(!button)return;const mode=button.dataset.accountTheme;localStorage.setItem('einvite-theme-mode',mode);if(window.EInviteThemeController)window.EInviteThemeController.applyTheme(mode,true);else{document.documentElement.dataset.theme=mode;document.documentElement.dataset.themeMode=mode;document.documentElement.style.colorScheme=mode}refresh()});
 refresh();
}
async function request(path,options={}){const r=await fetch(path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
async function showUploadPermission(){try{if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable())return;const me=await request('/api/auth/me');if(!me.user)return;let row=$('#accountUploadPermission')?.closest('div');if(!row){row=document.createElement('div');const label=document.createElement('small'),value=document.createElement('strong');label.textContent=_txt('Upload permission','Upload permission');value.id='accountUploadPermission';row.append(label,value);$('#accountPlan')?.closest('div')?.after(row)}const enabled=Boolean(me.user.uploadEnabled??me.user.upload_enabled??true);_accountState.uploadEnabled=enabled;$('#accountUploadPermission').textContent=enabled?_txt('Allowed','Allowed'):_txt('Disabled by administrator','Disabled by administrator')}catch(_){}}
async function init(){if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable()){window.EInviteBackend.message(document.querySelector('main')||document.body,'<span class="i18n i18n-en">Account security, sessions, MFA, passkeys, privacy export, and server storage require the full application server.</span><span class="i18n i18n-km khmer-text" lang="km">Account security, sessions, MFA, passkeys, privacy export, and server storage require the full application server.</span>');return}try{const [me,usage]=await Promise.all([request('/api/auth/me'),request('/api/account/usage')]);if(!me.user)throw Error('Sign in required');$('#accountEmail').textContent=me.user.email;$('#accountRole').textContent=me.user.role||'customer';$('#accountPlan').textContent=(usage.plan||me.user.plan||'free').replace(/^./,c=>c.toUpperCase());const verified=Boolean(me.user.emailVerified??me.user.email_verified);_accountState.verified=verified;$('#emailVerificationStatus').textContent=verified?_txt('Verified','Verified'):_txt('Not verified','Not verified');$('#requestVerification').hidden=verified;const u=usage.usage||{},l=usage.limits||{};$('#usageInvitations').textContent=`${u.invitations||0} / ${l.invitations??'—'}`;$('#usageTemplates').textContent=`${u.templates||0} / ${l.templates??'—'}`;$('#usageStorage').textContent=`${fmtBytes(u.storageBytes)} / ${fmtBytes(l.storageBytes)}`;$('#usageNote').textContent=usage.enforced?_txt('Your plan limits are currently enforced.','Your plan limits are currently enforced.'):_txt('Usage limits are informational in this development build; an administrator can assign plans manually.','Usage limits are informational in this development build; an administrator can assign plans manually.');_accountState.enforced=usage.enforced}catch(error){window.EInviteBackend?.message(document.querySelector('main')||document.body,error.message||_txt('Sign in through the full application server to manage this account.','Sign in through the full application server to manage this account.'))}}
$('#passwordForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),status=$('#passwordStatus');if(data.newPassword!==data.confirmPassword){status.textContent=_txt('The new passwords do not match.','The new passwords do not match.');return}status.textContent=_txt('Changing password…','Changing password…');try{await request('/api/auth/password',{method:'PUT',body:JSON.stringify({currentPassword:data.currentPassword,newPassword:data.newPassword})});e.target.reset();status.textContent=_txt('Password changed. Other signed-in sessions were ended.','Password changed. Other signed-in sessions were ended.')}catch(err){status.textContent=err.message}}
$('#exportAccount').onclick=async()=>{const status=$('#exportStatus');status.textContent=_txt('Preparing export…','Preparing export…');try{const data=await request('/api/account/export'),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`e-invitation-website-account-export-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent=_txt('Export downloaded.','Export downloaded.')}catch(err){status.textContent=err.message}}
installAppearanceSetting();init();showUploadPermission();

$('#requestVerification').onclick=async()=>{const status=$('#verificationMessage');status.textContent=_txt('Sending verification email…','Sending verification email…');try{const result=await request('/api/auth/verification/request',{method:'POST',body:'{}'});status.innerHTML=result.verified?_txt('Your email is already verified.','Your email is already verified.'):result.sent?_txt('Verification email sent.','Verification email sent.'):_txt('Verification token created, but SMTP delivery is not configured.','Verification token created, but SMTP delivery is not configured.');if(result.devToken)status.innerHTML+=` <a href="verify.html?token=${encodeURIComponent(result.devToken)}"><span class="i18n i18n-en">Development verification link</span><span class="i18n i18n-km khmer-text" lang="km">Development verification link</span></a>`}catch(error){status.textContent=error.message}};
if(window.EInviteI18n&&typeof window.EInviteI18n.subscribe==='function'){window.EInviteI18n.subscribe(renderStaticTexts)}
