const $=s=>document.querySelector(s),inviteId=window.EInviteContext?.getInvitationId();localStorage.removeItem('sovan-auth-token');
const _isKm=()=>(window.EInviteI18n&&window.EInviteI18n.get?window.EInviteI18n.get():(document.documentElement.lang||'').toLowerCase()).startsWith('km');
const _txt=(en,km)=>_isKm()?(km!=null?km:en):en;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=(en,km)=>`<span class="i18n i18n-en">${esc(en)}</span><span class="i18n i18n-km khmer-text" lang="km">${esc(km!=null?km:en)}</span>`;
let _analyticsData=null,_analyticsInvite=null;
async function api(path){const r=await fetch(path,{credentials:'same-origin',headers:{}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
function last30Days(){const days=[];const now=new Date();for(let i=29;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);days.push(d.toISOString().slice(0,10))}return days}
function render(data,invite){_analyticsData=data;_analyticsInvite=invite;const days=last30Days(),max=Math.max(1,...days.map(day=>Number(data.viewsByDay?.[day]||0))),statuses=Object.entries(data.rsvpStatuses||{}).sort((a,b)=>b[1]-a[1]),checkRate=data.guestListTotal?Math.round(data.checkedIn/data.guestListTotal*100):0;const names=invite.document?.fields?.names||_txt('Invitation','Invitation');$('#analyticsTitle').innerHTML=`${names} · ${location.origin}/i/${invite.slug}`;$('#analyticsRoot').innerHTML=`<div class="metric-grid"><div class="metric"><span>${b('Total views','Total views')}</span><strong>${data.totalViews||0}</strong><small>${b('All-time public opens','All-time public opens')}</small></div><div class="metric"><span>${b('Last 30 days','Last 30 days')}</span><strong>${data.views30Days||0}</strong><small>${b('Recent invitation opens','Recent invitation opens')}</small></div><div class="metric"><span>${data.rsvpEnabled===false?_txt('RSVP','RSVP'):_txt('RSVP responses','RSVP responses')}</span><strong>${data.rsvpEnabled===false?_txt('Disabled','Disabled'):(data.rsvpTotal||0)}</strong><small>${data.rsvpEnabled===false?b('Historical responses are preserved','Historical responses are preserved'):`${data.rsvpGuests||0} ${_txt('total responding guests','total responding guests')}`}</small></div><div class="metric"><span>${b('Checked in','Checked in')}</span><strong>${data.checkedIn||0}</strong><small>${data.guestListTotal||0} ${_txt('guests on list','guests on list')}</small></div></div><div class="analytics-grid"><section class="chart-card"><h2>${b('Views — last 30 days','Views — last 30 days')}</h2><div class="bars">${days.map(day=>{const value=Number(data.viewsByDay?.[day]||0),height=Math.max(1,Math.round(value/max*100));return`<div class="bar-wrap" data-label="${day}: ${value} ${_txt('view','view')}${value===1?'':'s'}"><span class="bar" style="height:${height}%"></span></div>`}).join('')}</div></section><aside class="summary-card"><h2>${b('RSVP breakdown','RSVP breakdown')}</h2>${data.rsvpEnabled===false?`<p>${b('RSVP disabled for this invitation. Historical response data remains available.','RSVP disabled for this invitation. Historical response data remains available.')}</p>`:statuses.length?statuses.map(([name,count])=>`<div class="status-row"><span>${esc(name)}</span><strong>${count}</strong></div>`).join(''):`<p>${b('No RSVP responses yet.','No RSVP responses yet.')}</p>`}<h2>${b('Guest check-in','Guest check-in')}</h2><div class="progress"><span style="width:${checkRate}%"></span></div><p><strong>${checkRate}%</strong> ${_txt('of listed guests checked in.','of listed guests checked in.')}</p><h2>${b('Publishing','Publishing')}</h2><p>${b('Public slug:','Public slug:')} <code>${esc(invite.slug)}</code></p><p>${b('Access:','Access:')} ${esc(invite.accessMode||'unlisted')}</p></aside></div>`}
async function load(){if(!inviteId)return window.EInviteBackend?.message($('#analyticsRoot'),'<span class="i18n i18n-en">Open analytics from a specific invitation.</span><span class="i18n i18n-km khmer-text" lang="km">Open analytics from a specific invitation.</span>');if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable())return window.EInviteBackend.message($('#analyticsRoot '),'<span class="i18n i18n-en">Analytics requires the full application server.</span><span class="i18n i18n-km khmer-text" lang="km">Analytics requires the full application server.</span>');try{const [data,invite,me]=await Promise.all([api(`/api/invitations/${inviteId}/analytics`),api(`/api/invitations/${inviteId}`),api('/api/auth/me')]);if(!me.user)return location.href='dashboard.html';$('#analyticsAccount').textContent=me.user.email;render(data,invite)}catch(error){$('#analyticsRoot').innerHTML=`<div class="empty"><h2>${b('Analytics unavailable','Analytics unavailable')}</h2><p>${esc(error.message)}</p></div>`}}
function renderAll(){if(_analyticsData&&_analyticsInvite)render(_analyticsData,_analyticsInvite)}
if(window.EInviteI18n&&typeof window.EInviteI18n.subscribe==='function'){window.EInviteI18n.subscribe(renderAll)}
$('#refreshAnalytics').onclick=load;load();
