(()=>{'use strict';
const $=s=>document.querySelector(s),inviteId=window.EInviteContext?.getInvitationId({allowRemembered:false})||window.EInviteContext?.getInvitationId()||'',queueKey=`einvite-checkin-queue:${inviteId}`;let guests=[],invitation=null,stream=null,scanTimer=null;
const api=async(path,options={})=>{const r=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const _isKm=()=>(window.EInviteI18n&&window.EInviteI18n.get?window.EInviteI18n.get():(document.documentElement.lang||'').toLowerCase()).startsWith('km');
const _txt=(en,km)=>_isKm()?(km!=null?km:en):en;
const _html=(en,km)=>{const isKm=_isKm();const v=isKm?(km!=null?km:en):en;return`<span class="i18n i18n-en">${esc(en)}</span><span class="i18n i18n-km khmer-text" lang="km">${esc(km!=null?km:en)}</span>`};
const queue=()=>{try{return JSON.parse(localStorage.getItem(queueKey)||'[]')}catch{return[]}},saveQueue=q=>localStorage.setItem(queueKey,JSON.stringify(q));
function setNetwork(){const online=navigator.onLine;$('#networkState').textContent=online?_txt('Online','Online'):_txt('Offline','Offline');$('#networkState').classList.toggle('offline',!online);renderQueue()}
function renderQueue(){const q=queue(),el=$('#pendingQueue');el.hidden=!q.length;const en=`${q.length} ${q.length===1?'check-in change':'check-in changes'} waiting to sync when the connection returns.`;el.innerHTML=q.length?`<span class="i18n i18n-en">${en}</span><span class="i18n i18n-km khmer-text" lang="km">${en}</span>`:''}
function render(){const q=$('#guestSearch').value.trim().toLowerCase(),filtered=guests.filter(g=>`${g.name} ${g.phone||''} ${g.group_name||''} ${g.table_name||''}`.toLowerCase().includes(q)),checked=guests.filter(g=>g.checked_in).length;$('#checkinSummary').innerHTML=`${checked} of ${guests.length} <span class="i18n i18n-en">guests checked in</span><span class="i18n i18n-km khmer-text" lang="km">guests checked in</span>`;$('#checkinStats').innerHTML=`<span class="checkin-stat"><strong>${checked}</strong> <span class="i18n i18n-en">in</span><span class="i18n i18n-km khmer-text" lang="km">in</span></span><span class="checkin-stat"><strong>${guests.length-checked}</strong> <span class="i18n i18n-en">remaining</span><span class="i18n i18n-km khmer-text" lang="km">remaining</span></span>`;$('#checkinList').innerHTML=filtered.map(g=>`<article class="checkin-person ${g.checked_in?'checked':''}" data-guest-id="${esc(g.id)}"><div><strong>${esc(g.name)}</strong><small>${[g.group_name,g.table_name&&`${_txt('Table','Table')} ${g.table_name}`,g.seat_label&&`${_txt('Seat','Seat')} ${g.seat_label}`,g.phone].filter(Boolean).map(esc).join(' · ')}</small></div><button data-check-id="${esc(g.id)}" class="${g.checked_in?'':'primary'}">${g.checked_in?_txt('Undo check-in','Undo check-in'):_txt('Check in','Check in')}</button></article>`).join('')||'<p class="empty-state"><span class="i18n i18n-en">No matching guests.</span><span class="i18n i18n-km khmer-text" lang="km">No matching guests.</span></p>';document.querySelectorAll('[data-check-id]').forEach(b=>b.onclick=()=>toggle(b.dataset.checkId))}
async function load(){if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable()){window.EInviteBackend.message($('#checkinList'),'<span class="i18n i18n-en">Guest check-in synchronization requires the full application server.</span><span class="i18n i18n-km khmer-text" lang="km">Guest check-in synchronization requires the full application server.</span>');$('#scanQrBtn').disabled=true;return}try{invitation=await api(`/api/invitations/${encodeURIComponent(inviteId)}`);guests=await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests`);$('#eventName').innerHTML='<span class="i18n i18n-en">'+(invitation.document?.fields?.names||'Guest check-in')+'</span><span class="i18n i18n-km khmer-text" lang="km">'+(invitation.document?.fields?.names||'Guest check-in')+'</span>';$('#backToGuests').href=window.EInviteContext.route(inviteId,'guests');render();await flushQueue()}catch(e){$('#checkinList').innerHTML=`<p><span class="i18n i18n-en">Could not load this guest list: </span><span class="i18n i18n-km khmer-text" lang="km">Could not load this guest list: </span>${esc(e.message)}</p>`}}
async function toggle(id,explicit){const g=guests.find(x=>x.id===id);if(!g)return;const checked=explicit??!g.checked_in;g.checked_in=checked;g.checked_in_at=checked?Date.now():null;render();if(!navigator.onLine){const q=queue().filter(x=>x.guestId!==id);q.push({guestId:id,checkedIn:checked,createdAt:Date.now()});saveQueue(q);renderQueue();return}try{const result=await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${encodeURIComponent(id)}/check-in`,{method:'PUT',body:JSON.stringify({checkedIn:checked})});if(result.alreadyCheckedIn){const notice=$('#checkinNotice');notice.textContent=`${g.name} ${_txt('was already checked in.','was already checked in.')}`;setTimeout(()=>{if(notice.textContent.includes(g.name))notice.textContent=''},3500)}}catch(e){const q=queue().filter(x=>x.guestId!==id);q.push({guestId:id,checkedIn:checked,createdAt:Date.now()});saveQueue(q);renderQueue()}}
async function flushQueue(){if(!navigator.onLine)return;let q=queue(),remaining=[];for(const item of q){try{await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${encodeURIComponent(item.guestId)}/check-in`,{method:'PUT',body:JSON.stringify({checkedIn:item.checkedIn})})}catch{remaining.push(item)}}saveQueue(remaining);renderQueue();if(q.length&&!remaining.length){guests=await api(`/api/invitations/${encodeURIComponent(inviteId)}/guests`);render()}}
function guestFromScanned(value){let text=String(value||'');try{const u=new URL(text,location.origin),token=u.searchParams.get('g')||u.searchParams.get('guest');if(token)return guests.find(g=>g.token===token)}catch{}return guests.find(g=>g.id===text)}
async function openScanner(){if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){alert(_txt('Camera QR scanning is not supported in this browser. Use guest search instead.','Camera QR scanning is not supported in this browser. Use guest search instead.'));return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('#scannerVideo').srcObject=stream;await $('#scannerVideo').play();$('#scannerDialog').showModal();const detector=new BarcodeDetector({formats:['qr_code']});const tick=async()=>{if(!stream)return;try{const codes=await detector.detect($('#scannerVideo'));if(codes[0]){const guest=guestFromScanned(codes[0].rawValue);if(guest){await toggle(guest.id,true);closeScanner();document.querySelector(`[data-guest-id="${CSS.escape(guest.id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});return}$('#scannerStatus').innerHTML='<span class="i18n i18n-en">This QR code does not belong to a guest in this invitation.</span><span class="i18n i18n-km khmer-text" lang="km">This QR code does not belong to a guest in this invitation.</span>'}}catch{}scanTimer=setTimeout(tick,260)};tick()}catch(e){alert(_txt('Camera could not be opened:','Camera could not be opened:')+' '+e.message)}}
function closeScanner(){clearTimeout(scanTimer);scanTimer=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('#scannerVideo').srcObject=null;$('#scannerDialog').close()}
$('#guestSearch').oninput=render;$('#scanQrBtn').onclick=openScanner;$('#closeScanner').onclick=closeScanner;$('#scannerDialog').addEventListener('close',()=>{if(stream)closeScanner()});window.addEventListener('online',()=>{setNetwork();flushQueue()});window.addEventListener('offline',setNetwork);setNetwork();load();if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});
if(window.EInviteI18n&&typeof window.EInviteI18n.subscribe==='function'){window.EInviteI18n.subscribe(function(){setNetwork();render()})}
})();
