(()=>{'use strict';
if(window.__EInviteCollaborationLiveInit)return;
window.__EInviteCollaborationLiveInit=true;
if(!document.querySelector('#stage'))return;
const $=selector=>document.querySelector(selector),life=window.EInviteLifecycle;
const clientId=sessionStorage.getItem('einvite-editor-client-id')||(crypto.randomUUID?.()||`client-${Date.now()}-${Math.random().toString(36).slice(2)}`);
sessionStorage.setItem('einvite-editor-client-id',clientId);
let knownRevision=Number(window.serverInvite?.updatedAt||0),notifiedRevision=0,pollTimer=0,presenceTimer=0,retryTimer=0,source=null,stopped=false;
const ownMutations=new Set();
const id=()=>window.serverInvite?.id||window.EInviteContext?.getInvitationId({allowRemembered:false})||'';
async function api(signal){const invitation=id();if(!invitation)throw Error('Invitation unavailable');const r=await fetch(`/api/invitations/${encodeURIComponent(invitation)}`,{credentials:'same-origin',cache:'no-store',signal});if(!r.ok)throw Error();return r.json()}
function ensureChip(){let chip=$('#eiRemoteChangeChip');if(!chip){chip=document.createElement('button');chip.id='eiRemoteChangeChip';chip.type='button';chip.className='ei-remote-chip';chip.hidden=true;chip.innerHTML='<span>↻</span><strong>Remote changes available</strong>';document.body.append(chip);chip.onclick=async()=>{if(!(await uiConfirm('Reload the latest server version? Unsaved local changes may be replaced.',{title:'Sync remote changes',confirmText:'Reload latest'})))return;location.reload()}}return chip}
function receive(change){const updated=Number(change?.updatedAt??change??0),origin=String(change?.clientId||''),mutation=String(change?.mutationId||'');if(!updated)return;if(!knownRevision){knownRevision=updated;return}if(origin===clientId||ownMutations.has(mutation)||updated<=knownRevision){knownRevision=Math.max(knownRevision,updated);return}if(updated!==notifiedRevision){notifiedRevision=updated;const chip=ensureChip();chip.hidden=false;window.uiToast?.('This invitation changed in another session.','↻')}knownRevision=Math.max(knownRevision,updated)}
function acceptLocal(detail={}){const updated=Number(detail.updatedAt||0),mutation=String(detail.mutationId||'');if(mutation)ownMutations.add(mutation);if(ownMutations.size>100)ownMutations.delete(ownMutations.values().next().value);if(updated)knownRevision=Math.max(knownRevision,updated);const chip=ensureChip();chip.hidden=true;notifiedRevision=0}
document.addEventListener('einvite:local-revision',event=>acceptLocal(event.detail||{}));
async function poll(){if(stopped||!id()||document.hidden)return;const controller=new AbortController();try{const invite=await api(controller.signal);receive({updatedAt:invite.updatedAt})}catch{}finally{controller.abort()}}
function startPolling(){if(stopped||pollTimer)return;poll();pollTimer=(life?.interval||setInterval)(poll,7000)}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=0}}
function scheduleSseRetry(){if(stopped||retryTimer)return;retryTimer=(life?.timeout||setTimeout)(()=>{retryTimer=0;if(!document.hidden)startSSE()},60000)}
function startSSE(){if(stopped)return;const invitation=id();if(!invitation||!window.EventSource){startPolling();return}try{source?.close();source=new EventSource(`/api/invitations/${encodeURIComponent(invitation)}/events`);source.addEventListener('open',stopPolling);source.addEventListener('invitation-update',event=>{try{receive(JSON.parse(event.data))}catch{}});source.onerror=()=>{source?.close();source=null;startPolling();scheduleSseRetry()}}catch{startPolling();scheduleSseRetry()}}
function ensurePresence(){let root=$('#eiPresenceStack');if(root)return root;root=document.createElement('div');root.id='eiPresenceStack';root.className='ei-presence-stack';root.hidden=true;root.setAttribute('aria-label','People currently viewing this invitation');document.body.append(root);return root}
function renderPresence(rows=[]){const others=rows.filter(x=>x.clientId!==clientId),root=ensurePresence();root.hidden=!others.length;root.replaceChildren(...others.slice(0,4).map(x=>{const span=document.createElement('span');span.className='ei-presence-avatar';span.title=String(x.email||'Collaborator');span.textContent=String(x.email||'?').trim().slice(0,1).toUpperCase();return span}));if(others.length){const label=document.createElement('span');label.className='ei-presence-label';label.textContent=`${others.length} collaborator${others.length===1?'':'s'} here`;root.append(label)}}
async function heartbeatPresence(){const invitation=id();if(stopped||!invitation||document.hidden)return;const controller=new AbortController();try{const selected=window.EInviteEditorBridge?.getSelectedIds?.()[0]||'',response=await fetch(`/api/invitations/${encodeURIComponent(invitation)}/presence`,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,mode:document.body.dataset.focusMode==='true'?'focus':'editing',selectedObjectId:selected}),signal:controller.signal});if(!response.ok)return;const payload=await response.json();renderPresence(Array.isArray(payload)?payload:(payload.presence||[]))}catch{}finally{controller.abort()}}
function stop(){if(stopped)return;stopped=true;stopPolling();if(presenceTimer){clearInterval(presenceTimer);presenceTimer=0}if(retryTimer){clearTimeout(retryTimer);retryTimer=0}source?.close();source=null}
const onVisibility=()=>{if(document.hidden)return;if(window.EInviteBackend?.isAvailable()){poll();heartbeatPresence();if(!source)startSSE()}};
document.addEventListener('visibilitychange',onVisibility);life?.add?.(()=>document.removeEventListener('visibilitychange',onVisibility));life?.add?.(stop);window.addEventListener('pagehide',stop,{once:true});
(async()=>{if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable()){stop();return}ensureChip();startSSE();heartbeatPresence();presenceTimer=(life?.interval||setInterval)(heartbeatPresence,15000)})();
window.EInviteCollaborationSync={clientId,get knownRevision(){return knownRevision},receive,acceptLocal};
})();
