#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
DATA=json.loads((ROOT/'rich-text-contract.json').read_text(encoding='utf-8'))
compact=json.dumps(DATA,ensure_ascii=False,separators=(',',':'))
js=f"""(()=>{{'use strict';
const DATA={compact};
const freezeList=key=>Object.freeze([...(DATA[key]||[])]);
window.EInviteRichTextContract=Object.freeze({{
 version:DATA.version,data:Object.freeze(DATA),
 MAX_PARAGRAPHS:DATA.maxParagraphs,MAX_RUNS:DATA.maxRuns,MAX_ENTITIES:DATA.maxEntities,
 MAX_DOCUMENT_CHARACTERS:DATA.maxDocumentCharacters,MAX_PARAGRAPH_CHARACTERS:DATA.maxParagraphCharacters,
 MAX_RUN_CHARACTERS:DATA.maxRunCharacters,MAX_TAB_STOPS:DATA.maxTabStops,MAX_LIST_DEPTH:DATA.maxListDepth,
 MAX_HTML_BYTES:DATA.maxHtmlBytes,MAX_LEGACY_NESTING:DATA.maxLegacyNesting,MAX_ID_LENGTH:DATA.maxIdLength,MAX_STYLE_ID_LENGTH:DATA.maxStyleIdLength,
 locales:freezeList('locales'),directions:freezeList('directions'),alignments:freezeList('alignments'),
 listTypes:freezeList('listTypes'),listMarkers:freezeList('listMarkers'),tabAlignments:freezeList('tabAlignments'),
 tabLeaders:freezeList('tabLeaders'),urlProtocols:freezeList('urlProtocols'),markKeys:freezeList('markKeys'),
 paragraphOverrideKeys:freezeList('paragraphOverrideKeys')
}});
}})();
"""
(ROOT/'rich-text-contract.js').write_text(js,encoding='utf-8')
py=f'''# Generated by generate_rich_text_contract.py. Do not edit.\nfrom __future__ import annotations\nDATA={repr(DATA)}\nVERSION=int(DATA["version"])\nMAX_PARAGRAPHS=int(DATA["maxParagraphs"])\nMAX_RUNS=int(DATA["maxRuns"])\nMAX_ENTITIES=int(DATA["maxEntities"])\nMAX_DOCUMENT_CHARACTERS=int(DATA["maxDocumentCharacters"])\nMAX_PARAGRAPH_CHARACTERS=int(DATA["maxParagraphCharacters"])\nMAX_RUN_CHARACTERS=int(DATA["maxRunCharacters"])\nMAX_TAB_STOPS=int(DATA["maxTabStops"])\nMAX_LIST_DEPTH=int(DATA["maxListDepth"])\nMAX_HTML_BYTES=int(DATA["maxHtmlBytes"])\nMAX_LEGACY_NESTING=int(DATA["maxLegacyNesting"])\nMAX_ID_LENGTH=int(DATA["maxIdLength"])\nMAX_STYLE_ID_LENGTH=int(DATA["maxStyleIdLength"])\nMAX_ENTITY_TITLE_LENGTH=int(DATA["maxEntityTitleLength"])\nLOCALES=frozenset(DATA["locales"])\nDIRECTIONS=frozenset(DATA["directions"])\nALIGNMENTS=frozenset(DATA["alignments"])\nLIST_TYPES=frozenset(DATA["listTypes"])\nLIST_MARKERS=frozenset(DATA["listMarkers"])\nTAB_ALIGNMENTS=frozenset(DATA["tabAlignments"])\nTAB_LEADERS=frozenset(DATA["tabLeaders"])\nURL_PROTOCOLS=frozenset(DATA["urlProtocols"])\nMARK_KEYS=frozenset(DATA["markKeys"])\nPARAGRAPH_OVERRIDE_KEYS=frozenset(DATA["paragraphOverrideKeys"])\n'''
(ROOT/'rich_text_contract.py').write_text(py,encoding='utf-8')
print('RICH_TEXT_CONTRACT_GENERATED')
