(()=>{'use strict';
function kitStyle(d){const k=window.EInviteExperience?.kits?.[d.styleKit?.id];if(!k)return'';const o=d.styleKit?.overrides||{},radius={minimal:'6px',soft:'14px',rounded:'24px'}[k.radius]||'14px',shadow={ceremonial:'0 18px 55px #5b3a1820',editorial:'0 16px 44px #17171718',soft:'0 18px 48px #754c5718'}[k.shadow]||'0 16px 42px #00000014',gap={compact:'20px',balanced:'32px',generous:'46px'}[k.spacing]||'32px';return `--kit-background:${o.background||k.background};--kit-surface:${o.surface||k.surface};--kit-text:${o.text||k.text};--kit-accent:${o.accent||k.accent};--kit-muted:${o.muted||k.muted};--kit-heading-font:${JSON.stringify(k.headingFont)};--kit-body-font:${JSON.stringify(k.bodyFont)};--kit-khmer-heading:${JSON.stringify(k.khmerHeadingFont)};--kit-khmer-body:${JSON.stringify(k.khmerBodyFont)};--kit-radius:${radius};--kit-shadow:${shadow};--kit-section-gap:${gap}`;}
function safeAmbientPhoto(d){const value=String(d.socialCard?.photo||d.openingScene?.backgroundImage||'').trim();return /^(?:https?:\/\/|\/uploads\/)/i.test(value)?value.replace(/["'()\\\n\r]/g,''):''}
function apply(root,d){
  if(root.dataset.guestLayoutApplied==='true')return;root.dataset.guestLayoutApplied='true';
  const layout=['ambient-frame','editorial-split','full-width'].includes(d.desktopGuestLayout)?d.desktopGuestLayout:'ambient-frame',kit=window.EInviteExperience?.kits?.[d.styleKit?.id];root.style.cssText += ';'+kitStyle(d);root.classList.add('style-kit-'+(d.styleKit?.id||'custom'));if(kit){root.dataset.kitButton=kit.buttonStyle||'';root.dataset.kitPhotoFrame=kit.photoFrame||'';root.dataset.kitOrnament=kit.ornament||'';root.dataset.kitDivider=kit.divider||'';root.dataset.kitMotion=kit.motion||'';}const ambient=safeAmbientPhoto(d);if(ambient)root.style.setProperty('--guest-ambient-image',`url("${ambient}")`);
  const cover=root.querySelector(':scope > #openCover');if(cover)cover.remove();const content=document.createElement('div');content.className='guest-layout-content';while(root.firstChild)content.append(root.firstChild);const shell=document.createElement('div');shell.className=`guest-layout-shell guest-layout-${layout}`;
  if(layout==='editorial-split'){const f=d.fields||{},mode=d.languageMode||'both',summary=document.createElement('aside'),names=mode==='km'?(f.namesKm||f.names):(f.names||'Invitation'),venue=mode==='km'?(f.venueKm||f.venue):(f.venue||'');summary.className='guest-layout-summary';summary.innerHTML=`<small>${mode==='km'?'សូមគោរពអញ្ជើញ':'YOU ARE INVITED'}</small><h1>${window.EInviteRenderer?.esc(names||'Invitation')}</h1><p>${window.EInviteRenderer?.esc(f.date||'')}</p><p>${window.EInviteRenderer?.esc(venue||'')}</p>`;shell.append(summary)}
  shell.append(content);root.append(shell);if(cover)root.append(cover);root.dataset.desktopLayout=layout;
  root.querySelectorAll('img').forEach((img,i)=>{if(!img.loading)img.loading=i<2?'eager':'lazy';img.decoding='async';if(!img.getAttribute('alt'))img.alt='Invitation photo';});root.querySelectorAll('section').forEach(s=>s.classList.add('guest-lazy-section'));
}
window.EInviteGuestLayouts={apply,kitStyle,safeAmbientPhoto};
})();
