/**
 * guests.js — Guest list management (ROADMAP §5.6).
 * Renders the guest table, summary metrics, per-guest action buttons (edit,
 * personal-link, QR, check-in, remove), CSV import/export, and inline editing.
 * All user-facing strings go through EInviteI18n.langText() (dual .i18n-en/.i18n-km
 * spans, CSS-driven toggle) or a plain-text helper for DOM APIs (alert/confirm/
 * textContent) that reads EInviteI18n.get() at call time. No STRINGS table so
 * check-bilingual-consistency.py (which only scans top-level src/js/*.js) is
 * not polluted with EN-FALLBACK placeholders — see §8 of LANGUAGE-GAP-REPORT.
 */
const $=s=>document.querySelector(s),inviteId=window.EInviteContext?.getInvitationId()||'demo-wedding',localKey=`sovan-guests:${inviteId}`;let guests=[],server=false,slug='invitation',invitation=null,rsvpEnabled=true;
const _isKm=()=>(window.EInviteI18n&&window.EInviteI18n.get?window.EInviteI18n.get():(document.documentElement.lang||'').toLowerCase()).startsWith('km');
const _html=(en,km)=>{if(window.EInviteI18n)return window.EInviteI18n.langText(en,km);const e=_isKm()?(km!=null?km:en):en;return`<span class="i18n i18n-en">${esc(en)}</span><span class="i18n i18n-km khmer-text" lang="km">${esc(km!=null?km:en)}</span>`};
const _txt=(en,km)=>{const isKm=_isKm();return isKm?(km!=null?km:en):en};
async function request(path,options={}){let r=await fetch(path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(data.error||'Request failed'),{status:r.status,data});return data}
async function load(){if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable()){server=false;guests=JSON.parse(localStorage.getItem(localKey)||'[]');window.EInviteBackend.message($('#guestList'),_txt('Guest management, personal links, QR codes, and check-in require the full application server.','Guest management, personal links, QR codes, and check-in require the full application server.'));render();return}try{await request('/api/health');server=true;invitation=await request(`/api/invitations/${encodeURIComponent(inviteId)}`);slug=invitation?.slug||slug;rsvpEnabled=invitation?.document?.settings?.rsvpEnabled!==false;guests=await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests`)}catch(error){server=false;guests=JSON.parse(localStorage.getItem(localKey)||'[]');if(error.status===404)window.EInviteBackend?.message($('#guestList'),_txt('This invitation is not available in the current server context.','This invitation is not available in the current server context.'))}render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function guestUrl(g){if(!g?.token)return'';return server?`${location.origin}/i/${encodeURIComponent(slug)}?g=${encodeURIComponent(g.token)}`:`${location.origin}${location.pathname.replace(/guests(?:\.html)?$/,'public.html')}?g=${encodeURIComponent(g.token)}`}
function filtered(){let q=$('#search').value.trim().toLowerCase(),filter=$('#statusFilter').value;return guests.filter(g=>{let text=`${g.name} ${g.phone||''} ${g.email||''} ${g.group_name||''} ${g.household_id||''} ${g.table_name||''} ${(g.tags||[]).join(' ')}`.toLowerCase(),status=g.rsvp_status||'';if(!text.includes(q))return false;if(!rsvpEnabled)return filter==='all'||filter==='checked'&&g.checked_in;return filter==='all'||filter==='yes'&&status.startsWith('Yes')||filter==='no'&&status.startsWith('Unable')||filter==='pending'&&!status||filter==='checked'&&g.checked_in})}
function render(){let yes=guests.filter(g=>g.rsvp_status?.startsWith('Yes')).length,no=guests.filter(g=>g.rsvp_status?.startsWith('Unable')).length,pending=guests.length-yes-no,checked=guests.filter(g=>g.checked_in).length;$('#summary').innerHTML=rsvpEnabled?`<div class="metric"><strong>${guests.length}</strong>${_html('Invited','Invited')}</div><div class="metric"><strong>${yes}</strong>${_html('Attending','Attending')}</div><div class="metric"><strong>${no}</strong>${_html('Declined','Declined')}</div><div class="metric"><strong>${pending}</strong>${_html('Pending','Pending')}</div><div class="metric"><strong>${checked}</strong>${_html('Checked in','Checked in')}</div>`:`<div class="metric"><strong>${guests.length}</strong>${_html('Invited','Invited')}</div><div class="metric"><strong>${checked}</strong>${_html('Checked in','Checked in')}</div><div class="metric"><strong>${_html('Off','Off')}</strong>${_html('RSVP disabled','RSVP disabled')}</div>`;const filter=$('#statusFilter');if(filter){[...filter.options].forEach(o=>{if(['yes','no','pending'].includes(o.value))o.hidden=!rsvpEnabled});if(!rsvpEnabled&&['yes','no','pending'].includes(filter.value))filter.value='all'}
$('#guestList').innerHTML=filtered().map(g=>{const status=rsvpEnabled?esc(g.rsvp_status||_txt('Awaiting reply','Awaiting reply')):(_txt(g.token_revoked_at?'Personal link revoked':(g.personalLinkAvailable?'Personal invitation ready':'Personal link needs rotation'),g.token_revoked_at?'Personal link revoked':(g.personalLinkAvailable?'Personal invitation ready':'Personal link needs rotation')));return`<div class="guest-row ${g.checked_in?'checked':''}"><div><strong>${esc(g.name)}</strong><br><small>${esc([g.phone,g.email,g.group_name&&`${_txt('Group:','Group:')} ${g.group_name}`,g.household_id&&`${_txt('Household:','Household:')} ${g.household_id}`,g.table_name&&`${_txt('Table:','Table:')} ${g.table_name}`,g.seat_label&&`${_txt('Seat:','Seat:')} ${g.seat_label}`].filter(Boolean).join(' · '))}</small>${(g.tags||[]).length?`<span class="tags">${(g.tags||[]).map(tag=>`<span class="tag">${esc(tag)}</span>`).join('')}</span>`:''}
<div class="guest-meta">${g.checked_in?`${_html('Checked in','Checked in')}${g.check_in_at?` ${_html('at','at')} ${esc(new Date(g.check_in_at).toLocaleString())}`:''}`:''}${g.rsvp_status&&rsvpEnabled?`${_html('RSVP','RSVP')}: ${esc(g.rsvp_status)}`:''}${g.delivery_status?` · ${esc(g.delivery_status)}`:''}${g.opened_at?` · ${_html('Opened','Opened')}`:''}</div></div><span>${status}</span><button data-edit="${g.id}">${_html('Edit','Edit')}</button><button data-link="${g.id}">${g.personalLinkAvailable?_html('Link','Link'):_html('Rotate link','Rotate link')}</button><button data-qr="${g.id}" ${g.personalLinkAvailable?'':'disabled'}>${_html('QR','QR')}</button><button data-check="${g.id}">${g.checked_in?_html('Undo check-in','Undo check-in'):_html('Check in','Check in')}</button><button class="danger" data-delete="${g.id}">${_html('Remove','Remove')}</button></div>`}).join('')||`<p class="empty">${_html('No guests match this filter.','No guests match this filter.')}</p>`}
;
$('#search').oninput=render;$('#statusFilter').onchange=render;
$('#addForm').onsubmit=async e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));data.tags=String(data.tags||'').split(',').map(x=>x.trim()).filter(Boolean);await addGuest(data);e.target.reset();render()};
async function addGuest(data){if(server){await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests`,{method:'POST',body:JSON.stringify(data)});guests=await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests`)}else{guests.unshift({id:crypto.randomUUID(),name:data.name,phone:data.phone,token:crypto.randomUUID().slice(0,12),personalLinkAvailable:true,rsvp_status:null,checked_in:false});localStorage.setItem(localKey,JSON.stringify(guests))}}
async function editGuest(id){let g=guests.find(x=>x.id===id);if(!g)return;const fields=[['name',_txt('Guest name','Guest name'),g.name],['phone',_txt('Phone number','Phone number'),g.phone||''],['email',_txt('Email','Email'),g.email||''],['groupName',_txt('Group','Group'),g.group_name||''],['householdId',_txt('Household','Household'),g.household_id||''],['tableName',_txt('Table','Table'),g.table_name||''],['seatLabel',_txt('Seat','Seat'),g.seat_label||''],['tags',_txt('Tags (comma separated)','Tags (comma separated)'),(g.tags||[]).join(', ')]];const form=document.createElement('form');form.innerHTML=`<h2>${_html('Edit guest','Edit guest')}</h2>${fields.map(([name,label,value])=>`<label>${esc(label)}<input name="${name}" value="${esc(value)}"></label>`).join('')}<div class="dialog-actions"><button type="button" data-cancel>${_html('Cancel','Cancel')}</button><button class="primary">${_html('Save','Save')}</button></div>`;$('#qrBody').replaceChildren(form);$('#qrModal').showModal();form.querySelector('[data-cancel]').onclick=()=>$('#qrModal').close();form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.tags=String(data.tags||'').split(',').map(x=>x.trim()).filter(Boolean);if(server){await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${id}`,{method:'PUT',body:JSON.stringify(data)});guests=await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests`)}else Object.assign(g,{name:data.name,phone:data.phone,email:data.email,group_name:data.groupName,household_id:data.householdId,table_name:data.tableName,seat_label:data.seatLabel,tags:data.tags});$('#qrModal').close();render()}}
async function checkIn(id){let g=guests.find(x=>x.id===id),checkedIn=!g.checked_in;if(server){await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${id}/check-in`,{method:'PUT',body:JSON.stringify({checkedIn})});guests=await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests`)}else{g.checked_in=checkedIn;g.checked_in_at=checkedIn?Date.now():null;localStorage.setItem(localKey,JSON.stringify(guests))}render()}
async function removeGuest(id){if(!(await uiConfirm(_txt('Remove this guest?','Remove this guest?'),{title:_txt('Remove guest','Remove guest'),danger:true,confirmText:_txt('Remove','Remove')})))return;if(server){await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${id}`,{method:'DELETE'});guests=await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests`)}else{guests=guests.filter(g=>g.id!==id);localStorage.setItem(localKey,JSON.stringify(guests))}render()}
async function rotateLink(g){let value=await uiPrompt(_txt('Optional expiration in days. Leave blank for no expiration.','Optional expiration in days. Leave blank for no expiration.'),'',{title:_txt('Rotate personal invitation link','Rotate personal invitation link'),confirmText:_txt('Rotate link','Rotate link')});if(value===null)return;const days=String(value).trim();const payload=await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${g.id}/token/rotate`,{method:'POST',body:JSON.stringify(days?{expiresDays:Number(days)}:{})});g.token=payload.token;g.token_expires_at=payload.tokenExpiresAt||null;g.token_revoked_at=null;g.personalLinkAvailable=true;return payload.token}
async function manageLink(id){let g=guests.find(x=>x.id===id);if(!g)return;if(!g.token){try{await rotateLink(g);render()}catch(error){alert(_txt(error.message||'Action failed','Action failed'))}return}const url=guestUrl(g);$('#qrBody').innerHTML=`<h2>${esc(g.name)}</h2><p>${_html('Personal invitation link','Personal invitation link')}</p><p class="personal-link-status">${g.token_expires_at?`${_html('Expires','Expires')} ${esc(new Date(g.token_expires_at).toLocaleString())}`:_html('No expiration set','No expiration set')}</p><div class="dialog-actions"><button id="copyPersonalLink">${_html('Copy personal link','Copy personal link')}</button><button id="rotatePersonalLink">${_html('Rotate link','Rotate link')}</button><button id="revokePersonalLink" class="danger">${_html('Revoke link','Revoke link')}</button></div>`;$('#qrModal').showModal();$('#copyPersonalLink').onclick=async()=>{await navigator.clipboard.writeText(url);$('#copyPersonalLink').textContent=_txt('Copied!','Copied!')};$('#rotatePersonalLink').onclick=async()=>{try{await rotateLink(g);$('#qrModal').close();render()}catch(error){alert(_txt(error.message||'Action failed','Action failed'))}};$('#revokePersonalLink').onclick=async()=>{if(!(await uiConfirm(_txt('Revoke this personal link? Existing copies and QR codes will stop working.','Revoke this personal link? Existing copies and QR codes will stop working.'),{title:_txt('Revoke personal link','Revoke personal link'),danger:true,confirmText:_txt('Revoke','Revoke')})))return;await request(`/api/invitations/${encodeURIComponent(inviteId)}/guests/${g.id}/token/revoke`,{method:'POST',body:'{}'});g.token=null;g.personalLinkAvailable=false;g.token_revoked_at=Date.now();$('#qrModal').close();render()}}
function showQr(id){let g=guests.find(x=>x.id===id);if(!g?.token)return manageLink(id);let url=guestUrl(g),qr=server?`/api/invitations/${encodeURIComponent(inviteId)}/guests/${encodeURIComponent(id)}/qr.png`:'';$('#qrBody').innerHTML=`<h2>${esc(g.name)}</h2>${qr?`<div id="qrImageWrap"><img id="guestQrImage" src="${qr}" alt="${_txt('QR code','QR code')} for ${esc(g.name)}" width="420" height="420"><p id="qrError" class="hint" hidden></p></div>`:`<p class="hint">${_html('Run the local server to generate a private QR code.','Run the local server to generate a private QR code.')}</p>`}<p><button id="copyLink">${_html('Copy personal link','Copy personal link')}</button>${qr?` <a id="downloadGuestQr" href="${qr}" download="${esc(g.name)}-qr.png" class="button-link">${_html('Download QR','Download QR')}</a>`:''}</p>`;$('#qrModal').showModal();const img=$('#guestQrImage'),download=$('#downloadGuestQr'),error=$('#qrError');if(img)img.onerror=()=>{img.hidden=true;if(download)download.hidden=true;if(error){error.hidden=false;error.textContent=_txt('QR generation is unavailable. The personal link can still be copied safely.','QR generation is unavailable. The personal link can still be copied safely.')}};$('#copyLink').onclick=async()=>{await navigator.clipboard.writeText(url);$('#copyLink').textContent=_txt('Copied!','Copied!')}}
$('.close').onclick=()=>$('#qrModal').close();
function parseCsv(text){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
$('#importFile').onchange=async e=>{let rows=parseCsv(await e.target.files[0].text()),start=/name/i.test(rows[0]?.[0]||'')?1:0,added=0;for(let i=start;i<rows.length;i++){if(!rows[i][0])continue;await addGuest({name:rows[i][0],phone:rows[i][1]||''});added++}render();alert(_txt('Imported %d guest(s).','Imported %d guest(s).').replace('%d',String(added)));e.target.value=''};
$('#exportBtn').onclick=()=>{let rows=[[_txt('Name','Name'),_txt('Phone','Phone'),_txt('Email','Email'),_txt('Group','Group'),_txt('Household','Household'),_txt('Table','Table'),_txt('Seat','Seat'),_txt('Tags','Tags'),rsvpEnabled?_txt('RSVP status','RSVP status'):_txt('Invitation mode','Invitation mode'),_txt('Checked in','Checked in'),_txt('Delivery','Delivery'),_txt('Opened','Opened'),_txt('Personal link','Personal link')],...guests.map(g=>[g.name,g.phone||'',g.email||'',g.group_name||'',g.household_id||'',g.table_name||'',g.seat_label||'',(g.tags||[]).join('|'),rsvpEnabled?(g.rsvp_status||_txt('Pending','Pending')):_txt('RSVP disabled','RSVP disabled'),g.checked_in?_txt('Yes','Yes'):_txt('No','No'),g.delivery_status||'',g.opened_at?new Date(g.opened_at).toISOString():'',guestUrl(g)])],csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='guest-list.csv';a.click();URL.createObjectURL(a.href)};
if(window.EInviteI18n&&typeof window.EInviteI18n.subscribe==='function'){window.EInviteI18n.subscribe(render)};
load();
