(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];if(!$('#stage'))return;
const selectedImage=()=>$$('.object.selected,.object.multi-selected').find(x=>x.dataset.objectType==='image')||null;const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)));
const dialog=document.createElement('dialog');dialog.className='ei-photo-dialog';dialog.innerHTML=`<div class="ei-photo-shell"><div class="ei-photo-stage"><span class="ei-photo-before">Edited preview</span><img alt="Photo edit preview"></div><aside class="ei-photo-panel"><div class="ei-photo-head"><h2>Edit photo</h2><button type="button" data-close>×</button></div><div class="ei-photo-controls"><fieldset><legend>Quick looks</legend><div class="ei-photo-presets"><button data-preset="original">Original</button><button data-preset="portrait">Portrait</button><button data-preset="vivid">Vivid</button><button data-preset="warm">Warm</button><button data-preset="mono">B&W</button><button data-preset="soft">Soft</button></div></fieldset><fieldset><legend>Adjust</legend><div data-sliders></div></fieldset><fieldset><legend>Transform</legend><div class="ei-photo-tools"><button data-tool="rotate-left">↶ Rotate</button><button data-tool="rotate-right">↷ Rotate</button><button data-tool="flip-x">↔ Flip H</button><button data-tool="flip-y">↕ Flip V</button><button data-tool="remove-bg">✦ Remove BG</button><button data-tool="replace">▣ Replace</button></div></fieldset><fieldset><legend>Crop & frame</legend><div class="ei-photo-selects"><label>Fit<select data-select="imageFit"><option value="cover">Crop to fill</option><option value="contain">Show full image</option></select></label><label>Mask<select data-select="imageMask"><option value="none">None</option><option value="circle">Circle</option><option value="arch">Arch</option><option value="diamond">Diamond</option><option value="hexagon">Hexagon</option><option value="blob">Blob</option></select></label><label>Frame<select data-select="imageFrame"><option value="none">None</option><option value="white">White</option><option value="gold">Gold</option><option value="dark">Dark</option></select></label></div></fieldset></div><div class="ei-photo-footer"><button type="button" data-revert>Revert session</button><button type="button" data-close class="primary">Done</button></div></aside></div>`;document.body.append(dialog);
const sliderDefs=[['imageBrightness','Brightness',20,200,100,'%'],['imageContrast','Contrast',20,200,100,'%'],['imageSaturation','Saturation',0,250,100,'%'],['imageHue','Hue',-180,180,0,'°'],['imageSepia','Warmth',0,100,0,'%'],['imageGrayscale','Grayscale',0,100,0,'%'],['imageBlur','Blur',0,20,0,'px']];const sliders=$('[data-sliders]',dialog);sliderDefs.forEach(([key,label,min,max,def,suffix])=>{const row=document.createElement('div');row.className='ei-photo-slider';row.innerHTML=`<label>${label}</label><input type="range" min="${min}" max="${max}" step="${key==='imageBlur'?'.1':'1'}" data-key="${key}"><output></output>`;row.dataset.suffix=suffix;sliders.append(row)});
let item=null,snapshot=null;const preview=$('.ei-photo-stage img',dialog);
function filter(o){return`brightness(${clamp(o.imageBrightness||100,20,200)}%) contrast(${clamp(o.imageContrast||100,20,200)}%) saturate(${clamp(o.imageSaturation||100,0,250)}%) grayscale(${clamp(o.imageGrayscale||0,0,100)}%) sepia(${clamp(o.imageSepia||0,0,100)}%) hue-rotate(${clamp(o.imageHue||0,-180,180)}deg) blur(${clamp(o.imageBlur||0,0,20)}px)`}
function apply(){if(!item)return;const img=item.querySelector('img');if(img){img.style.filter=filter(item.dataset);img.style.transform=`scaleX(${item.dataset.imageFlipX==='true'?-1:1}) scaleY(${item.dataset.imageFlipY==='true'?-1:1})`}try{typeof applyObjectVisualStyle==='function'&&applyObjectVisualStyle(item);typeof refreshSelectionUI==='function'&&refreshSelectionUI();typeof save==='function'&&save()}catch{}syncPreview()}
function syncPreview(){if(!item)return;const img=item.querySelector('img');preview.src=img?.src||'';preview.style.filter=filter(item.dataset);preview.style.transform=`rotate(${Number(item.dataset.rotation||0)}deg) scaleX(${item.dataset.imageFlipX==='true'?-1:1}) scaleY(${item.dataset.imageFlipY==='true'?-1:1})`;preview.style.objectFit=item.dataset.imageFit||'cover';sliderDefs.forEach(([key,,min,max,def])=>{const input=dialog.querySelector(`[data-key="${key}"]`);input.value=String(item.dataset[key]??def);input.closest('.ei-photo-slider').querySelector('output').textContent=`${input.value}${input.closest('.ei-photo-slider').dataset.suffix}`});$$('[data-select]',dialog).forEach(sel=>sel.value=item.dataset[sel.dataset.select]||'none')}
function open(){item=selectedImage();if(!item){window.uiToast?.('Select one image first.','!');return}snapshot={...item.dataset,src:item.querySelector('img')?.src||''};syncPreview();dialog.showModal()}
const imageControls=$('#imageControls');if(imageControls&&!$('#openPhotoEditor')){const b=document.createElement('button');b.id='openPhotoEditor';b.type='button';b.className='primary';b.textContent='Edit photo';imageControls.prepend(b);b.onclick=open}window.openEInvitePhotoEditor=open;
sliders.addEventListener('input',e=>{const input=e.target.closest('[data-key]');if(!input||!item)return;item.dataset[input.dataset.key]=input.value;input.closest('.ei-photo-slider').querySelector('output').textContent=`${input.value}${input.closest('.ei-photo-slider').dataset.suffix}`;apply()});
$$('[data-select]',dialog).forEach(sel=>sel.onchange=()=>{if(!item)return;item.dataset[sel.dataset.select]=sel.value;apply()});
const presets={original:{imageBrightness:100,imageContrast:100,imageSaturation:100,imageHue:0,imageSepia:0,imageGrayscale:0,imageBlur:0},portrait:{imageBrightness:105,imageContrast:102,imageSaturation:107,imageHue:0,imageSepia:5,imageGrayscale:0,imageBlur:.3},vivid:{imageBrightness:104,imageContrast:118,imageSaturation:135,imageHue:0,imageSepia:0,imageGrayscale:0,imageBlur:0},warm:{imageBrightness:104,imageContrast:106,imageSaturation:112,imageHue:0,imageSepia:24,imageGrayscale:0,imageBlur:0},mono:{imageBrightness:104,imageContrast:116,imageSaturation:100,imageHue:0,imageSepia:0,imageGrayscale:100,imageBlur:0},soft:{imageBrightness:108,imageContrast:92,imageSaturation:93,imageHue:0,imageSepia:7,imageGrayscale:0,imageBlur:.6}};
dialog.addEventListener('click',e=>{const p=e.target.closest('[data-preset]');if(p&&item){Object.entries(presets[p.dataset.preset]).forEach(([k,v])=>item.dataset[k]=String(v));apply()}const tool=e.target.closest('[data-tool]');if(tool&&item){const action=tool.dataset.tool;if(action==='rotate-left'||action==='rotate-right'){item.dataset.rotation=String((Number(item.dataset.rotation||0)+(action==='rotate-left'?-90:90)+360)%360)}if(action==='flip-x')item.dataset.imageFlipX=item.dataset.imageFlipX==='true'?'false':'true';if(action==='flip-y')item.dataset.imageFlipY=item.dataset.imageFlipY==='true'?'false':'true';if(action==='remove-bg')$('#aiBgCut')?.click();if(action==='replace')$('#aiReplaceImage')?.click();apply()}});
dialog.querySelector('[data-revert]').onclick=()=>{if(!item||!snapshot)return;Object.keys(item.dataset).forEach(k=>{if(!(k in snapshot))delete item.dataset[k]});Object.entries(snapshot).forEach(([k,v])=>item.dataset[k]=v);const img=item.querySelector('img');if(img)img.src=snapshot.src;apply()};$$('[data-close]',dialog).forEach(b=>b.onclick=()=>dialog.close());
})();
