const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),token=params.get('token')||'';
const _isKm=()=>(window.EInviteI18n&&window.EInviteI18n.get?window.EInviteI18n.get():(document.documentElement.lang||'').toLowerCase()).startsWith('km');
const _txt=(en,km)=>_isKm()?(km!=null?km:en):en;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function b(en,km){return`<span class="i18n i18n-en">${esc(en)}</span><span class="i18n i18n-km khmer-text" lang="km">${esc(km!=null?km:en)}</span>`}
async function api(path,body){const response=await fetch(path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Request failed');return data}
if(token){$('#requestView').hidden=true;$('#confirmView').hidden=false}
$('#requestForm').onsubmit=async e=>{e.preventDefault();const status=$('#requestStatus');status.textContent=_txt('Requesting reset link…','Requesting reset link…');try{const result=await api('/api/auth/password-reset/request',{email:new FormData(e.target).get('email')});status.innerHTML=result.sent?b('If the account exists, a reset link has been sent.','If the account exists, a reset link has been sent.'):b('The request was accepted, but email delivery is not configured on this server. Contact the administrator or configure SMTP.','The request was accepted, but email delivery is not configured on this server. Contact the administrator or configure SMTP.');if(result.devToken)status.innerHTML+=`<br><a href="reset.html?token=${encodeURIComponent(result.devToken)}">${b('Development reset link','Development reset link')}</a>`}catch(error){status.textContent=error.message}}
$('#confirmForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),status=$('#confirmStatus');if(data.newPassword!==data.confirmPassword){status.textContent=_txt('The passwords do not match.','The passwords do not match.');return}status.textContent=_txt('Resetting password…','Resetting password…');try{await api('/api/auth/password-reset/confirm',{token,newPassword:data.newPassword});status.classList.add('success');status.innerHTML=b('Password changed successfully. ','Password changed successfully. ')+`<a href="dashboard.html">${b('Return to sign in','Return to sign in')}</a>`;e.target.reset()}catch(error){status.textContent=error.message}}
if(window.EInviteI18n&&typeof window.EInviteI18n.subscribe==='function'){window.EInviteI18n.subscribe(function(){})}
