const $=s=>document.querySelector(s),inviteId=window.EInviteContext?.getInvitationId()||'demo-wedding';localStorage.removeItem('sovan-auth-token');let responses=[],wishes=[],documentData={},server=false,rsvpEnabled=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const _isKm=()=>(window.EInviteI18n&&window.EInviteI18n.get?window.EInviteI18n.get():(document.documentElement.lang||'').toLowerCase()).startsWith('km');
const _txt=(en,km)=>_isKm()?(km!=null?km:en):en;
const b=(en,km)=>`<span class="i18n i18n-en">${esc(en)}</span><span class="i18n i18n-km khmer-text" lang="km">${esc(km!=null?km:en)}</span>`;
async function request(path,options={}){const r=await fetch(path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',}}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Request failed');return data}
function customLabels(){return Object.fromEntries((documentData.rsvpFields||[]).map(f=>[`custom_${f.id}`,f.label||f.labelKm||f.id]))}
function metrics(){if(!rsvpEnabled){$('#metrics').innerHTML=`<div class="response-metric"><strong>${b('Disabled','Disabled')}</strong>${b('RSVP status','RSVP status')}</div><div class="response-metric"><strong>${responses.length}</strong>${b('Historical responses','Historical responses')}</div><div class="response-metric"><strong>${wishes.length}</strong>${b('Guest wishes','Guest wishes')}</div>`;return}const yes=responses.filter(r=>String(r.status).startsWith('Yes')),no=responses.filter(r=>String(r.status).startsWith('Unable')),maybe=responses.filter(r=>r.status==='Maybe'),guests=yes.reduce((n,r)=>n+Number(r.guest_count||r.count||1),0);$('#metrics').innerHTML=`<div class="response-metric"><strong>${responses.length}</strong>${b("Responses","Responses")}</div><div class="response-metric"><strong>${yes.length}</strong>${b("Attending replies","Attending replies")}</div><div class="response-metric"><strong>${guests}</strong>${b("Attending guests","Attending guests")}</div><div class="response-metric"><strong>${wishes.length}</strong>Guest wishes</div>`}
function filteredResponses(){const q=$('#responseSearch').value.trim().toLowerCase(),filter=$('#responseFilter').value;return responses.filter(r=>{const text=`${r.name} ${r.status} ${r.note||''} ${Object.values(r.answers||{}).join(' ')}`.toLowerCase(),status=String(r.status||'');return text.includes(q)&&(filter==='all'||filter==='yes'&&status.startsWith('Yes')||filter==='no'&&status.startsWith('Unable')||filter==='maybe'&&status==='Maybe')})}
function renderResponses(){const labels=customLabels(),items=filteredResponses();$('#responseList').innerHTML=items.length?items.map(r=>`<article class="response-card" data-id="${esc(r.id)}"><div><h3>${esc(r.name)}</h3><p>${esc(r.note||_txt('No message','No message'))}</p>${Object.entries(r.answers||{}).filter(([,v])=>String(v||'').trim()).map(([k,v])=>`<div class="custom-answer"><strong>${esc(labels[k]||k.replace(/^custom_/,''))}:</strong> ${esc(v)}</div>`).join('')}</div><label>Status<select data-status><option ${r.status==='Yes, joyfully'?'selected':''}>Yes, joyfully</option><option ${r.status==='Unable to attend'?'selected':''}>Unable to attend</option><option ${r.status==='Maybe'?'selected':''}>Maybe</option></select></label><label>Guests<input data-count type="number" min="1" max="10" value="${Number(r.guest_count||r.count||1)}"></label><div><button data-save>${b("Save","រក្សាទុក")}</button><button class="danger" data-delete>${b("Delete","លុប")}</button><small style="display:block;margin-top:8px">${new Date(r.created_at||r.createdAt||Date.now()).toLocaleString()}</small></div></article>`).join(''):`<div class="empty-state">${b('No RSVP responses match this view.','No RSVP responses match this view.')}</div>`;document.querySelectorAll('.response-card').forEach(card=>{card.querySelector('[data-save]').onclick=()=>saveResponse(card);card.querySelector('[data-delete]').onclick=()=>deleteResponse(card.dataset.id)})}
function renderWishes(){$('#wishList').innerHTML=wishes.length?wishes.map(w=>`<article class="wish-card"><h3>${esc(w.name)}</h3><p>${esc(w.message)}</p><small>${new Date(w.createdAt||w.created_at||Date.now()).toLocaleString()}</small>${server?`<p><button class="danger" data-delete-wish="${esc(w.id)}">${b("Delete","លុប")}</button></p>`:''}</article>`).join(''):`<div class="empty-state">${b('No private guest wishes yet.','No private guest wishes yet.')}</div>`;document.querySelectorAll('[data-delete-wish]').forEach(b=>b.onclick=()=>deleteWish(b.dataset.deleteWish))}
async function saveResponse(card){if(!server)return;const id=card.dataset.id,status=card.querySelector('[data-status]').value,guestCount=Number(card.querySelector('[data-count]').value||1),button=card.querySelector('[data-save]');button.disabled=true;try{await request(`/api/invitations/${inviteId}/rsvps/${id}`,{method:'PUT',body:JSON.stringify({status,guestCount})});const item=responses.find(x=>x.id===id);if(item){item.status=status;item.guest_count=guestCount}metrics();button.textContent=_txt('Saved','Saved');setTimeout(()=>button.textContent=_txt('Save','Save'),1000)}catch(err){alert(err.message)}finally{button.disabled=false}}
async function deleteResponse(id){if(!server||!(await uiConfirm(_txt('Delete this RSVP response?','Delete this RSVP response?'),{title:_txt('Delete RSVP response','Delete RSVP response'),danger:true,confirmText:'Delete'})))return;try{await request(`/api/invitations/${inviteId}/rsvps/${id}`,{method:'DELETE'});responses=responses.filter(x=>x.id!==id);metrics();renderResponses()}catch(err){alert(err.message)}}
async function deleteWish(id){if(!server||!(await uiConfirm(_txt('Delete this guest wish?','Delete this guest wish?'),{title:_txt('Delete guest wish','Delete guest wish'),danger:true,confirmText:'Delete'})))return;try{await request(`/api/invitations/${inviteId}/wishes/${id}`,{method:'DELETE'});wishes=wishes.filter(x=>x.id!==id);metrics();renderWishes()}catch(err){alert(err.message)}}
function csvCell(v){return`"${String(v??'').replaceAll('"','""')}"`}
$('#exportRsvp').onclick=()=>{const fields=documentData.rsvpFields||[],rows=[['Name','Status','Guest count','Message',...fields.map(f=>f.label||f.labelKm||f.id)],...responses.map(r=>[r.name,r.status,r.guest_count||r.count||1,r.note||'',...fields.map(f=>(r.answers||{})[`custom_${f.id}`]||'')])],csv=rows.map(row=>row.map(csvCell).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='rsvp-responses.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#responseSearch').oninput=renderResponses;$('#responseFilter').onchange=renderResponses;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#rsvpPanel').classList.toggle('hidden',b.dataset.tab!=='rsvp');$('#wishesPanel').classList.toggle('hidden',b.dataset.tab!=='wishes')});
async function load(){if(window.EInviteBackend?.ready)await window.EInviteBackend.ready;if(window.EInviteBackend&&!window.EInviteBackend.isAvailable()){server=false;documentData=JSON.parse(localStorage.getItem(`sovan-invite-draft-v3:${inviteId}`)||'{}');responses=JSON.parse(localStorage.getItem(`sovan-invite-rsvps-v3:${inviteId}`)||'[]');wishes=JSON.parse(localStorage.getItem(`sovan-invite-wishes-v1:${inviteId}`)||'[]');window.EInviteBackend.message($('#rsvpPanel'),'<span class="i18n i18n-en">RSVP responses and guest wishes require the full application server.</span><span class="i18n i18n-km khmer-text" lang="km">RSVP responses and guest wishes require the full application server.</span>');metrics();renderWishes();return}try{await request('/api/health');server=true;const invite=await request(`/api/invitations/${inviteId}`);documentData=invite.document||{};rsvpEnabled=documentData.settings?.rsvpEnabled!==false;[responses,wishes]=await Promise.all([request(`/api/invitations/${inviteId}/rsvps`),request(`/api/invitations/${inviteId}/wishes`)]);}catch{server=false;documentData=JSON.parse(localStorage.getItem(`sovan-invite-draft-v3:${inviteId}`)||'{}');responses=JSON.parse(localStorage.getItem(`sovan-invite-rsvps-v3:${inviteId}`)||'[]');wishes=JSON.parse(localStorage.getItem(`sovan-invite-wishes-v1:${inviteId}`)||'[]')}metrics();renderResponses();renderWishes()}
load();
if(window.EInviteI18n&&typeof window.EInviteI18n.subscribe==='function'){window.EInviteI18n.subscribe(metrics)}
