"""Auto-generation of long-lived server secrets for the V54 hardening pass.

The platform's existing ``persistent_data_secret`` helper in ``server.py``
writes secrets to a per-data-dir sidecar file (``.upload-signing-secret`` etc.)
so the value survives a restart. That works well for signing secrets that the
runtime reads via ``platform_env(...)``, but ``SECRET_KEY`` and
``BILLING_WEBHOOK_SECRET`` are sometimes configured via the repo-root ``.env``
file. This module ensures those two values exist (a) in the loaded environment
so the running process picks them up immediately, and (b) appended to
``.env`` at the repo root so subsequent launches find the same value.

The module never overwrites a non-placeholder value already present in either
``os.environ`` or ``.env``.
"""
from __future__ import annotations

import os
import re
import secrets
from pathlib import Path
from typing import Optional

# Values that look like documentation/example placeholders and MUST be replaced.
# Matches the convention used by ``production_preflight.PLACEHOLDER``.
_PLACEHOLDER_RE = re.compile(
    r"(?:^|[-_ ])(?:change|replace|example|placeholder|your[-_ ]?|"
    r"secret[-_ ]?manager|password|todo|xxxx+)(?:$|[-_ ])",
    re.IGNORECASE,
)

# Repo root: this file lives at src/python/secrets_v54.py, so the repo root is
# two parents up. We resolve lazily so a relocated module still works.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_ENV_PATH = _REPO_ROOT / ".env"


def _is_placeholder(value: str) -> bool:
    """Return ``True`` when ``value`` looks like a documentation placeholder."""
    stripped = (value or "").strip()
    if not stripped:
        return True
    if _PLACEHOLDER_RE.search(stripped):
        return True
    # Also treat very short values as placeholders: a 16-char "changeme" still
    # matches above; a random 8-char string does not, but is too short for a
    # server secret, so we treat it as a placeholder too.
    return len(stripped) < 16


def _read_env_file(path: Path) -> dict[str, str]:
    """Read a ``.env``-style file into a dict without evaluating quotes.

    Args:
        path: Filesystem path to the ``.env`` file. Need not exist.

    Returns:
        A mapping of variable name to raw value (without the leading ``name=``
        and without surrounding quotes). Comments and blank lines are skipped.
    """
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return values
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        name, _, value = line.partition("=")
        name = name.strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        values[name] = value
    return values


def _append_to_env_file(path: Path, name: str, value: str) -> None:
    """Append a ``name=value`` line to the repo-root ``.env`` file.

    A comment line is written above the assignment so operators can see that
    the value was generated by this module and rotate it if they wish. The
    file is created (with mode 0600) when absent; existing content is never
    rewritten. If the key already exists in the file (placeholder or not), we
    do NOT append again — the caller has already decided the in-process value
    is the source of truth.

    Args:
        path: Filesystem path to the ``.env`` file.
        name: Environment variable name.
        value: Generated secret value.
    """
    existing = _read_env_file(path)
    if name in existing:
        # Even if the existing value is a placeholder, we never auto-rewrite
        # the .env file in place — that risks corrupting operator comments and
        # ordering. The in-process env still carries the generated value so
        # the current launch is safe; the operator must replace the placeholder
        # in the .env file manually.
        return
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        newline_needed = path.exists() and not path.read_bytes().endswith(b"\n")
        with path.open("a", encoding="utf-8") as handle:
            if newline_needed:
                handle.write("\n")
            handle.write("# auto-generated by secrets_v54 — change if needed\n")
            handle.write(f"{name}={value}\n")
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass
    except OSError:
        # Best-effort: the in-process env is already populated; failure to
        # persist to disk only means the next launch will regenerate.
        pass


def ensure_secret(name: str, length: int = 64) -> str:
    """Ensure that a long-lived secret exists in the environment (and ``.env``).

    Resolution order:
      1. ``os.environ[name]`` — if a non-placeholder value is already present,
         return it unchanged.
      2. Repo-root ``.env`` — if a non-placeholder value is present there,
         promote it into ``os.environ`` and return it.
      3. Otherwise, generate ``secrets.token_urlsafe(length)``, write it into
         ``os.environ[name]`` so the running process picks it up, AND append it
         to the repo-root ``.env`` (with a comment) for the next launch.

    Args:
        name: Environment variable name (must match ``[A-Za-z_][A-Za-z0-9_]*``).
        length: The number of random bytes to feed ``secrets.token_urlsafe``.
            The resulting string is ~33% longer after base64url encoding, so
            ``length=64`` yields ~86 characters — comfortably above the
            32-character floor used by ``production_preflight``.

    Returns:
        The secret value now visible in ``os.environ``.

    Raises:
        ValueError: When ``name`` is not a valid environment variable name.
    """
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name or ""):
        raise ValueError(f"invalid environment variable name: {name!r}")
    if length < 32:
        # Refuse to generate something shorter than the project's preflight floor.
        length = 32

    current = os.environ.get(name, "").strip()
    if current and not _is_placeholder(current):
        return current

    file_value: Optional[str] = _read_env_file(_ENV_PATH).get(name, "").strip()
    if file_value and not _is_placeholder(file_value):
        os.environ[name] = file_value
        return file_value

    generated = secrets.token_urlsafe(length)
    os.environ[name] = generated
    _append_to_env_file(_ENV_PATH, name, generated)
    return generated
